In [2]:
import pandas as pd
import requests
import time

# ── 1. Load your CSV ──────────────────────────────────────────────────────────
# Update this path to wherever you saved the CSV
df = pd.read_csv('byzantine_emperors.csv')

def get_wiki_image(name):
    """Fetch the main image URL from Wikipedia for a given search term."""
    session = requests.Session()
    url = "https://en.wikipedia.org/w/api.php"
    
    # First, search for the most likely page title
    search_params = {
        "action": "query",
        "list": "search",
        "srsearch": name + " Byzantine emperor",
        "format": "json",
        "srlimit": 1
    }
    
    try:
        search_resp = session.get(url, params=search_params, timeout=10)
        search_data = search_resp.json()
        results = search_data.get("query", {}).get("search", [])
        
        if not results:
            print(f"  No search result for: {name}")
            return "NOT_FOUND"
        
        page_title = results[0]["title"]
        
        # Now fetch the page image using the resolved title
        image_params = {
            "action": "query",
            "titles": page_title,
            "prop": "pageimages",
            "pithumbsize": 400,
            "format": "json"
        }
        
        img_resp = session.get(url, params=image_params, timeout=10)
        img_data = img_resp.json()
        pages = img_data.get("query", {}).get("pages", {})
        
        for page in pages.values():
            thumb = page.get("thumbnail", {}).get("source", "NO_IMAGE")
            print(f"  {name} → {page_title} → {thumb[:60]}...")
            return thumb
            
    except Exception as e:
        print(f"  ERROR for {name}: {e}")
        return "ERROR"

# ── 2. Loop through emperors and fetch images ─────────────────────────────────
print("Fetching Wikipedia images...\n")

image_urls = []
for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    print(f"[{idx+1}/{len(df)}] {name}")
    img_url = get_wiki_image(name)
    image_urls.append(img_url)
    time.sleep(0.5)  # be polite to the Wikipedia API

# ── 3. Write URLs back to the dataframe and save ──────────────────────────────
df['Image_URL'] = image_urls
df.to_csv('byzantine_emperors_with_images.csv', index=False)

print("\nDone! Saved as byzantine_emperors_with_images.csv")

# ── 4. Quick summary of results ───────────────────────────────────────────────
found     = sum(1 for u in image_urls if u not in ("NOT_FOUND", "NO_IMAGE", "ERROR"))
not_found = sum(1 for u in image_urls if u == "NOT_FOUND")
no_image  = sum(1 for u in image_urls if u == "NO_IMAGE")
errors    = sum(1 for u in image_urls if u == "ERROR")

print(f"\nResults summary:")
print(f"  Images found : {found}")
print(f"  Not found    : {not_found}")
print(f"  No image     : {no_image}")
print(f"  Errors       : {errors}")

FileNotFoundError: [Errno 2] No such file or directory: 'byzantine_emperors.csv'

In [ ]:
import pandas as pd
import requests
import time

# ── 1. Load your CSV ──────────────────────────────────────────────────────────
# Update this path to wherever you saved the CSV
df = pd.read_csv('ERE_List_20260226.csv')

def get_wiki_image(name):
    """Fetch the main image URL from Wikipedia for a given search term."""
    session = requests.Session()
    url = "https://en.wikipedia.org/w/api.php"
    
    # First, search for the most likely page title
    search_params = {
        "action": "query",
        "list": "search",
        "srsearch": name + " Byzantine emperor",
        "format": "json",
        "srlimit": 1
    }
    
    try:
        search_resp = session.get(url, params=search_params, timeout=10)
        search_data = search_resp.json()
        results = search_data.get("query", {}).get("search", [])
        
        if not results:
            print(f"  No search result for: {name}")
            return "NOT_FOUND"
        
        page_title = results[0]["title"]
        
        # Now fetch the page image using the resolved title
        image_params = {
            "action": "query",
            "titles": page_title,
            "prop": "pageimages",
            "pithumbsize": 400,
            "format": "json"
        }
        
        img_resp = session.get(url, params=image_params, timeout=10)
        img_data = img_resp.json()
        pages = img_data.get("query", {}).get("pages", {})
        
        for page in pages.values():
            thumb = page.get("thumbnail", {}).get("source", "NO_IMAGE")
            print(f"  {name} → {page_title} → {thumb[:60]}...")
            return thumb
            
    except Exception as e:
        print(f"  ERROR for {name}: {e}")
        return "ERROR"

# ── 2. Loop through emperors and fetch images ─────────────────────────────────
print("Fetching Wikipedia images...\n")

image_urls = []
for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    print(f"[{idx+1}/{len(df)}] {name}")
    img_url = get_wiki_image(name)
    image_urls.append(img_url)
    time.sleep(0.5)  # be polite to the Wikipedia API

# ── 3. Write URLs back to the dataframe and save ──────────────────────────────
df['Image_URL'] = image_urls
df.to_csv('byzantine_emperors_with_images.csv', index=False)

print("\nDone! Saved as byzantine_emperors_with_images.csv")

# ── 4. Quick summary of results ───────────────────────────────────────────────
found     = sum(1 for u in image_urls if u not in ("NOT_FOUND", "NO_IMAGE", "ERROR"))
not_found = sum(1 for u in image_urls if u == "NOT_FOUND")
no_image  = sum(1 for u in image_urls if u == "NO_IMAGE")
errors    = sum(1 for u in image_urls if u == "ERROR")

print(f"\nResults summary:")
print(f"  Images found : {found}")
print(f"  Not found    : {not_found}")
print(f"  No image     : {no_image}")
print(f"  Errors       : {errors}")

In [ ]:
import pandas as pd
import requests
import time

# ── 1. Load your CSV ──────────────────────────────────────────────────────────
# Update this path to wherever you saved the CSV
df = pd.read_csv('ERE_List_20260226.csv')

def get_wiki_image(name):
    """Fetch the main image URL from Wikipedia for a given search term."""
    session = requests.Session()
    session.headers.update({
        'User-Agent': 'ByzantineEmperorsTool/1.0 (educational project; ecocinar@gmail.com)'
    })
    url = "https://en.wikipedia.org/w/api.php"
    
    # First, search for the most likely page title
    search_params = {
        "action": "query",
        "list": "search",
        "srsearch": name + " Byzantine emperor",
        "format": "json",
        "srlimit": 1
    }
    
    try:
        search_resp = session.get(url, params=search_params, timeout=10)
        search_data = search_resp.json()
        results = search_data.get("query", {}).get("search", [])
        
        if not results:
            print(f"  No search result for: {name}")
            return "NOT_FOUND"
        
        page_title = results[0]["title"]
        
        # Now fetch the page image using the resolved title
        image_params = {
            "action": "query",
            "titles": page_title,
            "prop": "pageimages",
            "pithumbsize": 400,
            "format": "json"
        }
        
        img_resp = session.get(url, params=image_params, timeout=10)
        img_data = img_resp.json()
        pages = img_data.get("query", {}).get("pages", {})
        
        for page in pages.values():
            thumb = page.get("thumbnail", {}).get("source", "NO_IMAGE")
            print(f"  {name} → {page_title} → {thumb[:60]}...")
            return thumb
            
    except Exception as e:
        print(f"  ERROR for {name}: {e}")
        return "ERROR"

# ── 2. Loop through emperors and fetch images ─────────────────────────────────
print("Fetching Wikipedia images...\n")

image_urls = []
for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    print(f"[{idx+1}/{len(df)}] {name}")
    img_url = get_wiki_image(name)
    image_urls.append(img_url)
    time.sleep(1.5)  # be polite to the Wikipedia API

# ── 3. Write URLs back to the dataframe and save ──────────────────────────────
df['Image_URL'] = image_urls
df.to_csv('ERE_List_20260226.csv', index=False)

print("\nDone! Saved as byzantine_emperors_with_images.csv")

# ── 4. Quick summary of results ───────────────────────────────────────────────
found     = sum(1 for u in image_urls if u not in ("NOT_FOUND", "NO_IMAGE", "ERROR"))
not_found = sum(1 for u in image_urls if u == "NOT_FOUND")
no_image  = sum(1 for u in image_urls if u == "NO_IMAGE")
errors    = sum(1 for u in image_urls if u == "ERROR")

print(f"\nResults summary:")
print(f"  Images found : {found}")
print(f"  Not found    : {not_found}")
print(f"  No image     : {no_image}")
print(f"  Errors       : {errors}")

In [ ]:
import pandas as pd

# Load the CSV with image URLs
df = pd.read_csv('byzantine_emperors_with_images.csv')

# Build HTML
rows_html = ""
for _, row in df.iterrows():
    img_url = row['Image_URL']
    num = row['List_Number']
    name = row['Simple_Name_With_Epithets']
    dynasty = row['Broad_Dynasty']
    reign = f"{row['Reign_Start']} – {row['Reign_End']}"

    if img_url in ("NOT_FOUND", "NO_IMAGE", "ERROR", "PLACEHOLDER"):
        img_tag = "<div style='width:120px;height:150px;background:#333;display:flex;align-items:center;justify-content:center;color:#888;font-size:12px;'>No Image</div>"
    else:
        img_tag = f"<img src='{img_url}' style='width:120px;height:150px;object-fit:cover;border-radius:4px;' onerror=\"this.style.display='none'\">"

    rows_html += f"""
    <div style='display:flex;align-items:center;gap:16px;padding:12px;border-bottom:1px solid #2a2a2a;'>
        <div style='color:#666;width:30px;text-align:right;font-size:13px;'>{num}</div>
        {img_tag}
        <div>
            <div style='color:#e8e8e8;font-size:15px;font-weight:600;'>{name}</div>
            <div style='color:#888;font-size:13px;margin-top:4px;'>{dynasty} &nbsp;|&nbsp; {reign}</div>
            <div style='margin-top:8px;'>
                <a href='{img_url}' target='_blank' style='color:#5b9bd5;font-size:12px;'>View image URL</a>
            </div>
        </div>
    </div>
    """

html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title>Byzantine Emperors – Image Check</title>
    <style>
        body {{ background:#1a1a1a; color:#e8e8e8; font-family:sans-serif; max-width:800px; margin:40px auto; padding:0 20px; }}
        h1 {{ color:#c8a96e; border-bottom:1px solid #333; padding-bottom:12px; }}
        p  {{ color:#888; font-size:13px; }}
    </style>
</head>
<body>
    <h1>Byzantine Emperors – Image Verification</h1>
    <p>Scroll through and check each image is the correct emperor. Click "View image URL" to open the source.</p>
    {rows_html}
</body>
</html>"""

output_path = 'byzantine_image_check.html'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(html)

print(f"Done! Open this file in your browser: {output_path}")

In [ ]:
import pandas as pd
import requests
import time

# ── Correct Wikipedia page titles for problem entries ─────────────────────────
# Key = Simple_Name_With_Epithets from your CSV
# Value = exact Wikipedia page title to use instead of searching
OVERRIDES = {
    "Constantine I the Great":       "Constantine the Great",
    "Constantinus II":               "Constantius II",  # NOTE: verify this is correct
    "Constantius II":                "Constantius II",
    "Valens":                        "Valens",
    "Gratian":                       "Gratian",
    "Anastasios I":                  "Anastasius I (emperor)",
    "Justinian I the Great":         "Justinian I",
    "Phokas (Usurper)":              "Phocas",
    "Heraklonas":                    "Heraklonas",
    "Leontios (Usurper)":            "Leontios (emperor)",
    "Artabasdos (Usurper)":         "Artabasdos",
    "Michael II the Amorian":        "Michael II",
    "Zoe (with Theodora)":           "Zoe (empress)",
    "John II Komnenos":              "John II Comnenus",
    "Manuel I Komnenos":             "Manuel I Komnenos",
    "John V Palaiologos":            "John V Palaiologos",  # will use direct URL below
}

# Direct Wikimedia image URLs for specific cases where we want a specific image
DIRECT_URLS = {
    "Justinian I the Great": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg/400px-Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg",
    "Zoe (with Theodora)":   "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Zoe_mosaic_Hagia_Sophia.jpg/400px-Zoe_mosaic_Hagia_Sophia.jpg",
    "John II Komnenos":      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/John_II_Comnenus_mosaic_Hagia_Sophia.jpg/400px-John_II_Comnenus_mosaic_Hagia_Sophia.jpg",
    "John V Palaiologos":    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg/400px-Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg",
}

def get_wiki_image_by_title(page_title, session):
    """Fetch thumbnail image URL from Wikipedia using an exact page title."""
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action":      "query",
        "titles":      page_title,
        "prop":        "pageimages",
        "pithumbsize": 400,
        "format":      "json"
    }
    try:
        resp = session.get(url, params=params, timeout=10)
        data = resp.json()
        pages = data.get("query", {}).get("pages", {})
        for page in pages.values():
            return page.get("thumbnail", {}).get("source", "NO_IMAGE")
    except Exception as e:
        print(f"    ERROR: {e}")
        return "ERROR"

# ── Load CSV ──────────────────────────────────────────────────────────────────
df = pd.read_csv('ERE_List_20260226.csv')

session = requests.Session()
session.headers.update({
    'User-Agent': 'ByzantineEmperorsTool/1.0 (educational project; ecocinar@gmail.com)'
})

print("Fixing problem image URLs...\n")
fixed = 0

for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    
    if name not in OVERRIDES and name not in DIRECT_URLS:
        continue  # skip entries that don't need fixing
    
    print(f"Fixing: {name}")
    
    if name in DIRECT_URLS:
        df.at[idx, 'Image_URL'] = DIRECT_URLS[name]
        print(f"  → Direct URL applied")
        fixed += 1
    else:
        page_title = OVERRIDES[name]
        img_url = get_wiki_image_by_title(page_title, session)
        df.at[idx, 'Image_URL'] = img_url
        print(f"  → {img_url[:80]}...")
        fixed += 1
        time.sleep(1.0)

# ── Save updated CSV ──────────────────────────────────────────────────────────
df.to_csv('ERE_List_20260226.csv', index=False)
print(f"\nDone! Fixed {fixed} entries. CSV updated.")

In [ ]:
df = pd.read_csv('ERE_List_20260226.csv')

In [35]:
import pandas as pd

# Load the CSV with image URLs
df = pd.read_csv('ERE_List_20260226.csv')

# Build HTML
rows_html = ""
for _, row in df.iterrows():
    img_url = row['Image_URL']
    num = row['List_Number']
    name = row['Simple_Name_With_Epithets']
    dynasty = row['Broad_Dynasty']
    reign = f"{row['Reign_Start']} – {row['Reign_End']}"

    if img_url in ("NOT_FOUND", "NO_IMAGE", "ERROR", "PLACEHOLDER"):
        img_tag = "<div style='width:120px;height:150px;background:#333;display:flex;align-items:center;justify-content:center;color:#888;font-size:12px;'>No Image</div>"
    else:
        img_tag = f"<img src='{img_url}' style='width:120px;height:150px;object-fit:cover;border-radius:4px;' onerror=\"this.style.display='none'\">"

    rows_html += f"""
    <div style='display:flex;align-items:center;gap:16px;padding:12px;border-bottom:1px solid #2a2a2a;'>
        <div style='color:#666;width:30px;text-align:right;font-size:13px;'>{num}</div>
        {img_tag}
        <div>
            <div style='color:#e8e8e8;font-size:15px;font-weight:600;'>{name}</div>
            <div style='color:#888;font-size:13px;margin-top:4px;'>{dynasty} &nbsp;|&nbsp; {reign}</div>
            <div style='margin-top:8px;'>
                <a href='{img_url}' target='_blank' style='color:#5b9bd5;font-size:12px;'>View image URL</a>
            </div>
        </div>
    </div>
    """

html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title>Byzantine Emperors – Image Check</title>
    <style>
        body {{ background:#1a1a1a; color:#e8e8e8; font-family:sans-serif; max-width:800px; margin:40px auto; padding:0 20px; }}
        h1 {{ color:#c8a96e; border-bottom:1px solid #333; padding-bottom:12px; }}
        p  {{ color:#888; font-size:13px; }}
    </style>
</head>
<body>
    <h1>Byzantine Emperors – Image Verification</h1>
    <p>Scroll through and check each image is the correct emperor. Click "View image URL" to open the source.</p>
    {rows_html}
</body>
</html>"""

output_path = 'byzantine_image_check.html'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(html)

print(f"Done! Open this file in your browser: {output_path}")

Done! Open this file in your browser: byzantine_image_check.html

In [ ]:
import pandas as pd
import requests
import time

# ── Correct Wikipedia page titles for problem entries ─────────────────────────
# Key = Simple_Name_With_Epithets from your CSV
# Value = exact Wikipedia page title to use instead of searching
OVERRIDES = {
    "Constantine I the Great":       "Constantine the Great",
    "Constantinus II":               "Constantius II",  # NOTE: verify this is correct
    "Constantius II":                "Constantius II",
    "Valens":                        "Valens",
    "Gratian":                       "Gratian",
    "Anastasios I":                  "Anastasius I (emperor)",
    "Justinian I the Great":         "Justinian I",
    "Phokas (Usurper)":              "Phocas",
    "Heraklonas":                    "Heraklonas",
    "Leontios (Usurper)":            "Leontios (emperor)",
    "Artabasdos (Usurper)":         "Artabasdos",
    "Michael II the Amorian":        "Michael II",
    "Zoe (with Theodora)":           "Zoe (empress)",
    "John II Komnenos":              "John II Comnenus",
    "Manuel I Komnenos":             "Manuel I Komnenos",
    "John V Palaiologos":            "John V Palaiologos",  # will use direct URL below
}

# Direct Wikimedia image URLs for specific cases where we want a specific image
DIRECT_URLS = {
    "Justinian I the Great": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg/400px-Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg",
    "Zoe (with Theodora)":   "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Zoe_mosaic_Hagia_Sophia.jpg/400px-Zoe_mosaic_Hagia_Sophia.jpg",
    "John II Komnenos":      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/John_II_Comnenus_mosaic_Hagia_Sophia.jpg/400px-John_II_Comnenus_mosaic_Hagia_Sophia.jpg",
    "John V Palaiologos":    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg/400px-Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg",
    "Anastasios I":          "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Flavius_Anastasius_Probus_01c_%28Anastasius_I%29_%28cropped%29.JPG/400px-Flavius_Anastasius_Probus_01c_%28Anastasius_I%29_%28cropped%29.JPG",
    "Heraklonas":            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Heraclonas_on_Solidus.jpg/400px-Heraclonas_on_Solidus.jpg",
    "Leontios (Usurper)":    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Solidus_of_Leontius.png/400px-Solidus_of_Leontius.png",
}

def get_wiki_image_by_title(page_title, session):
    """Fetch thumbnail image URL from Wikipedia using an exact page title."""
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action":      "query",
        "titles":      page_title,
        "prop":        "pageimages",
        "pithumbsize": 400,
        "format":      "json"
    }
    try:
        resp = session.get(url, params=params, timeout=10)
        data = resp.json()
        pages = data.get("query", {}).get("pages", {})
        for page in pages.values():
            return page.get("thumbnail", {}).get("source", "NO_IMAGE")
    except Exception as e:
        print(f"    ERROR: {e}")
        return "ERROR"

# ── Load CSV ──────────────────────────────────────────────────────────────────
df = pd.read_csv('byzantine_emperors_with_images.csv')

session = requests.Session()
session.headers.update({
    'User-Agent': 'ByzantineEmperorsTool/1.0 (educational project; your@email.com)'
})

print("Fixing problem image URLs...\n")
fixed = 0

for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    
    if name not in OVERRIDES and name not in DIRECT_URLS:
        continue  # skip entries that don't need fixing
    
    print(f"Fixing: {name}")
    
    if name in DIRECT_URLS:
        df.at[idx, 'Image_URL'] = DIRECT_URLS[name]
        print(f"  → Direct URL applied")
        fixed += 1
    else:
        page_title = OVERRIDES[name]
        img_url = get_wiki_image_by_title(page_title, session)
        df.at[idx, 'Image_URL'] = img_url
        print(f"  → {img_url[:80]}...")
        fixed += 1
        time.sleep(1.0)

# ── Save updated CSV ──────────────────────────────────────────────────────────
df.to_csv('byzantine_emperors_with_images.csv', index=False)
print(f"\nDone! Fixed {fixed} entries. CSV updated.")

In [ ]:
df = pd.read_csv('ERE_List_20260226.csv')

In [ ]:
import pandas as pd
import requests
import time

# ── Correct Wikipedia page titles for problem entries ─────────────────────────
# Key = Simple_Name_With_Epithets from your CSV
# Value = exact Wikipedia page title to use instead of searching
OVERRIDES = {
    "Constantine I the Great":       "Constantine the Great",
    "Constantinus II":               "Constantius II",  # NOTE: verify this is correct
    "Constantius II":                "Constantius II",
    "Valens":                        "Valens",
    "Gratian":                       "Gratian",
    "Anastasios I":                  "Anastasius I (emperor)",
    "Justinian I the Great":         "Justinian I",
    "Phokas (Usurper)":              "Phocas",
    "Heraklonas":                    "Heraklonas",
    "Leontios (Usurper)":            "Leontios (emperor)",
    "Artabasdos (Usurper)":         "Artabasdos",
    "Michael II the Amorian":        "Michael II",
    "Zoe (with Theodora)":           "Zoe (empress)",
    "John II Komnenos":              "John II Comnenus",
    "Manuel I Komnenos":             "Manuel I Komnenos",
    "John V Palaiologos":            "John V Palaiologos",  # will use direct URL below
}

# Direct Wikimedia image URLs for specific cases where we want a specific image
DIRECT_URLS = {
    "Justinian I the Great": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg/400px-Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg",
    "Zoe (with Theodora)":   "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Zoe_mosaic_Hagia_Sophia.jpg/400px-Zoe_mosaic_Hagia_Sophia.jpg",
    "John II Komnenos":      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/John_II_Comnenus_mosaic_Hagia_Sophia.jpg/400px-John_II_Comnenus_mosaic_Hagia_Sophia.jpg",
    "John V Palaiologos":    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg/400px-Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg",
    "Anastasios I":          "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Flavius_Anastasius_Probus_01c_%28Anastasius_I%29_%28cropped%29.JPG/400px-Flavius_Anastasius_Probus_01c_%28Anastasius_I%29_%28cropped%29.JPG",
    "Heraklonas":            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Heraclonas_on_Solidus.jpg/400px-Heraclonas_on_Solidus.jpg",
    "Leontios (Usurper)":    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Solidus_of_Leontius.png/400px-Solidus_of_Leontius.png",
}

def get_wiki_image_by_title(page_title, session):
    """Fetch thumbnail image URL from Wikipedia using an exact page title."""
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action":      "query",
        "titles":      page_title,
        "prop":        "pageimages",
        "pithumbsize": 400,
        "format":      "json"
    }
    try:
        resp = session.get(url, params=params, timeout=10)
        data = resp.json()
        pages = data.get("query", {}).get("pages", {})
        for page in pages.values():
            return page.get("thumbnail", {}).get("source", "NO_IMAGE")
    except Exception as e:
        print(f"    ERROR: {e}")
        return "ERROR"

# ── Load CSV ──────────────────────────────────────────────────────────────────
df = pd.read_csv('byzantine_emperors_with_images.csv')

session = requests.Session()
session.headers.update({
    'User-Agent': 'ByzantineEmperorsTool/1.0 (educational project; your@email.com)'
})

print("Fixing problem image URLs...\n")
fixed = 0

for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    
    if name not in OVERRIDES and name not in DIRECT_URLS:
        continue  # skip entries that don't need fixing
    
    print(f"Fixing: {name}")
    
    if name in DIRECT_URLS:
        df.at[idx, 'Image_URL'] = DIRECT_URLS[name]
        print(f"  → Direct URL applied")
        fixed += 1
    else:
        page_title = OVERRIDES[name]
        img_url = get_wiki_image_by_title(page_title, session)
        df.at[idx, 'Image_URL'] = img_url
        print(f"  → {img_url[:80]}...")
        fixed += 1
        time.sleep(1.0)

# ── Save updated CSV ──────────────────────────────────────────────────────────
df.to_csv('byzantine_emperors_with_images.csv', index=False)
print(f"\nDone! Fixed {fixed} entries. CSV updated.")

In [ ]:
import pandas as pd
import requests
import time

# ── Correct Wikipedia page titles for problem entries ─────────────────────────
# Key = Simple_Name_With_Epithets from your CSV
# Value = exact Wikipedia page title to use instead of searching
OVERRIDES = {
    "Constantine I the Great":       "Constantine the Great",
    "Constantinus II":               "Constantius II",  # NOTE: verify this is correct
    "Constantius II":                "Constantius II",
    "Valens":                        "Valens",
    "Gratian":                       "Gratian",
    "Anastasios I":                  "Anastasius I (emperor)",
    "Justinian I the Great":         "Justinian I",
    "Phokas (Usurper)":              "Phocas",
    "Heraklonas":                    "Heraklonas",
    "Leontios (Usurper)":            "Leontios (emperor)",
    "Artabasdos (Usurper)":         "Artabasdos",
    "Michael II the Amorian":        "Michael II",
    "Zoe (with Theodora)":           "Zoe (empress)",
    "John II Komnenos":              "John II Comnenus",
    "Manuel I Komnenos":             "Manuel I Komnenos",
    "John V Palaiologos":            "John V Palaiologos",  # will use direct URL below
}

# Direct Wikimedia image URLs for specific cases where we want a specific image
DIRECT_URLS = {
    "Justinian I the Great": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg/400px-Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg",
    "Zoe (with Theodora)":   "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Zoe_mosaic_Hagia_Sophia.jpg/400px-Zoe_mosaic_Hagia_Sophia.jpg",
    "John II Komnenos":      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/John_II_Comnenus_mosaic_Hagia_Sophia.jpg/400px-John_II_Comnenus_mosaic_Hagia_Sophia.jpg",
    "John V Palaiologos":    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg/400px-Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg",
    "Anastasios I":          "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Flavius_Anastasius_Probus_01c_%28Anastasius_I%29_%28cropped%29.JPG/400px-Flavius_Anastasius_Probus_01c_%28Anastasius_I%29_%28cropped%29.JPG",
    "Heraklonas":            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Heraclonas_on_Solidus.jpg/400px-Heraclonas_on_Solidus.jpg",
    "Leontios (Usurper)":    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Solidus_of_Leontius.png/400px-Solidus_of_Leontius.png",
}

def get_wiki_image_by_title(page_title, session):
    """Fetch thumbnail image URL from Wikipedia using an exact page title."""
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action":      "query",
        "titles":      page_title,
        "prop":        "pageimages",
        "pithumbsize": 400,
        "format":      "json"
    }
    try:
        resp = session.get(url, params=params, timeout=10)
        data = resp.json()
        pages = data.get("query", {}).get("pages", {})
        for page in pages.values():
            return page.get("thumbnail", {}).get("source", "NO_IMAGE")
    except Exception as e:
        print(f"    ERROR: {e}")
        return "ERROR"

# ── Load CSV ──────────────────────────────────────────────────────────────────
df = pd.read_csv('byzantine_emperors_with_images.csv')

session = requests.Session()
session.headers.update({
    'User-Agent': 'ByzantineEmperorsTool/1.0 (educational project; your@email.com)'
})

print("Fixing problem image URLs...\n")
fixed = 0

for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    
    if name not in OVERRIDES and name not in DIRECT_URLS:
        continue  # skip entries that don't need fixing
    
    print(f"Fixing: {name}")
    
    if name in DIRECT_URLS:
        df.at[idx, 'Image_URL'] = DIRECT_URLS[name]
        print(f"  → Direct URL applied")
        fixed += 1
    else:
        page_title = OVERRIDES[name]
        img_url = get_wiki_image_by_title(page_title, session)
        df.at[idx, 'Image_URL'] = img_url
        print(f"  → {img_url[:80]}...")
        fixed += 1
        time.sleep(1.0)

# ── Save updated CSV ──────────────────────────────────────────────────────────
df.to_csv('byzantine_emperors_with_images.csv', index=False)
print(f"\nDone! Fixed {fixed} entries. CSV updated.")

In [19]:
import pandas as pd

# Load the CSV with image URLs
df = pd.read_csv('ERE_List_20260226.csv')

# Build HTML
rows_html = ""
for _, row in df.iterrows():
    img_url = row['Image_URL']
    num = row['List_Number']
    name = row['Simple_Name_With_Epithets']
    dynasty = row['Broad_Dynasty']
    reign = f"{row['Reign_Start']} – {row['Reign_End']}"

    if img_url in ("NOT_FOUND", "NO_IMAGE", "ERROR", "PLACEHOLDER"):
        img_tag = "<div style='width:120px;height:150px;background:#333;display:flex;align-items:center;justify-content:center;color:#888;font-size:12px;'>No Image</div>"
    else:
        img_tag = f"<img src='{img_url}' style='width:120px;height:150px;object-fit:cover;border-radius:4px;' onerror=\"this.style.display='none'\">"

    rows_html += f"""
    <div style='display:flex;align-items:center;gap:16px;padding:12px;border-bottom:1px solid #2a2a2a;'>
        <div style='color:#666;width:30px;text-align:right;font-size:13px;'>{num}</div>
        {img_tag}
        <div>
            <div style='color:#e8e8e8;font-size:15px;font-weight:600;'>{name}</div>
            <div style='color:#888;font-size:13px;margin-top:4px;'>{dynasty} &nbsp;|&nbsp; {reign}</div>
            <div style='margin-top:8px;'>
                <a href='{img_url}' target='_blank' style='color:#5b9bd5;font-size:12px;'>View image URL</a>
            </div>
        </div>
    </div>
    """

html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title>Byzantine Emperors – Image Check</title>
    <style>
        body {{ background:#1a1a1a; color:#e8e8e8; font-family:sans-serif; max-width:800px; margin:40px auto; padding:0 20px; }}
        h1 {{ color:#c8a96e; border-bottom:1px solid #333; padding-bottom:12px; }}
        p  {{ color:#888; font-size:13px; }}
    </style>
</head>
<body>
    <h1>Byzantine Emperors – Image Verification</h1>
    <p>Scroll through and check each image is the correct emperor. Click "View image URL" to open the source.</p>
    {rows_html}
</body>
</html>"""

output_path = 'byzantine_image_check.html'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(html)

print(f"Done! Open this file in your browser: {output_path}")

Done! Open this file in your browser: byzantine_image_check.html

In [ ]:
import pandas as pd

df_main = pd.read_csv('ERE_List_20260226.csv')
df_images = pd.read_csv('byzantine_emperors_with_images.csv')

df_main['Image_URL'] = df_images['Image_URL']

df_main.to_csv('ERE_List_20260226.csv', index=False)
print("Done! Image URLs merged into ERE_List_20260226.csv")

In [33]:
import pandas as pd

# Load the CSV with image URLs
df = pd.read_csv('ERE_List_20260226.csv')

# Build HTML
rows_html = ""
for _, row in df.iterrows():
    img_url = row['Image_URL']
    num = row['List_Number']
    name = row['Simple_Name_With_Epithets']
    dynasty = row['Broad_Dynasty']
    reign = f"{row['Reign_Start']} – {row['Reign_End']}"

    if img_url in ("NOT_FOUND", "NO_IMAGE", "ERROR", "PLACEHOLDER"):
        img_tag = "<div style='width:120px;height:150px;background:#333;display:flex;align-items:center;justify-content:center;color:#888;font-size:12px;'>No Image</div>"
    else:
        img_tag = f"<img src='{img_url}' style='width:120px;height:150px;object-fit:cover;border-radius:4px;' onerror=\"this.style.display='none'\">"

    rows_html += f"""
    <div style='display:flex;align-items:center;gap:16px;padding:12px;border-bottom:1px solid #2a2a2a;'>
        <div style='color:#666;width:30px;text-align:right;font-size:13px;'>{num}</div>
        {img_tag}
        <div>
            <div style='color:#e8e8e8;font-size:15px;font-weight:600;'>{name}</div>
            <div style='color:#888;font-size:13px;margin-top:4px;'>{dynasty} &nbsp;|&nbsp; {reign}</div>
            <div style='margin-top:8px;'>
                <a href='{img_url}' target='_blank' style='color:#5b9bd5;font-size:12px;'>View image URL</a>
            </div>
        </div>
    </div>
    """

html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title>Byzantine Emperors – Image Check</title>
    <style>
        body {{ background:#1a1a1a; color:#e8e8e8; font-family:sans-serif; max-width:800px; margin:40px auto; padding:0 20px; }}
        h1 {{ color:#c8a96e; border-bottom:1px solid #333; padding-bottom:12px; }}
        p  {{ color:#888; font-size:13px; }}
    </style>
</head>
<body>
    <h1>Byzantine Emperors – Image Verification</h1>
    <p>Scroll through and check each image is the correct emperor. Click "View image URL" to open the source.</p>
    {rows_html}
</body>
</html>"""

output_path = 'byzantine_image_check.html'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(html)

print(f"Done! Open this file in your browser: {output_path}")

Done! Open this file in your browser: byzantine_image_check.html

Done! All fixes applied.

In [9]:
import pandas as pd
import requests
import time

# ── Correct Wikipedia page titles for problem entries ─────────────────────────
# Key = Simple_Name_With_Epithets from your CSV
# Value = exact Wikipedia page title to use instead of searching
OVERRIDES = {
    "Constantine I the Great":       "Constantine the Great",
    "Constantinus II":               "Constantius II",  # NOTE: verify this is correct
    "Constantius II":                "Constantius II",
    "Valens":                        "Valens",
    "Gratian":                       "Gratian",
    "Anastasios I":                  "Anastasius I (emperor)",
    "Justinian I the Great":         "Justinian I",
    "Phokas (Usurper)":              "Phocas",
    "Heraklonas":                    "Heraklonas",
    "Leontios (Usurper)":            "Leontios (emperor)",
    "Artabasdos (Usurper)":         "Artabasdos",
    "Michael II the Amorian":        "Michael II",
    "Zoe (with Theodora)":           "Zoe (empress)",
    "John II Komnenos":              "John II Comnenus",
    "Manuel I Komnenos":             "Manuel I Komnenos",
    "John V Palaiologos":            "John V Palaiologos",  # will use direct URL below
}

# Direct Wikimedia image URLs for specific cases where we want a specific image
DIRECT_URLS = {
    "Justinian I the Great": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg/400px-Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg",
    "Zoe (with Theodora)":   "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Zoe_mosaic_Hagia_Sophia.jpg/400px-Zoe_mosaic_Hagia_Sophia.jpg",
    "John II Komnenos":      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/John_II_Comnenus_mosaic_Hagia_Sophia.jpg/400px-John_II_Comnenus_mosaic_Hagia_Sophia.jpg",
    "John V Palaiologos":    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg/400px-Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg",
    "Anastasios I":          "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Flavius_Anastasius_Probus_01c_%28Anastasius_I%29_%28cropped%29.JPG/400px-Flavius_Anastasius_Probus_01c_%28Anastasius_I%29_%28cropped%29.JPG",
    "Heraklonas":            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Solidus_Heraclius_sb_767_%28obverse%29.png/400px-Solidus_Heraclius_sb_767_%28obverse%29.png",
    "Leontios (Usurper)":    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Solidus_of_Leontius.png/400px-Solidus_of_Leontius.png",
}

def get_wiki_image_by_title(page_title, session):
    """Fetch thumbnail image URL from Wikipedia using an exact page title."""
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action":      "query",
        "titles":      page_title,
        "prop":        "pageimages",
        "pithumbsize": 400,
        "format":      "json"
    }
    try:
        resp = session.get(url, params=params, timeout=10)
        data = resp.json()
        pages = data.get("query", {}).get("pages", {})
        for page in pages.values():
            return page.get("thumbnail", {}).get("source", "NO_IMAGE")
    except Exception as e:
        print(f"    ERROR: {e}")
        return "ERROR"

# ── Load and merge CSVs ───────────────────────────────────────────────────────
df = pd.read_csv('ERE_List_20260226.csv')
df_images = pd.read_csv('byzantine_emperors_with_images.csv')
df['Image_URL'] = df_images['Image_URL']

session = requests.Session()
session.headers.update({
    'User-Agent': 'ByzantineEmperorsTool/1.0 (educational project; your@email.com)'
})

print("Fixing problem image URLs...\n")
fixed = 0

for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    
    if name not in OVERRIDES and name not in DIRECT_URLS:
        continue  # skip entries that don't need fixing
    
    print(f"Fixing: {name}")
    
    if name in DIRECT_URLS:
        df.at[idx, 'Image_URL'] = DIRECT_URLS[name]
        print(f"  → Direct URL applied")
        fixed += 1
    else:
        page_title = OVERRIDES[name]
        img_url = get_wiki_image_by_title(page_title, session)
        df.at[idx, 'Image_URL'] = img_url
        print(f"  → {img_url[:80]}...")
        fixed += 1
        time.sleep(1.0)

# ── Save updated CSV ──────────────────────────────────────────────────────────
df.to_csv('ERE_List_20260226.csv', index=False)
print(f"\nDone! Fixed {fixed} entries. CSV updated.")

Fixing problem image URLs...

Fixing: Constantine I the Great
  → https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Statua_di_Costantino_a...
Fixing: Constantinus II
  → https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bust_of_Constantius_II...
Fixing: Constantius II
  → https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bust_of_Constantius_II...
Fixing: Valens
  → https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/INC-3015-a_%D0%A1%D0%B...
Fixing: Gratian
  → https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Gratian_Trier_enhanced...
Fixing: Anastasios I
  → Direct URL applied
Fixing: Justinian I the Great
  → Direct URL applied
Fixing: Phokas (Usurper)
  → https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Phocas%2C_British_Muse...
Fixing: Heraklonas
  → Direct URL applied
Fixing: Leontios (Usurper)
  → Direct URL applied
Fixing: Artabasdos (Usurper)
  → https://upload.wikimedia.org/wikipedia/commons/f/f6/Solidus_of_Artabasdos.png...
Fixing: Michael II the Amorian
  → https://upload.wikimedia.org/wikipedia/commons/d/dc/Michael_II_in_the_Madrid_Sky...
Fixing: Zoe (with Theodora)
  → Direct URL applied
Fixing: John II Komnenos
  → Direct URL applied
Fixing: Manuel I Komnenos
  → https://upload.wikimedia.org/wikipedia/commons/a/af/Manuel_I_Comnenus.jpg...
Fixing: John V Palaiologos
  → Direct URL applied

Done! Fixed 16 entries. CSV updated.

In [11]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
problem = ['Justinian I the Great', 'Zoe (with Theodora)', 'John II Komnenos', 'John V Palaiologos', 'Heraklonas', 'Leontios (Usurper)']
for name in problem:
    row = df[df['Simple_Name_With_Epithets'] == name]
    if len(row) > 0:
        print(f"{name}:")
        print(f"  {row['Image_URL'].values[0]}")
        print()

Justinian I the Great:
  https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg/400px-Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg

Zoe (with Theodora):
  https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Zoe_mosaic_Hagia_Sophia.jpg/400px-Zoe_mosaic_Hagia_Sophia.jpg

John II Komnenos:
  https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/John_II_Comnenus_mosaic_Hagia_Sophia.jpg/400px-John_II_Comnenus_mosaic_Hagia_Sophia.jpg

John V Palaiologos:
  https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg/400px-Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg

Heraklonas:
  https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Solidus_Heraclius_sb_767_%28obverse%29.png/400px-Solidus_Heraclius_sb_767_%28obverse%29.png

Leontios (Usurper):
  https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Solidus_of_Leontius.png/400px-Solidus_of_Leontius.png

In [12]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')

DIRECT_URLS = {
    "Justinian I the Great": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg",
    "Zoe (with Theodora)":   "https://upload.wikimedia.org/wikipedia/commons/e/e9/Zoe_mosaic_Hagia_Sophia.jpg",
    "John II Komnenos":      "https://upload.wikimedia.org/wikipedia/commons/5/5d/John_II_Comnenus_mosaic_Hagia_Sophia.jpg",
    "John V Palaiologos":    "https://upload.wikimedia.org/wikipedia/commons/2/2a/Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg",
    "Heraklonas":            "https://upload.wikimedia.org/wikipedia/commons/5/5e/Solidus_Heraclius_sb_767_%28obverse%29.png",
    "Leontios (Usurper)":    "https://upload.wikimedia.org/wikipedia/commons/8/8e/Solidus_of_Leontius.png",
}

for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    if name in DIRECT_URLS:
        df.at[idx, 'Image_URL'] = DIRECT_URLS[name]

df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [14]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
problem = ['Zoe (with Theodora)', 'John II Komnenos', 'John V Palaiologos', 'Heraklonas', 'Leontios (Usurper)']
for name in problem:
    row = df[df['Simple_Name_With_Epithets'] == name]
    if len(row) > 0:
        print(f"{name}:")
        print(f"  {row['Image_URL'].values[0]}")
        print()

Zoe (with Theodora):
  https://upload.wikimedia.org/wikipedia/commons/e/e9/Zoe_mosaic_Hagia_Sophia.jpg

John II Komnenos:
  https://upload.wikimedia.org/wikipedia/commons/5/5d/John_II_Comnenus_mosaic_Hagia_Sophia.jpg

John V Palaiologos:
  https://upload.wikimedia.org/wikipedia/commons/2/2a/Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg

Heraklonas:
  https://upload.wikimedia.org/wikipedia/commons/5/5e/Solidus_Heraclius_sb_767_%28obverse%29.png

Leontios (Usurper):
  https://upload.wikimedia.org/wikipedia/commons/8/8e/Solidus_of_Leontius.png

In [15]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
problem = ['Zoe (with Theodora)', 'John II Komnenos', 'John V Palaiologos', 'Heraklonas', 'Leontios (Usurper)']
for name in problem:
    row = df[df['Simple_Name_With_Epithets'] == name]
    if len(row) > 0:
        print(f"{name}:")
        print(f"  {row['Image_URL'].values[0]}")
        print()

Zoe (with Theodora):
  https://upload.wikimedia.org/wikipedia/commons/e/e9/Zoe_mosaic_Hagia_Sophia.jpg

John II Komnenos:
  https://upload.wikimedia.org/wikipedia/commons/5/5d/John_II_Comnenus_mosaic_Hagia_Sophia.jpg

John V Palaiologos:
  https://upload.wikimedia.org/wikipedia/commons/2/2a/Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg

Heraklonas:
  https://upload.wikimedia.org/wikipedia/commons/5/5e/Solidus_Heraclius_sb_767_%28obverse%29.png

Leontios (Usurper):
  https://upload.wikimedia.org/wikipedia/commons/8/8e/Solidus_of_Leontius.png

In [16]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')

DIRECT_URLS = {
    "Justinian I the Great": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_%28Ravenna%29.jpg",
    "Zoe (with Theodora)":   "https://upload.wikimedia.org/wikipedia/commons/3/3f/Zoe_mosaic_Hagia_Sophia.jpg",
    "John II Komnenos":      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Jean_II_Comnene.jpg/400px-Jean_II_Comnene.jpg",
    "John V Palaiologos":    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg/400px-Restored_mosaic_of_John_V_Palaiologos_%28head%29.jpg",
    "Heraklonas":            "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Solidus_Heraclius_sb_767_%28obverse%29.png/400px-Solidus_Heraclius_sb_767_%28obverse%29.png",
    "Leontios (Usurper)":    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Solidus_of_Leontius.png/400px-Solidus_of_Leontius.png",
}

for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    if name in DIRECT_URLS:
        df.at[idx, 'Image_URL'] = DIRECT_URLS[name]

df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [18]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')
df.loc[df['Simple_Name_With_Epithets'] == 'Leontios (Usurper)', 'Image_URL'] = 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Solidus_of_Leontius.png'
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [20]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')
df.loc[df['Simple_Name_With_Epithets'] == 'Anastasios I', 'Image_URL'] = 'https://upload.wikimedia.org/wikipedia/commons/9/92/Flavius_Anastasius_Probus_01c_%28Anastasius_I%29_%28cropped%29.JPG'
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [22]:
df

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL
0,1,Constantine I,Constantine I the Great,Flavius Valerius Constantinus,Constantinian,Constantinus,306,337,31,Sole emperor from 324. Moved the imperial capi...,Co-ruled with Licinius 313-324; sons Constanti...,https://upload.wikimedia.org/wikipedia/commons...
1,2,Constantinus II,Constantinus II,Flavius Claudius Constantinus,Constantinian,Constantinus,337,340,3,Son of Constantine I. Ruled the western provin...,Co-emperor with brothers Constans I and Consta...,https://upload.wikimedia.org/wikipedia/commons...
2,3,Constans I,Constans I,Flavius Julius Constans,Constantinian,Constantinus,337,350,13,Son of Constantine I. Ruled the Balkans and la...,Co-emperor with brothers Constantinus II and C...,https://upload.wikimedia.org/wikipedia/commons...
3,4,Constantius II,Constantius II,Flavius Julius Constantius,Constantinian,Constantinus,337,361,24,Son of Constantine I. Sole emperor from 350. F...,Co-emperor with brothers 337-350; appointed Ju...,https://upload.wikimedia.org/wikipedia/commons...
4,5,Magnentius,Magnentius (Usurper),Flavius Magnus Magnentius,NaN,Magnentius,350,353,3,Western usurper of barbarian origin. Defeated ...,Usurper in the west; never recognized by Const...,https://upload.wikimedia.org/wikipedia/commons...
...,...,...,...,...,...,...,...,...,...,...,...,...
93,94,Andronikos IV,Andronikos IV Palaiologos,Andronicus Palaeologus,Palaiologan,Palaiologos,1376,1379,3,Son of John V who rebelled against his father ...,Usurper against his father John V; later recog...,https://upload.wikimedia.org/wikipedia/commons...
94,95,John VII,John VII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1390,1390,1,Grandson of John V who briefly seized Constant...,Brief usurper; later legitimate co-emperor and...,https://upload.wikimedia.org/wikipedia/commons...
95,96,Manuel II,Manuel II Palaiologos,Manuel Palaeologus,Palaiologan,Palaiologos,1391,1425,34,Cultivated and able emperor facing an impossib...,Co-emperor under John V from 1373; made his so...,https://upload.wikimedia.org/wikipedia/commons...
96,97,John VIII,John VIII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1425,1448,23,Son of Manuel II. Attended the Council of Flor...,Co-emperor under Manuel II from 1421; made his...,https://upload.wikimedia.org/wikipedia/commons...
97,98,Constantine XI,Constantine XI Palaiologos Dragases,Constantine Palaeologus Dragases,Palaiologan,Palaiologos,1449,1453,4,Last Byzantine emperor. Defended Constantinopl...,Sole emperor at the end; no co-emperor,https://upload.wikimedia.org/wikipedia/commons...

In [23]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
print(df[['List_Number', 'Simple_Name', 'Simple_Name_With_Epithets']].head(6))

   List_Number      Simple_Name Simple_Name_With_Epithets
0            1    Constantine I   Constantine I the Great
1            2  Constantinus II           Constantinus II
2            3       Constans I                Constans I
3            4   Constantius II            Constantius II
4            5       Magnentius      Magnentius (Usurper)
5            6           Julian       Julian the Apostate

In [24]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
print(df[df['Simple_Name_With_Epithets'] == 'Constantius II']['Image_URL'].values[0])

https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bust_of_Constantius_II_%28Mary_Harrsch%29.jpg/500px-Bust_of_Constantius_II_%28Mary_Harrsch%29.jpg

In [25]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
print(df[df['Simple_Name_With_Epithets'] == 'Constantius II']['Image_URL'].values[0])

https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bust_of_Constantius_II_%28Mary_Harrsch%29.jpg/500px-Bust_of_Constantius_II_%28Mary_Harrsch%29.jpg

In [27]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')

# Remove western-only emperors
cut = [
    'Constantinus II',
    'Constans I',
    'Magnentius (Usurper)',
    'Valentinian I',
    'Gratian',
    'Magnus Maximus (Usurper)',
    'Valentinian II',
]

df = df[~df['Simple_Name_With_Epithets'].isin(cut)].copy()

# Renumber from 1
df['List_Number'] = range(1, len(df) + 1)

df.to_csv('ERE_List_20260226.csv', index=False)
print(f"Done! {len(df)} emperors remaining.")

Done! 91 emperors remaining.

In [28]:
df

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL
0,1,Constantine I,Constantine I the Great,Flavius Valerius Constantinus,Constantinian,Constantinus,306,337,31,Sole emperor from 324. Moved the imperial capi...,Co-ruled with Licinius 313-324; sons Constanti...,https://upload.wikimedia.org/wikipedia/commons...
3,2,Constantius II,Constantius II,Flavius Julius Constantius,Constantinian,Constantinus,337,361,24,Son of Constantine I. Sole emperor from 350. F...,Co-emperor with brothers 337-350; appointed Ju...,https://upload.wikimedia.org/wikipedia/commons...
5,3,Julian,Julian the Apostate,Flavius Claudius Julianus,Constantinian,Constantinus,361,363,2,Last non-Christian emperor. Attempted to resto...,Caesar under Constantius II from 355; proclaim...,https://upload.wikimedia.org/wikipedia/commons...
6,4,Jovian,Jovian,Flavius Jovianus,NaN,Non-dynastic,363,364,1,Elected by the army after Julian's death. Made...,Sole emperor; no co-rulers,https://upload.wikimedia.org/wikipedia/commons...
8,5,Valens,Valens,Flavius Valens,Valentinianic,Valentinianus,364,378,14,"Eastern emperor, brother of Valentinian I. All...",Co-emperor in the east under arrangement with ...,https://upload.wikimedia.org/wikipedia/commons...
...,...,...,...,...,...,...,...,...,...,...,...,...
93,87,Andronikos IV,Andronikos IV Palaiologos,Andronicus Palaeologus,Palaiologan,Palaiologos,1376,1379,3,Son of John V who rebelled against his father ...,Usurper against his father John V; later recog...,https://upload.wikimedia.org/wikipedia/commons...
94,88,John VII,John VII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1390,1390,1,Grandson of John V who briefly seized Constant...,Brief usurper; later legitimate co-emperor and...,https://upload.wikimedia.org/wikipedia/commons...
95,89,Manuel II,Manuel II Palaiologos,Manuel Palaeologus,Palaiologan,Palaiologos,1391,1425,34,Cultivated and able emperor facing an impossib...,Co-emperor under John V from 1373; made his so...,https://upload.wikimedia.org/wikipedia/commons...
96,90,John VIII,John VIII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1425,1448,23,Son of Manuel II. Attended the Council of Flor...,Co-emperor under Manuel II from 1421; made his...,https://upload.wikimedia.org/wikipedia/commons...
97,91,Constantine XI,Constantine XI Palaiologos Dragases,Constantine Palaeologus Dragases,Palaiologan,Palaiologos,1449,1453,4,Last Byzantine emperor. Defended Constantinopl...,Sole emperor at the end; no co-emperor,https://upload.wikimedia.org/wikipedia/commons...

In [30]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')

# Epithet fixes: English → Greek where appropriate
EPITHET_FIXES = {
    'Constantine VII the Purple-Born':  'Constantine VII Porphyrogennetos',
    'Michael V the Caulker':            'Michael V Kalaphates',
    'Constantine V the Dung-Named':     'Constantine V Kopronymos',
    'Alexios V Bushy-Eyebrows':         'Alexios V Mourtzouphlos',
}

df['Simple_Name_With_Epithets'] = df['Simple_Name_With_Epithets'].replace(EPITHET_FIXES)

df.to_csv('ERE_List_20260226.csv', index=False)
print("Done! Epithets updated.")
print("\nUpdated entries:")
for old, new in EPITHET_FIXES.items():
    print(f"  {old} → {new}")

Done! Epithets updated.

Updated entries:
  Constantine VII the Purple-Born → Constantine VII Porphyrogennetos
  Michael V the Caulker → Michael V Kalaphates
  Constantine V the Dung-Named → Constantine V Kopronymos
  Alexios V Bushy-Eyebrows → Alexios V Mourtzouphlos

In [31]:
df

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL
0,1,Constantine I,Constantine I the Great,Flavius Valerius Constantinus,Constantinian,Constantinus,306,337,31,Sole emperor from 324. Moved the imperial capi...,Co-ruled with Licinius 313-324; sons Constanti...,https://upload.wikimedia.org/wikipedia/commons...
1,2,Constantius II,Constantius II,Flavius Julius Constantius,Constantinian,Constantinus,337,361,24,Son of Constantine I. Sole emperor from 350. F...,Co-emperor with brothers 337-350; appointed Ju...,https://upload.wikimedia.org/wikipedia/commons...
2,3,Julian,Julian the Apostate,Flavius Claudius Julianus,Constantinian,Constantinus,361,363,2,Last non-Christian emperor. Attempted to resto...,Caesar under Constantius II from 355; proclaim...,https://upload.wikimedia.org/wikipedia/commons...
3,4,Jovian,Jovian,Flavius Jovianus,NaN,Non-dynastic,363,364,1,Elected by the army after Julian's death. Made...,Sole emperor; no co-rulers,https://upload.wikimedia.org/wikipedia/commons...
4,5,Valens,Valens,Flavius Valens,Valentinianic,Valentinianus,364,378,14,"Eastern emperor, brother of Valentinian I. All...",Co-emperor in the east under arrangement with ...,https://upload.wikimedia.org/wikipedia/commons...
...,...,...,...,...,...,...,...,...,...,...,...,...
86,87,Andronikos IV,Andronikos IV Palaiologos,Andronicus Palaeologus,Palaiologan,Palaiologos,1376,1379,3,Son of John V who rebelled against his father ...,Usurper against his father John V; later recog...,https://upload.wikimedia.org/wikipedia/commons...
87,88,John VII,John VII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1390,1390,1,Grandson of John V who briefly seized Constant...,Brief usurper; later legitimate co-emperor and...,https://upload.wikimedia.org/wikipedia/commons...
88,89,Manuel II,Manuel II Palaiologos,Manuel Palaeologus,Palaiologan,Palaiologos,1391,1425,34,Cultivated and able emperor facing an impossib...,Co-emperor under John V from 1373; made his so...,https://upload.wikimedia.org/wikipedia/commons...
89,90,John VIII,John VIII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1425,1448,23,Son of Manuel II. Attended the Council of Flor...,Co-emperor under Manuel II from 1421; made his...,https://upload.wikimedia.org/wikipedia/commons...
90,91,Constantine XI,Constantine XI Palaiologos Dragases,Constantine Palaeologus Dragases,Palaiologan,Palaiologos,1449,1453,4,Last Byzantine emperor. Defended Constantinopl...,Sole emperor at the end; no co-emperor,https://upload.wikimedia.org/wikipedia/commons...

In [34]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
df['Simple_Name_With_Epithets'] = df['Simple_Name_With_Epithets'].replace({'Phokas (Usurper)': 'Phokas'})
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [1]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')

# Ratings: List_Number → (Difficulty, Effectiveness)
# Difficulty: 1-20 (how bad/hard was the situation they faced)
# Effectiveness: 1-20 (how well did they handle it, relative to what was possible)

RATINGS = {
    1:  (5,  18),  # Constantine I - stable inheritance, transformed empire
    2:  (8,  12),  # Constantius II - civil wars with brothers, capable but flawed
    3:  (7,  10),  # Julian - stable inheritance, ambitious but brief
    4:  (8,  6),   # Jovian - catastrophic Persian situation, gave away too much
    5:  (9,  11),  # Valens - manageable challenges until Adrianople, decent admin
    6:  (10, 16),  # Theodosios I - multiple crises, handled them masterfully
    7:  (8,  5),   # Arkadios - dominated by factions, largely passive
    8:  (9,  13),  # Theodosios II - long stable reign, walls and law code
    9:  (7,  12),  # Markianos - moderate challenges, sound administration
    10: (8,  11),  # Leo I - broke Aspar's grip, mostly effective
    11: (6,  8),   # Leo II - child emperor, too brief to rate meaningfully
    12: (10, 11),  # Zeno - chronic instability, survived against the odds
    13: (8,  1),   # Basiliskos - usurper, collapsed in a year
    14: (7,  13),  # Anastasios I - religious tensions, exceptional finances
    15: (6,  10),  # Justin I - moderate challenges, relied on Justinian
    16: (10, 17),  # Justinian I - stable inheritance, ambitious choice not forced necessity
    17: (11, 8),   # Justin II - lost Italy, mental collapse
    18: (10, 12),  # Tiberios II - multiple threats, competent response
    19: (12, 15),  # Maurikios - severe threats, excellent general and administrator
    20: (8,  1),   # Phokas - inherited stable empire, destroyed it
    21: (14, 17),  # Herakleios - near total collapse inherited, heroic recovery
    22: (14, 8),   # Constantine III - died too soon to judge
    23: (14, 3),   # Heraklonas - impossible situation, incompetent response
    24: (13, 13),  # Constans II - Arab onslaught, held empire together
    25: (13, 15),  # Constantine IV - Arab siege, Greek fire, strong response
    26: (12, 10),  # Justinian II - moderate challenges first reign, self-destructive
    27: (8,  3),   # Leontios - lost Carthage through inaction
    28: (8,  7),   # Tiberios III - brief, unremarkable
    29: (10, 4),   # Philippikos - usurper, theological troublemaker
    30: (9,  8),   # Anastasios II - competent but overthrown
    31: (10, 5),   # Theodosios III - accidental emperor, abdicated
    32: (13, 16),  # Leo III - Arab siege, iconoclasm, reorganized empire
    33: (11, 15),  # Constantine V Kopronymos - iconoclast wars, strong military
    34: (8,  4),   # Artabasdos - usurper, quickly defeated
    35: (9,  11),  # Leo IV - short but stable
    36: (10, 7),   # Constantine VI - dominated by mother, weak
    37: (9,  12),  # Eirene - politically adept, restored icons
    38: (9,  12),  # Nikephoros I - financial reforms, died heroically
    39: (10, 5),   # Staurakios - dying from wounds, no real reign
    40: (10, 6),   # Michael I Rhangabe - pious but ineffective
    41: (11, 13),  # Leo V the Armenian - revived iconoclasm, strong military
    42: (10, 11),  # Michael II the Amorian - founded dynasty, survived Thomas revolt
    43: (10, 12),  # Theophilos - multiple threats, cultured capable ruler
    44: (11, 14),  # Michael III - icons restored, Slavs christianized, murdered
    45: (8,  16),  # Basil I - founded Macedonian dynasty, strong legislator
    46: (9,  15),  # Leo VI the Wise - prolific legislator, mixed military
    47: (9,  7),   # Alexander - brief, reckless
    48: (12, 13),  # Constantine VII Porphyrogennetos - dominated but scholarly legacy
    49: (10, 8),   # Romanos I Lekapenos - capable but usurper
    50: (8,  10),  # Romanos II - brief, relied on generals
    51: (10, 16),  # Nikephoros II Phokas - reconquests, unpopular but effective
    52: (10, 16),  # John I Tzimiskes - brilliant campaigns, brief reign
    53: (11, 20),  # Basil II Bulgaroktonos - civil war then total dominance, exceptional
    54: (6,  5),   # Constantine VIII - coasted on brother's work
    55: (8,  6),   # Romanos III Argyros - pretentious, incompetent
    56: (8,  10),  # Michael IV the Paphlagonian - capable generals, epilepsy
    57: (8,  1),   # Michael V Kalaphates - handed everything, threw it away in weeks
    58: (7,  8),   # Zoe - symbolic more than effective
    59: (7,  9),   # Theodora - brief competent sole rule
    60: (8,  7),   # Constantine IX Monomachos - reduced military, Great Schism
    61: (9,  5),   # Michael VI Bringas - couldn't manage aristocracy
    62: (10, 12),  # Isaac I Komnenos - needed reform, achieved some
    63: (11, 8),   # Constantine X Doukas - cut military at worst possible time
    64: (13, 5),   # Romanos IV Diogenes - Mantzikert catastrophe
    65: (13, 6),   # Michael VII Doukas - lost Anatolia, ineffective
    66: (12, 7),   # Nikephoros III Botaneiates - elderly usurper, overwhelmed
    67: (14, 16),  # Alexios I Komnenos - empire near collapse, rebuilt it
    68: (12, 17),  # John II Komnenos - strong inheritance, maximized it
    69: (10, 14),  # Manuel I Komnenos - ambitious, Myriokephalon a setback
    70: (11, 6),   # Alexios II Komnenos - child, murdered
    71: (11, 8),   # Andronikos I Komnenos - chaos inherited, made it worse
    72: (12, 10),  # Isaac II Angelos - founded dynasty under pressure
    73: (12, 5),   # Alexios III Angelos - stable enough, completely passive
    74: (14, 4),   # Isaac II restored - blind, helpless
    75: (14, 4),   # Alexios IV Angelos - invited crusaders, couldn't pay them
    76: (15, 6),   # Alexios V Mourtzouphlos - impossible situation, tried to fight
    77: (14, 14),  # Theodore I Laskaris - built Nikaia from nothing
    78: (12, 17),  # John III Doukas Vatatzes - greatest Nikaian emperor
    79: (11, 12),  # Theodore II Laskaris - capable but suspicious
    80: (13, 5),   # John IV Laskaris - child, blinded by Michael VIII
    81: (13, 15),  # Michael VIII Palaiologos - recovered Constantinople, ruthless
    82: (15, 10),  # Andronikos II Palaiologos - financial ruin, Catalan disaster
    83: (14, 10),  # Michael IX Palaiologos - co-emperor only, never sole ruler
    84: (15, 12),  # Andronikos III Palaiologos - civil war then competent rule
    85: (17, 7),   # John V Palaiologos - impossible situation, survived barely
    86: (10, 4),   # John VI Kantakouzenos - civil war of his own making, invited Ottomans into Europe
    87: (16, 6),   # Andronikos IV Palaiologos - rebel, brief
    88: (16, 5),   # John VII Palaiologos - brief usurper
    89: (16, 14),  # Manuel II Palaiologos - extraordinary dignity under impossible odds
    90: (18, 11),  # John VIII Palaiologos - Florence union, Varna disaster
    91: (20, 18),  # Constantine XI - impossible, died fighting, legendary
}

# Apply ratings
df['Difficulty'] = df['List_Number'].map(lambda x: RATINGS.get(x, (1,1))[0])
df['Effectiveness'] = df['List_Number'].map(lambda x: RATINGS.get(x, (1,1))[1])

df.to_csv('ERE_List_20260226.csv', index=False)
print("Done! Ratings added.")
print(f"\nTop 5 by Effectiveness:")
print(df.nlargest(5, 'Effectiveness')[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']])
print(f"\nTop 5 by Difficulty:")
print(df.nlargest(5, 'Difficulty')[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']])

Done! Ratings added.

Top 5 by Effectiveness:
    List_Number            Simple_Name_With_Epithets  Difficulty  \
52           53           Basil II the Bulgar-Slayer          11
0             1              Constantine I the Great           5
90           91  Constantine XI Palaiologos Dragases          20
15           16                Justinian I the Great          10
20           21                           Herakleios          14

    Effectiveness
52             20
0              18
90             18
15             17
20             17

Top 5 by Difficulty:
    List_Number            Simple_Name_With_Epithets  Difficulty  \
90           91  Constantine XI Palaiologos Dragases          20
89           90                John VIII Palaiologos          18
84           85                   John V Palaiologos          17
86           87            Andronikos IV Palaiologos          16
87           88                 John VII Palaiologos          16

    Effectiveness
90             18
89             11
84              7
86              6
87              5

In [2]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')

# Ratings: List_Number → (Difficulty, Effectiveness)
# Difficulty: 1-20 (how bad/hard was the situation they faced)
# Effectiveness: 1-20 (how well did they handle it, relative to what was possible)

RATINGS = {
    1:  (5,  18),  # Constantine I - stable inheritance, transformed empire
    2:  (8,  12),  # Constantius II - civil wars with brothers, capable but flawed
    3:  (7,  10),  # Julian - stable inheritance, ambitious but brief
    4:  (8,  6),   # Jovian - catastrophic Persian situation, gave away too much
    5:  (9,  11),  # Valens - manageable challenges until Adrianople, decent admin
    6:  (10, 16),  # Theodosios I - multiple crises, handled them masterfully
    7:  (8,  5),   # Arkadios - dominated by factions, largely passive
    8:  (9,  13),  # Theodosios II - long stable reign, walls and law code
    9:  (7,  12),  # Markianos - moderate challenges, sound administration
    10: (8,  11),  # Leo I - broke Aspar's grip, mostly effective
    11: (6,  8),   # Leo II - child emperor, too brief to rate meaningfully
    12: (10, 11),  # Zeno - chronic instability, survived against the odds
    13: (8,  1),   # Basiliskos - usurper, collapsed in a year
    14: (7,  13),  # Anastasios I - religious tensions, exceptional finances
    15: (6,  10),  # Justin I - moderate challenges, relied on Justinian
    16: (10, 17),  # Justinian I - stable inheritance, ambitious choice not forced necessity
    17: (11, 8),   # Justin II - lost Italy, mental collapse
    18: (10, 12),  # Tiberios II - multiple threats, competent response
    19: (12, 15),  # Maurikios - severe threats, excellent general and administrator
    20: (8,  1),   # Phokas - inherited stable empire, destroyed it
    21: (14, 17),  # Herakleios - near total collapse inherited, heroic recovery
    22: (14, 8),   # Constantine III - died too soon to judge
    23: (14, 3),   # Heraklonas - impossible situation, incompetent response
    24: (13, 13),  # Constans II - Arab onslaught, held empire together
    25: (13, 15),  # Constantine IV - Arab siege, Greek fire, strong response
    26: (12, 10),  # Justinian II - moderate challenges first reign, self-destructive
    27: (8,  3),   # Leontios - lost Carthage through inaction
    28: (8,  7),   # Tiberios III - brief, unremarkable
    29: (10, 4),   # Philippikos - usurper, theological troublemaker
    30: (9,  8),   # Anastasios II - competent but overthrown
    31: (10, 5),   # Theodosios III - accidental emperor, abdicated
    32: (13, 16),  # Leo III - Arab siege, iconoclasm, reorganized empire
    33: (11, 15),  # Constantine V Kopronymos - iconoclast wars, strong military
    34: (8,  4),   # Artabasdos - usurper, quickly defeated
    35: (9,  11),  # Leo IV - short but stable
    36: (10, 7),   # Constantine VI - dominated by mother, weak
    37: (9,  12),  # Eirene - politically adept, restored icons
    38: (9,  12),  # Nikephoros I - financial reforms, died heroically
    39: (10, 5),   # Staurakios - dying from wounds, no real reign
    40: (10, 6),   # Michael I Rhangabe - pious but ineffective
    41: (11, 13),  # Leo V the Armenian - revived iconoclasm, strong military
    42: (10, 11),  # Michael II the Amorian - founded dynasty, survived Thomas revolt
    43: (10, 12),  # Theophilos - multiple threats, cultured capable ruler
    44: (11, 14),  # Michael III - icons restored, Slavs christianized, murdered
    45: (8,  16),  # Basil I - founded Macedonian dynasty, strong legislator
    46: (9,  15),  # Leo VI the Wise - prolific legislator, mixed military
    47: (9,  7),   # Alexander - brief, reckless
    48: (12, 13),  # Constantine VII Porphyrogennetos - dominated but scholarly legacy
    49: (10, 8),   # Romanos I Lekapenos - capable but usurper
    50: (8,  10),  # Romanos II - brief, relied on generals
    51: (10, 16),  # Nikephoros II Phokas - reconquests, unpopular but effective
    52: (10, 16),  # John I Tzimiskes - brilliant campaigns, brief reign
    53: (11, 20),  # Basil II Bulgaroktonos - civil war then total dominance, exceptional
    54: (6,  5),   # Constantine VIII - coasted on brother's work
    55: (8,  6),   # Romanos III Argyros - pretentious, incompetent
    56: (8,  10),  # Michael IV the Paphlagonian - capable generals, epilepsy
    57: (8,  1),   # Michael V Kalaphates - handed everything, threw it away in weeks
    58: (7,  8),   # Zoe - symbolic more than effective
    59: (7,  9),   # Theodora - brief competent sole rule
    60: (8,  7),   # Constantine IX Monomachos - reduced military, Great Schism
    61: (9,  5),   # Michael VI Bringas - couldn't manage aristocracy
    62: (10, 12),  # Isaac I Komnenos - needed reform, achieved some
    63: (11, 8),   # Constantine X Doukas - cut military at worst possible time
    64: (13, 5),   # Romanos IV Diogenes - Mantzikert catastrophe
    65: (13, 6),   # Michael VII Doukas - lost Anatolia, ineffective
    66: (12, 7),   # Nikephoros III Botaneiates - elderly usurper, overwhelmed
    67: (14, 16),  # Alexios I Komnenos - empire near collapse, rebuilt it
    68: (12, 17),  # John II Komnenos - strong inheritance, maximized it
    69: (10, 14),  # Manuel I Komnenos - ambitious, Myriokephalon a setback
    70: (11, 6),   # Alexios II Komnenos - child, murdered
    71: (11, 8),   # Andronikos I Komnenos - chaos inherited, made it worse
    72: (12, 10),  # Isaac II Angelos - founded dynasty under pressure
    73: (12, 5),   # Alexios III Angelos - stable enough, completely passive
    74: (14, 4),   # Isaac II restored - blind, helpless
    75: (14, 4),   # Alexios IV Angelos - invited crusaders, couldn't pay them
    76: (15, 6),   # Alexios V Mourtzouphlos - impossible situation, tried to fight
    77: (14, 14),  # Theodore I Laskaris - built Nikaia from nothing
    78: (12, 17),  # John III Doukas Vatatzes - greatest Nikaian emperor
    79: (11, 12),  # Theodore II Laskaris - capable but suspicious
    80: (13, 5),   # John IV Laskaris - child, blinded by Michael VIII
    81: (13, 15),  # Michael VIII Palaiologos - recovered Constantinople, ruthless
    82: (15, 10),  # Andronikos II Palaiologos - financial ruin, Catalan disaster
    83: (14, 10),  # Michael IX Palaiologos - co-emperor only, never sole ruler
    84: (15, 12),  # Andronikos III Palaiologos - civil war then competent rule
    85: (17, 7),   # John V Palaiologos - impossible situation, survived barely
    86: (10, 4),   # John VI Kantakouzenos - civil war of his own making, invited Ottomans into Europe
    87: (16, 6),   # Andronikos IV Palaiologos - rebel, brief
    88: (16, 5),   # John VII Palaiologos - brief usurper
    89: (16, 14),  # Manuel II Palaiologos - extraordinary dignity under impossible odds
    90: (18, 11),  # John VIII Palaiologos - Florence union, Varna disaster
    91: (20, 18),  # Constantine XI - impossible, died fighting, legendary
}

# Apply ratings
df['Difficulty'] = df['List_Number'].map(lambda x: RATINGS.get(x, (1,1))[0])
df['Effectiveness'] = df['List_Number'].map(lambda x: RATINGS.get(x, (1,1))[1])

df.to_csv('ERE_List_20260226.csv', index=False)
print("Done! Ratings added.")
print(f"\nTop 5 by Effectiveness:")
print(df.nlargest(5, 'Effectiveness')[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']])
print(f"\nTop 5 by Difficulty:")
print(df.nlargest(5, 'Difficulty')[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']])

Done! Ratings added.

Top 5 by Effectiveness:
    List_Number            Simple_Name_With_Epithets  Difficulty  \
52           53           Basil II the Bulgar-Slayer          11
0             1              Constantine I the Great           5
90           91  Constantine XI Palaiologos Dragases          20
15           16                Justinian I the Great          10
20           21                           Herakleios          14

    Effectiveness
52             20
0              18
90             18
15             17
20             17

Top 5 by Difficulty:
    List_Number            Simple_Name_With_Epithets  Difficulty  \
90           91  Constantine XI Palaiologos Dragases          20
89           90                John VIII Palaiologos          18
84           85                   John V Palaiologos          17
86           87            Andronikos IV Palaiologos          16
87           88                 John VII Palaiologos          16

    Effectiveness
90             18
89             11
84              7
86              6
87              5

In [3]:
df

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL,Difficulty,Effectiveness
0,1,Constantine I,Constantine I the Great,Flavius Valerius Constantinus,Constantinian,Constantinus,306,337,31,Sole emperor from 324. Moved the imperial capi...,Co-ruled with Licinius 313-324; sons Constanti...,https://upload.wikimedia.org/wikipedia/commons...,5,18
1,2,Constantius II,Constantius II,Flavius Julius Constantius,Constantinian,Constantinus,337,361,24,Son of Constantine I. Sole emperor from 350. F...,Co-emperor with brothers 337-350; appointed Ju...,https://upload.wikimedia.org/wikipedia/commons...,8,12
2,3,Julian,Julian the Apostate,Flavius Claudius Julianus,Constantinian,Constantinus,361,363,2,Last non-Christian emperor. Attempted to resto...,Caesar under Constantius II from 355; proclaim...,https://upload.wikimedia.org/wikipedia/commons...,7,10
3,4,Jovian,Jovian,Flavius Jovianus,NaN,Non-dynastic,363,364,1,Elected by the army after Julian's death. Made...,Sole emperor; no co-rulers,https://upload.wikimedia.org/wikipedia/commons...,8,6
4,5,Valens,Valens,Flavius Valens,Valentinianic,Valentinianus,364,378,14,"Eastern emperor, brother of Valentinian I. All...",Co-emperor in the east under arrangement with ...,https://upload.wikimedia.org/wikipedia/commons...,9,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,87,Andronikos IV,Andronikos IV Palaiologos,Andronicus Palaeologus,Palaiologan,Palaiologos,1376,1379,3,Son of John V who rebelled against his father ...,Usurper against his father John V; later recog...,https://upload.wikimedia.org/wikipedia/commons...,16,6
87,88,John VII,John VII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1390,1390,1,Grandson of John V who briefly seized Constant...,Brief usurper; later legitimate co-emperor and...,https://upload.wikimedia.org/wikipedia/commons...,16,5
88,89,Manuel II,Manuel II Palaiologos,Manuel Palaeologus,Palaiologan,Palaiologos,1391,1425,34,Cultivated and able emperor facing an impossib...,Co-emperor under John V from 1373; made his so...,https://upload.wikimedia.org/wikipedia/commons...,16,14
89,90,John VIII,John VIII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1425,1448,23,Son of Manuel II. Attended the Council of Flor...,Co-emperor under Manuel II from 1421; made his...,https://upload.wikimedia.org/wikipedia/commons...,18,11
90,91,Constantine XI,Constantine XI Palaiologos Dragases,Constantine Palaeologus Dragases,Palaiologan,Palaiologos,1449,1453,4,Last Byzantine emperor. Defended Constantinopl...,Sole emperor at the end; no co-emperor,https://upload.wikimedia.org/wikipedia/commons...,20,18

In [4]:
import pandas as pd
import json

df = pd.read_csv('ERE_List_20260226.csv')

# Build emperor data list for JavaScript
emperors = []
for _, row in df.iterrows():
    emperors.append({
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "image":      str(row['Image_URL']),
        "years":      int(row['Reign_Length_Years']),
    })

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #111;
    color: #e8e8e8;
    font-family: 'Georgia', serif;
    overflow-x: hidden;
  }}
  h1 {{
    text-align: center;
    color: #c8a96e;
    font-size: 1.8em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #888;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-container {{
    position: relative;
    margin: 0 auto;
    width: 900px;
    height: 700px;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(20,20,20,0.97);
    border: 1px solid #c8a96e;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 280px;
    z-index: 100;
  }}
  #tooltip img {{
    width: 80px;
    height: 100px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name {{ color: #c8a96e; font-size: 1em; font-weight: bold; margin-bottom: 4px; }}
  #tooltip .tip-dynasty {{ color: #aaa; font-size: 0.8em; margin-bottom: 4px; }}
  #tooltip .tip-reign {{ color: #888; font-size: 0.78em; margin-bottom: 6px; }}
  #tooltip .tip-scores {{ color: #e8e8e8; font-size: 0.82em; margin-bottom: 6px; }}
  #tooltip .tip-summary {{ color: #bbb; font-size: 0.75em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #333; padding-top: 6px; }}
  .axis-label {{
    position: absolute;
    color: #888;
    font-size: 0.8em;
    letter-spacing: 1px;
    text-transform: uppercase;
  }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 30px;
    padding: 12px;
    flex-wrap: wrap;
  }}
  .legend-item {{
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 0.78em;
    color: #aaa;
  }}
  .legend-dot {{
    width: 12px;
    height: 12px;
    border-radius: 50%;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Hover over an emperor to learn more</p>

<div id="chart-container">
  <canvas id="bg-canvas" width="900" height="700"></canvas>
  <canvas id="img-canvas" width="900" height="700"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#e8c84a"></div>High Difficulty / High Effectiveness</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e87a4a"></div>High Difficulty / Low Effectiveness</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4ae87a"></div>Low Difficulty / High Effectiveness</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a8ae8"></div>Low Difficulty / Low Effectiveness</div>
</div>

<div id="tooltip"></div>

<script>
const EMPERORS = {data_json};

const PAD = {{ left: 70, right: 30, top: 40, bottom: 60 }};
const W = 900, H = 700;
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_SIZE = 20;
const MAX_SIZE = 70;

// Scale functions
function scaleX(d) {{ return PAD.left + ((d - 1) / 19) * plotW; }}
function scaleY(d) {{ return PAD.top + plotH - ((d - 1) / 19) * plotH; }}

// Quadrant color
function quadColor(diff, eff) {{
  const hiD = diff > 10, hiE = eff > 10;
  if (hiD && hiE)  return '#e8c84a';
  if (hiD && !hiE) return '#e87a4a';
  if (!hiD && hiE) return '#4ae87a';
  return '#4a8ae8';
}}

// Draw background grid and quadrant shading
const bgCanvas = document.getElementById('bg-canvas');
const bgCtx = bgCanvas.getContext('2d');

// Quadrant shading
const midX = scaleX(10.5);
const midY = scaleY(10.5);

function shadeQuadrant(x1, y1, x2, y2, color) {{
  bgCtx.fillStyle = color;
  bgCtx.fillRect(x1, y1, x2 - x1, y2 - y1);
}}

shadeQuadrant(PAD.left, PAD.top,   midX,        midY,         'rgba(74,138,232,0.07)');
shadeQuadrant(midX,     PAD.top,   PAD.left+plotW, midY,      'rgba(74,232,122,0.07)');
shadeQuadrant(PAD.left, midY,      midX,        PAD.top+plotH,'rgba(232,122,74,0.07)');
shadeQuadrant(midX,     midY,      PAD.left+plotW, PAD.top+plotH, 'rgba(232,200,74,0.07)');

// Quadrant dividers
bgCtx.strokeStyle = '#333';
bgCtx.lineWidth = 1;
bgCtx.setLineDash([4, 4]);
bgCtx.beginPath();
bgCtx.moveTo(midX, PAD.top);
bgCtx.lineTo(midX, PAD.top + plotH);
bgCtx.stroke();
bgCtx.beginPath();
bgCtx.moveTo(PAD.left, midY);
bgCtx.lineTo(PAD.left + plotW, midY);
bgCtx.stroke();
bgCtx.setLineDash([]);

// Grid lines
bgCtx.strokeStyle = '#222';
bgCtx.lineWidth = 1;
for (let i = 1; i <= 20; i++) {{
  const x = scaleX(i);
  const y = scaleY(i);
  bgCtx.beginPath(); bgCtx.moveTo(x, PAD.top); bgCtx.lineTo(x, PAD.top + plotH); bgCtx.stroke();
  bgCtx.beginPath(); bgCtx.moveTo(PAD.left, y); bgCtx.lineTo(PAD.left + plotW, y); bgCtx.stroke();
}}

// Axes
bgCtx.strokeStyle = '#555';
bgCtx.lineWidth = 2;
bgCtx.beginPath();
bgCtx.moveTo(PAD.left, PAD.top);
bgCtx.lineTo(PAD.left, PAD.top + plotH);
bgCtx.lineTo(PAD.left + plotW, PAD.top + plotH);
bgCtx.stroke();

// Axis tick labels
bgCtx.fillStyle = '#666';
bgCtx.font = '11px Georgia';
bgCtx.textAlign = 'center';
for (let i = 1; i <= 20; i += 2) {{
  bgCtx.fillText(i, scaleX(i), PAD.top + plotH + 18);
}}
bgCtx.textAlign = 'right';
for (let i = 1; i <= 20; i += 2) {{
  bgCtx.fillText(i, PAD.left - 8, scaleY(i) + 4);
}}

// Axis titles
bgCtx.fillStyle = '#888';
bgCtx.font = '13px Georgia';
bgCtx.textAlign = 'center';
bgCtx.fillText('Difficulty of Reign →', PAD.left + plotW / 2, H - 10);
bgCtx.save();
bgCtx.translate(16, PAD.top + plotH / 2);
bgCtx.rotate(-Math.PI / 2);
bgCtx.fillText('← Effectiveness', 0, 0);
bgCtx.restore();

// Quadrant labels
bgCtx.font = 'italic 11px Georgia';
bgCtx.fillStyle = 'rgba(200,200,200,0.25)';
bgCtx.textAlign = 'center';
bgCtx.fillText('Easy Reign, High Achievement', PAD.left + plotW * 0.75, PAD.top + 20);
bgCtx.fillText('Hard Reign, High Achievement', PAD.left + plotW * 0.25, PAD.top + 20);
bgCtx.fillText('Easy Reign, Low Achievement', PAD.left + plotW * 0.75, PAD.top + plotH - 10);
bgCtx.fillText('Hard Reign, Low Achievement', PAD.left + plotW * 0.25, PAD.top + plotH - 10);

const maxYears = Math.max(...EMPERORS.map(e => e.years));
function imgSize(years) {{
  return MIN_SIZE + ((years / maxYears) * (MAX_SIZE - MIN_SIZE));
}}


const imgCanvas = document.getElementById('img-canvas');
const imgCtx = imgCanvas.getContext('2d');
const positions = [];

EMPERORS.forEach((emp, i) => {{
  const cx = scaleX(emp.difficulty);
  const cy = scaleY(emp.effective);
  const half = imgSize(emp.years) / 2;
  positions.push({{ cx, cy, emp, half }});

  const img = new Image();
  img.crossOrigin = 'anonymous';
  img.onload = function() {{
    // Colored circle border
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half + 3, 0, Math.PI * 2);
    imgCtx.fillStyle = quadColor(emp.difficulty, emp.effective);
    imgCtx.fill();
    // Clip and draw image
    imgCtx.save();
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half, 0, Math.PI * 2);
    imgCtx.clip();
    imgCtx.drawImage(img, cx - half, cy - half, half * 2, half * 2);
    imgCtx.restore();
  }};
  img.onerror = function() {{
    // Fallback: colored circle with initial
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half + 3, 0, Math.PI * 2);
    imgCtx.fillStyle = quadColor(emp.difficulty, emp.effective);
    imgCtx.fill();
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half, 0, Math.PI * 2);
    imgCtx.fillStyle = '#333';
    imgCtx.fill();
    imgCtx.fillStyle = '#e8e8e8';
    imgCtx.font = `bold ${{Math.max(10, half * 0.6)}}px Georgia`;
    imgCtx.textAlign = 'center';
    imgCtx.fillText(emp.name.charAt(0), cx, cy + 4);
  }};
  img.src = emp.image;
}});

// Tooltip logic
const tooltip = document.getElementById('tooltip');
imgCanvas.addEventListener('mousemove', function(e) {{
  const rect = imgCanvas.getBoundingClientRect();
  const mx = e.clientX - rect.left;
  const my = e.clientY - rect.top;
  let found = null;
  for (const p of positions) {{
    const dx = mx - p.cx, dy = my - p.cy;
    if (Math.sqrt(dx*dx + dy*dy) < IMG_SIZE / 2 + 4) {{
      found = p;
      break;
    }}
  }}
  if (found) {{
    const emp = found.emp;
    const imgTag = emp.image && emp.image !== 'PLACEHOLDER'
      ? `<img src="${{emp.image}}" onerror="this.style.display='none'">`
      : '';
    tooltip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{emp.name}}</div>
      <div class="tip-dynasty">${{emp.dynasty}}</div>
      <div class="tip-reign">${{emp.start}} – ${{emp.end}}</div>
      <div class="tip-scores">Difficulty: ${{emp.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{emp.effective}}</div>
      <div class="tip-summary">${{emp.summary}}</div>
    `;
    tooltip.style.display = 'block';
    let tx = e.clientX + 15;
    let ty = e.clientY - 10;
    if (tx + 290 > window.innerWidth) tx = e.clientX - 295;
    if (ty + 300 > window.innerHeight) ty = e.clientY - 300;
    tooltip.style.left = tx + 'px';
    tooltip.style.top  = ty + 'px';
    imgCanvas.style.cursor = 'pointer';
  }} else {{
    tooltip.style.display = 'none';
    imgCanvas.style.cursor = 'default';
  }}
}});
imgCanvas.addEventListener('mouseleave', () => {{ tooltip.style.display = 'none'; }});
</script>
</body>
</html>"""

with open('byzantine_scatter.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("Done! Open byzantine_scatter.html in your browser.")

Done! Open byzantine_scatter.html in your browser.

In [5]:
import pandas as pd
import requests
import os
import time
from urllib.parse import urlparse

df = pd.read_csv('ERE_List_20260226.csv')

# Create images folder
os.makedirs('images', exist_ok=True)

session = requests.Session()
session.headers.update({
    'User-Agent': 'ByzantineEmperorsTool/1.0 (educational project; ecocinar@gmail.com)'
})

print("Downloading images...\n")

local_urls = []
failed = 0

for idx, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    img_url = str(row['Image_URL'])
    num = int(row['List_Number'])

    if img_url in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        print(f"  [{num}] {name} — no URL, skipping")
        local_urls.append(img_url)
        continue

    # Get file extension from URL
    parsed = urlparse(img_url)
    ext = os.path.splitext(parsed.path)[-1].lower()
    if ext not in ('.jpg', '.jpeg', '.png', '.gif', '.webp'):
        ext = '.jpg'

    filename = f"images/{num:03d}_{ext}"

    if os.path.exists(filename):
        print(f"  [{num}] {name} — already exists, skipping")
        local_urls.append(filename)
        continue

    try:
        resp = session.get(img_url, timeout=15)
        if resp.status_code == 200:
            with open(filename, 'wb') as f:
                f.write(resp.content)
            print(f"  [{num}] {name} — saved as {filename}")
            local_urls.append(filename)
        else:
            print(f"  [{num}] {name} — HTTP {resp.status_code}, keeping URL")
            local_urls.append(img_url)
            failed += 1
    except Exception as e:
        print(f"  [{num}] {name} — ERROR: {e}")
        local_urls.append(img_url)
        failed += 1

    time.sleep(0.3)

# Save local paths back to CSV
df['Local_Image'] = local_urls
df.to_csv('ERE_List_20260226.csv', index=False)

print(f"\nDone! {len(df) - failed} images downloaded.")
print(f"Failed: {failed}")
print("Local paths saved to 'Local_Image' column in CSV.")

Downloading images...

  [1] Constantine I the Great — saved as images/001_.jpg
  [2] Constantius II — saved as images/002_.jpg
  [3] Julian the Apostate — saved as images/003_.jpg
  [4] Jovian — saved as images/004_.jpg
  [5] Valens — saved as images/005_.png
  [6] Theodosios I the Great — saved as images/006_.jpg
  [7] Arkadios — saved as images/007_.jpg
  [8] Theodosios II — saved as images/008_.jpg
  [9] Markianos — saved as images/009_.png
  [10] Leo I the Thracian — saved as images/010_.jpg
  [11] Leo II — saved as images/011_.png
  [12] Zeno — saved as images/012_.jpg
  [13] Basiliskos (Usurper) — saved as images/013_.jpg
  [14] Anastasios I — saved as images/014_.jpg
  [15] Justin I — saved as images/015_.jpg
  [16] Justinian I the Great — saved as images/016_.jpg
  [17] Justin II — saved as images/017_.jpg
  [18] Tiberios II the Constantine — saved as images/018_.jpg
  [19] Maurikios — saved as images/019_.png
  [20] Phokas — saved as images/020_.jpg
  [21] Herakleios — saved as images/021_.jpg
  [22] Constantine III — saved as images/022_.jpg
  [23] Heraklonas — saved as images/023_.png
  [24] Constans II — saved as images/024_.jpg
  [25] Constantine IV — saved as images/025_.jpg
  [26] Justinian II Slit-Nose — saved as images/026_.png
  [27] Leontios (Usurper) — saved as images/027_.png
  [28] Tiberios III (Usurper) — saved as images/028_.png
  [29] Philippikos (Usurper) — saved as images/029_.png
  [30] Anastasios II — saved as images/030_.jpg
  [31] Theodosios III — saved as images/031_.png
  [32] Leo III the Isaurian — saved as images/032_.png
  [33] Constantine V Kopronymos — saved as images/033_.png
  [34] Artabasdos (Usurper) — saved as images/034_.png
  [35] Leo IV the Khazar — saved as images/035_.jpg
  [36] Constantine VI — saved as images/036_.png
  [37] Eirene — saved as images/037_.jpg
  [38] Nikephoros I — saved as images/038_.png
  [39] Staurakios — saved as images/039_.png
  [40] Michael I Rhangabe — saved as images/040_.jpg
  [41] Leo V the Armenian — saved as images/041_.jpg
  [42] Michael II the Amorian — saved as images/042_.jpg
  [43] Theophilos — saved as images/043_.jpg
  [44] Michael III the Drunkard — saved as images/044_.jpg
  [45] Basil I the Macedonian — saved as images/045_.png
  [46] Leo VI the Wise — saved as images/046_.jpg
  [47] Alexander — saved as images/047_.jpg
  [48] Constantine VII Porphyrogennetos — saved as images/048_.jpeg
  [49] Romanos I Lekapenos — saved as images/049_.png
  [50] Romanos II — saved as images/050_.jpg
  [51] Nikephoros II Phokas — saved as images/051_.jpg
  [52] John I Tzimiskes — saved as images/052_.jpg
  [53] Basil II the Bulgar-Slayer — saved as images/053_.jpg
  [54] Constantine VIII — saved as images/054_.jpg
  [55] Romanos III Argyros — saved as images/055_.png
  [56] Michael IV the Paphlagonian — saved as images/056_.jpg
  [57] Michael V Kalaphates — saved as images/057_.jpg
  [58] Zoe (with Theodora) — saved as images/058_.jpg
  [59] Theodora — saved as images/059_.jpg
  [60] Constantine IX Monomachos — saved as images/060_.jpg
  [61] Michael VI Bringas — saved as images/061_.png
  [62] Isaac I Komnenos — saved as images/062_.jpg
  [63] Constantine X Doukas — saved as images/063_.jpg
  [64] Romanos IV Diogenes — saved as images/064_.png
  [65] Michael VII Doukas — saved as images/065_.png
  [66] Nikephoros III Botaneiates — saved as images/066_.jpg
  [67] Alexios I Komnenos — saved as images/067_.jpg
  [68] John II Komnenos — saved as images/068_.jpg
  [69] Manuel I Komnenos — saved as images/069_.jpg
  [70] Alexios II Komnenos — saved as images/070_.png
  [71] Andronikos I Komnenos — saved as images/071_.jpg
  [72] Isaac II Angelos — saved as images/072_.png
  [73] Alexios III Angelos — saved as images/073_.png
  [74] Isaac II Angelos (restored) — saved as images/074_.png
  [75] Alexios IV Angelos — saved as images/075_.png
  [76] Alexios V Mourtzouphlos — saved as images/076_.png
  [77] Theodore I Laskaris — saved as images/077_.png
  [78] John III Doukas Vatatzes — saved as images/078_.png
  [79] Theodore II Laskaris — saved as images/079_.png
  [80] John IV Laskaris — saved as images/080_.png
  [81] Michael VIII Palaiologos — saved as images/081_.png
  [82] Andronikos II Palaiologos — saved as images/082_.png
  [83] Michael IX Palaiologos — saved as images/083_.png
  [84] Andronikos III Palaiologos — saved as images/084_.jpg
  [85] John V Palaiologos — saved as images/085_.jpg
  [86] John VI Kantakouzenos — saved as images/086_.jpg
  [87] Andronikos IV Palaiologos — saved as images/087_.png
  [88] John VII Palaiologos — saved as images/088_.jpg
  [89] Manuel II Palaiologos — saved as images/089_.jpg
  [90] John VIII Palaiologos — saved as images/090_.jpg
  [91] Constantine XI Palaiologos Dragases — saved as images/091_.jpg

Done! 91 images downloaded.
Failed: 0
Local paths saved to 'Local_Image' column in CSV.

In [6]:
import pandas as pd
import json

df = pd.read_csv('ERE_List_20260226.csv')

# Build emperor data list for JavaScript
emperors = []
for _, row in df.iterrows():
    emperors.append({
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "image":      str(row['Local_Image']),
        "years":      int(row['Reign_Length_Years']),
    })

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #111;
    color: #e8e8e8;
    font-family: 'Georgia', serif;
    overflow-x: hidden;
  }}
  h1 {{
    text-align: center;
    color: #c8a96e;
    font-size: 1.8em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #888;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-container {{
    position: relative;
    margin: 0 auto;
    width: 900px;
    height: 700px;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(20,20,20,0.97);
    border: 1px solid #c8a96e;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 280px;
    z-index: 100;
  }}
  #tooltip img {{
    width: 80px;
    height: 100px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name {{ color: #c8a96e; font-size: 1em; font-weight: bold; margin-bottom: 4px; }}
  #tooltip .tip-dynasty {{ color: #aaa; font-size: 0.8em; margin-bottom: 4px; }}
  #tooltip .tip-reign {{ color: #888; font-size: 0.78em; margin-bottom: 6px; }}
  #tooltip .tip-scores {{ color: #e8e8e8; font-size: 0.82em; margin-bottom: 6px; }}
  #tooltip .tip-summary {{ color: #bbb; font-size: 0.75em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #333; padding-top: 6px; }}
  .axis-label {{
    position: absolute;
    color: #888;
    font-size: 0.8em;
    letter-spacing: 1px;
    text-transform: uppercase;
  }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 30px;
    padding: 12px;
    flex-wrap: wrap;
  }}
  .legend-item {{
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 0.78em;
    color: #aaa;
  }}
  .legend-dot {{
    width: 12px;
    height: 12px;
    border-radius: 50%;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Hover over an emperor to learn more</p>

<div id="chart-container">
  <canvas id="bg-canvas" width="900" height="700"></canvas>
  <canvas id="img-canvas" width="900" height="700"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#e8c84a"></div>High Difficulty / High Effectiveness</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e87a4a"></div>High Difficulty / Low Effectiveness</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4ae87a"></div>Low Difficulty / High Effectiveness</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a8ae8"></div>Low Difficulty / Low Effectiveness</div>
</div>

<div id="tooltip"></div>

<script>
const EMPERORS = {data_json};

const PAD = {{ left: 70, right: 30, top: 40, bottom: 60 }};
const W = 900, H = 700;
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_SIZE = 20;
const MAX_SIZE = 70;

// Scale functions
function scaleX(d) {{ return PAD.left + ((d - 1) / 19) * plotW; }}
function scaleY(d) {{ return PAD.top + plotH - ((d - 1) / 19) * plotH; }}

// Quadrant color
function quadColor(diff, eff) {{
  const hiD = diff > 10, hiE = eff > 10;
  if (hiD && hiE)  return '#e8c84a';
  if (hiD && !hiE) return '#e87a4a';
  if (!hiD && hiE) return '#4ae87a';
  return '#4a8ae8';
}}

// Draw background grid and quadrant shading
const bgCanvas = document.getElementById('bg-canvas');
const bgCtx = bgCanvas.getContext('2d');

// Quadrant shading
const midX = scaleX(10.5);
const midY = scaleY(10.5);

function shadeQuadrant(x1, y1, x2, y2, color) {{
  bgCtx.fillStyle = color;
  bgCtx.fillRect(x1, y1, x2 - x1, y2 - y1);
}}

shadeQuadrant(PAD.left, PAD.top,   midX,        midY,         'rgba(74,138,232,0.07)');
shadeQuadrant(midX,     PAD.top,   PAD.left+plotW, midY,      'rgba(74,232,122,0.07)');
shadeQuadrant(PAD.left, midY,      midX,        PAD.top+plotH,'rgba(232,122,74,0.07)');
shadeQuadrant(midX,     midY,      PAD.left+plotW, PAD.top+plotH, 'rgba(232,200,74,0.07)');

// Quadrant dividers
bgCtx.strokeStyle = '#333';
bgCtx.lineWidth = 1;
bgCtx.setLineDash([4, 4]);
bgCtx.beginPath();
bgCtx.moveTo(midX, PAD.top);
bgCtx.lineTo(midX, PAD.top + plotH);
bgCtx.stroke();
bgCtx.beginPath();
bgCtx.moveTo(PAD.left, midY);
bgCtx.lineTo(PAD.left + plotW, midY);
bgCtx.stroke();
bgCtx.setLineDash([]);

// Grid lines
bgCtx.strokeStyle = '#222';
bgCtx.lineWidth = 1;
for (let i = 1; i <= 20; i++) {{
  const x = scaleX(i);
  const y = scaleY(i);
  bgCtx.beginPath(); bgCtx.moveTo(x, PAD.top); bgCtx.lineTo(x, PAD.top + plotH); bgCtx.stroke();
  bgCtx.beginPath(); bgCtx.moveTo(PAD.left, y); bgCtx.lineTo(PAD.left + plotW, y); bgCtx.stroke();
}}

// Axes
bgCtx.strokeStyle = '#555';
bgCtx.lineWidth = 2;
bgCtx.beginPath();
bgCtx.moveTo(PAD.left, PAD.top);
bgCtx.lineTo(PAD.left, PAD.top + plotH);
bgCtx.lineTo(PAD.left + plotW, PAD.top + plotH);
bgCtx.stroke();

// Axis tick labels
bgCtx.fillStyle = '#666';
bgCtx.font = '11px Georgia';
bgCtx.textAlign = 'center';
for (let i = 1; i <= 20; i += 2) {{
  bgCtx.fillText(i, scaleX(i), PAD.top + plotH + 18);
}}
bgCtx.textAlign = 'right';
for (let i = 1; i <= 20; i += 2) {{
  bgCtx.fillText(i, PAD.left - 8, scaleY(i) + 4);
}}

// Axis titles
bgCtx.fillStyle = '#888';
bgCtx.font = '13px Georgia';
bgCtx.textAlign = 'center';
bgCtx.fillText('Difficulty of Reign →', PAD.left + plotW / 2, H - 10);
bgCtx.save();
bgCtx.translate(16, PAD.top + plotH / 2);
bgCtx.rotate(-Math.PI / 2);
bgCtx.fillText('← Effectiveness', 0, 0);
bgCtx.restore();

// Quadrant labels
bgCtx.font = 'italic 11px Georgia';
bgCtx.fillStyle = 'rgba(200,200,200,0.25)';
bgCtx.textAlign = 'center';
bgCtx.fillText('Easy Reign, High Achievement', PAD.left + plotW * 0.75, PAD.top + 20);
bgCtx.fillText('Hard Reign, High Achievement', PAD.left + plotW * 0.25, PAD.top + 20);
bgCtx.fillText('Easy Reign, Low Achievement', PAD.left + plotW * 0.75, PAD.top + plotH - 10);
bgCtx.fillText('Hard Reign, Low Achievement', PAD.left + plotW * 0.25, PAD.top + plotH - 10);

const maxYears = Math.max(...EMPERORS.map(e => e.years));
function imgSize(years) {{
  return MIN_SIZE + ((years / maxYears) * (MAX_SIZE - MIN_SIZE));
}}


const imgCanvas = document.getElementById('img-canvas');
const imgCtx = imgCanvas.getContext('2d');
const positions = [];

EMPERORS.forEach((emp, i) => {{
  const cx = scaleX(emp.difficulty);
  const cy = scaleY(emp.effective);
  const half = imgSize(emp.years) / 2;
  positions.push({{ cx, cy, emp, half }});

  const img = new Image();
  img.crossOrigin = 'anonymous';
  img.onload = function() {{
    // Colored circle border
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half + 3, 0, Math.PI * 2);
    imgCtx.fillStyle = quadColor(emp.difficulty, emp.effective);
    imgCtx.fill();
    // Clip and draw image
    imgCtx.save();
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half, 0, Math.PI * 2);
    imgCtx.clip();
    imgCtx.drawImage(img, cx - half, cy - half, half * 2, half * 2);
    imgCtx.restore();
  }};
  img.onerror = function() {{
    // Fallback: colored circle with initial
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half + 3, 0, Math.PI * 2);
    imgCtx.fillStyle = quadColor(emp.difficulty, emp.effective);
    imgCtx.fill();
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half, 0, Math.PI * 2);
    imgCtx.fillStyle = '#333';
    imgCtx.fill();
    imgCtx.fillStyle = '#e8e8e8';
    imgCtx.font = `bold ${{Math.max(10, half * 0.6)}}px Georgia`;
    imgCtx.textAlign = 'center';
    imgCtx.fillText(emp.name.charAt(0), cx, cy + 4);
  }};
  img.src = emp.image;
}});

// Tooltip logic
const tooltip = document.getElementById('tooltip');
imgCanvas.addEventListener('mousemove', function(e) {{
  const rect = imgCanvas.getBoundingClientRect();
  const mx = e.clientX - rect.left;
  const my = e.clientY - rect.top;
  let found = null;
  for (const p of positions) {{
    const dx = mx - p.cx, dy = my - p.cy;
    if (Math.sqrt(dx*dx + dy*dy) < p.half + 4) {{
      found = p;
      break;
    }}
  }}
  if (found) {{
    const emp = found.emp;
    const imgTag = emp.image && emp.image !== 'PLACEHOLDER'
      ? `<img src="${{emp.image}}" onerror="this.style.display='none'">`
      : '';
    tooltip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{emp.name}}</div>
      <div class="tip-dynasty">${{emp.dynasty}}</div>
      <div class="tip-reign">${{emp.start}} – ${{emp.end}}</div>
      <div class="tip-scores">Difficulty: ${{emp.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{emp.effective}}</div>
      <div class="tip-summary">${{emp.summary}}</div>
    `;
    tooltip.style.display = 'block';
    let tx = e.clientX + 15;
    let ty = e.clientY - 10;
    if (tx + 290 > window.innerWidth) tx = e.clientX - 295;
    if (ty + 300 > window.innerHeight) ty = e.clientY - 300;
    tooltip.style.left = tx + 'px';
    tooltip.style.top  = ty + 'px';
    imgCanvas.style.cursor = 'pointer';
  }} else {{
    tooltip.style.display = 'none';
    imgCanvas.style.cursor = 'default';
  }}
}});
imgCanvas.addEventListener('mouseleave', () => {{ tooltip.style.display = 'none'; }});
</script>
</body>
</html>"""

with open('byzantine_scatter.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("Done! Open byzantine_scatter.html in your browser.")

Done! Open byzantine_scatter.html in your browser.

In [7]:
import pandas as pd
import json

df = pd.read_csv('ERE_List_20260226.csv')

# Build emperor data list for JavaScript
emperors = []
for _, row in df.iterrows():
    emperors.append({
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "image":      str(row['Local_Image']),
        "years":      int(row['Reign_Length_Years']),
    })

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #111;
    color: #e8e8e8;
    font-family: 'Georgia', serif;
    overflow-x: hidden;
  }}
  h1 {{
    text-align: center;
    color: #c8a96e;
    font-size: 1.8em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #888;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-container {{
    position: relative;
    margin: 0 auto;
    width: 900px;
    height: 700px;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(20,20,20,0.97);
    border: 1px solid #c8a96e;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 280px;
    z-index: 100;
  }}
  #tooltip img {{
    width: 80px;
    height: 100px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name {{ color: #c8a96e; font-size: 1em; font-weight: bold; margin-bottom: 4px; }}
  #tooltip .tip-dynasty {{ color: #aaa; font-size: 0.8em; margin-bottom: 4px; }}
  #tooltip .tip-reign {{ color: #888; font-size: 0.78em; margin-bottom: 6px; }}
  #tooltip .tip-scores {{ color: #e8e8e8; font-size: 0.82em; margin-bottom: 6px; }}
  #tooltip .tip-summary {{ color: #bbb; font-size: 0.75em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #333; padding-top: 6px; }}
  .axis-label {{
    position: absolute;
    color: #888;
    font-size: 0.8em;
    letter-spacing: 1px;
    text-transform: uppercase;
  }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 30px;
    padding: 12px;
    flex-wrap: wrap;
  }}
  .legend-item {{
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 0.78em;
    color: #aaa;
  }}
  .legend-dot {{
    width: 12px;
    height: 12px;
    border-radius: 50%;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Hover over an emperor to learn more</p>

<div id="chart-container">
  <canvas id="bg-canvas" width="900" height="700"></canvas>
  <canvas id="img-canvas" width="900" height="700"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#e8c84a"></div>High Difficulty / High Effectiveness</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e87a4a"></div>High Difficulty / Low Effectiveness</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4ae87a"></div>Low Difficulty / High Effectiveness</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a8ae8"></div>Low Difficulty / Low Effectiveness</div>
</div>

<div id="tooltip"></div>

<script>
const EMPERORS = {data_json};

const PAD = {{ left: 70, right: 30, top: 40, bottom: 60 }};
const W = 900, H = 700;
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_SIZE = 20;
const MAX_SIZE = 70;

// Scale functions
function scaleX(d) {{ return PAD.left + ((d - 1) / 19) * plotW; }}
function scaleY(d) {{ return PAD.top + plotH - ((d - 1) / 19) * plotH; }}

// Quadrant color
function quadColor(diff, eff) {{
  const hiD = diff > 10, hiE = eff > 10;
  if (hiD && hiE)  return '#e8c84a';
  if (hiD && !hiE) return '#e87a4a';
  if (!hiD && hiE) return '#4ae87a';
  return '#4a8ae8';
}}

// Draw background grid and quadrant shading
const bgCanvas = document.getElementById('bg-canvas');
const bgCtx = bgCanvas.getContext('2d');

// Quadrant shading
const midX = scaleX(10.5);
const midY = scaleY(10.5);

function shadeQuadrant(x1, y1, x2, y2, color) {{
  bgCtx.fillStyle = color;
  bgCtx.fillRect(x1, y1, x2 - x1, y2 - y1);
}}

shadeQuadrant(PAD.left, PAD.top,   midX,        midY,         'rgba(74,138,232,0.07)');
shadeQuadrant(midX,     PAD.top,   PAD.left+plotW, midY,      'rgba(74,232,122,0.07)');
shadeQuadrant(PAD.left, midY,      midX,        PAD.top+plotH,'rgba(232,122,74,0.07)');
shadeQuadrant(midX,     midY,      PAD.left+plotW, PAD.top+plotH, 'rgba(232,200,74,0.07)');

// Quadrant dividers
bgCtx.strokeStyle = '#333';
bgCtx.lineWidth = 1;
bgCtx.setLineDash([4, 4]);
bgCtx.beginPath();
bgCtx.moveTo(midX, PAD.top);
bgCtx.lineTo(midX, PAD.top + plotH);
bgCtx.stroke();
bgCtx.beginPath();
bgCtx.moveTo(PAD.left, midY);
bgCtx.lineTo(PAD.left + plotW, midY);
bgCtx.stroke();
bgCtx.setLineDash([]);

// Grid lines
bgCtx.strokeStyle = '#222';
bgCtx.lineWidth = 1;
for (let i = 1; i <= 20; i++) {{
  const x = scaleX(i);
  const y = scaleY(i);
  bgCtx.beginPath(); bgCtx.moveTo(x, PAD.top); bgCtx.lineTo(x, PAD.top + plotH); bgCtx.stroke();
  bgCtx.beginPath(); bgCtx.moveTo(PAD.left, y); bgCtx.lineTo(PAD.left + plotW, y); bgCtx.stroke();
}}

// Axes
bgCtx.strokeStyle = '#555';
bgCtx.lineWidth = 2;
bgCtx.beginPath();
bgCtx.moveTo(PAD.left, PAD.top);
bgCtx.lineTo(PAD.left, PAD.top + plotH);
bgCtx.lineTo(PAD.left + plotW, PAD.top + plotH);
bgCtx.stroke();

// Axis tick labels
bgCtx.fillStyle = '#666';
bgCtx.font = '11px Georgia';
bgCtx.textAlign = 'center';
for (let i = 1; i <= 20; i += 2) {{
  bgCtx.fillText(i, scaleX(i), PAD.top + plotH + 18);
}}
bgCtx.textAlign = 'right';
for (let i = 1; i <= 20; i += 2) {{
  bgCtx.fillText(i, PAD.left - 8, scaleY(i) + 4);
}}

// Axis titles
bgCtx.fillStyle = '#888';
bgCtx.font = '13px Georgia';
bgCtx.textAlign = 'center';
bgCtx.fillText('Difficulty of Reign →', PAD.left + plotW / 2, H - 10);
bgCtx.save();
bgCtx.translate(16, PAD.top + plotH / 2);
bgCtx.rotate(-Math.PI / 2);
bgCtx.fillText('← Effectiveness', 0, 0);
bgCtx.restore();

// Quadrant labels
bgCtx.font = 'italic 11px Georgia';
bgCtx.fillStyle = 'rgba(200,200,200,0.25)';
bgCtx.textAlign = 'center';
bgCtx.fillText('Easy Reign, High Achievement', PAD.left + plotW * 0.75, PAD.top + 20);
bgCtx.fillText('Hard Reign, High Achievement', PAD.left + plotW * 0.25, PAD.top + 20);
bgCtx.fillText('Easy Reign, Low Achievement', PAD.left + plotW * 0.75, PAD.top + plotH - 10);
bgCtx.fillText('Hard Reign, Low Achievement', PAD.left + plotW * 0.25, PAD.top + plotH - 10);

const maxYears = Math.max(...EMPERORS.map(e => e.years));
function imgSize(years) {{
  return MIN_SIZE + ((years / maxYears) * (MAX_SIZE - MIN_SIZE));
}}


const imgCanvas = document.getElementById('img-canvas');
const imgCtx = imgCanvas.getContext('2d');
const positions = [];

EMPERORS.forEach((emp, i) => {{
  const cx = scaleX(emp.difficulty);
  const cy = scaleY(emp.effective);
  const half = imgSize(emp.years) / 2;
  positions.push({{ cx, cy, emp, half }});

  const img = new Image();
  img.crossOrigin = 'anonymous';
  img.onload = function() {{
    // Colored circle border
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half + 3, 0, Math.PI * 2);
    imgCtx.fillStyle = quadColor(emp.difficulty, emp.effective);
    imgCtx.fill();
    // Clip and draw image
    imgCtx.save();
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half, 0, Math.PI * 2);
    imgCtx.clip();
    imgCtx.drawImage(img, cx - half, cy - half, half * 2, half * 2);
    imgCtx.restore();
  }};
  img.onerror = function() {{
    // Fallback: colored circle with initial
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half + 3, 0, Math.PI * 2);
    imgCtx.fillStyle = quadColor(emp.difficulty, emp.effective);
    imgCtx.fill();
    imgCtx.beginPath();
    imgCtx.arc(cx, cy, half, 0, Math.PI * 2);
    imgCtx.fillStyle = '#333';
    imgCtx.fill();
    imgCtx.fillStyle = '#e8e8e8';
    imgCtx.font = `bold ${{Math.max(10, half * 0.6)}}px Georgia`;
    imgCtx.textAlign = 'center';
    imgCtx.fillText(emp.name.charAt(0), cx, cy + 4);
  }};
  img.src = emp.image;
}});

// Tooltip logic
const tooltip = document.getElementById('tooltip');
imgCanvas.addEventListener('mousemove', function(e) {{
  const rect = imgCanvas.getBoundingClientRect();
  const mx = e.clientX - rect.left;
  const my = e.clientY - rect.top;
  let found = null;
  for (const p of positions) {{
    const dx = mx - p.cx, dy = my - p.cy;
    if (Math.sqrt(dx*dx + dy*dy) < p.half + 4) {{
      found = p;
      break;
    }}
  }}
  if (found) {{
    const emp = found.emp;
    const imgTag = emp.image && emp.image !== 'PLACEHOLDER'
      ? `<img src="${{emp.image}}" onerror="this.style.display='none'">`
      : '';
    tooltip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{emp.name}}</div>
      <div class="tip-dynasty">${{emp.dynasty}}</div>
      <div class="tip-reign">${{emp.start}} – ${{emp.end}}</div>
      <div class="tip-scores">Difficulty: ${{emp.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{emp.effective}}</div>
      <div class="tip-summary">${{emp.summary}}</div>
    `;
    tooltip.style.display = 'block';
    let tx = e.clientX + 15;
    let ty = e.clientY - 10;
    if (tx + 290 > window.innerWidth) tx = e.clientX - 295;
    if (ty + 300 > window.innerHeight) ty = e.clientY - 300;
    tooltip.style.left = tx + 'px';
    tooltip.style.top  = ty + 'px';
    imgCanvas.style.cursor = 'pointer';
  }} else {{
    tooltip.style.display = 'none';
    imgCanvas.style.cursor = 'default';
  }}
}});
imgCanvas.addEventListener('mouseleave', () => {{ tooltip.style.display = 'none'; }});
</script>
</body>
</html>"""

with open('byzantine_scatter.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("Done! Open byzantine_scatter.html in your browser.")

Done! Open byzantine_scatter.html in your browser.

In [8]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
for _, row in df.iterrows():
    print(f"{int(row['List_Number']):3d}. {row['Simple_Name_With_Epithets']:<45} D:{int(row['Difficulty']):2d}  E:{int(row['Effectiveness']):2d}")

  1. Constantine I the Great                       D: 5  E:18
  2. Constantius II                                D: 8  E:12
  3. Julian the Apostate                           D: 7  E:10
  4. Jovian                                        D: 8  E: 6
  5. Valens                                        D: 9  E:11
  6. Theodosios I the Great                        D:10  E:16
  7. Arkadios                                      D: 8  E: 5
  8. Theodosios II                                 D: 9  E:13
  9. Markianos                                     D: 7  E:12
 10. Leo I the Thracian                            D: 8  E:11
 11. Leo II                                        D: 6  E: 8
 12. Zeno                                          D:10  E:11
 13. Basiliskos (Usurper)                          D: 8  E: 1
 14. Anastasios I                                  D: 7  E:13
 15. Justin I                                      D: 6  E:10
 16. Justinian I the Great                         D:10  E:17
 17. Justin II                                     D:11  E: 8
 18. Tiberios II the Constantine                   D:10  E:12
 19. Maurikios                                     D:12  E:15
 20. Phokas                                        D: 8  E: 1
 21. Herakleios                                    D:14  E:17
 22. Constantine III                               D:14  E: 8
 23. Heraklonas                                    D:14  E: 3
 24. Constans II                                   D:13  E:13
 25. Constantine IV                                D:13  E:15
 26. Justinian II Slit-Nose                        D:12  E:10
 27. Leontios (Usurper)                            D: 8  E: 3
 28. Tiberios III (Usurper)                        D: 8  E: 7
 29. Philippikos (Usurper)                         D:10  E: 4
 30. Anastasios II                                 D: 9  E: 8
 31. Theodosios III                                D:10  E: 5
 32. Leo III the Isaurian                          D:13  E:16
 33. Constantine V Kopronymos                      D:11  E:15
 34. Artabasdos (Usurper)                          D: 8  E: 4
 35. Leo IV the Khazar                             D: 9  E:11
 36. Constantine VI                                D:10  E: 7
 37. Eirene                                        D: 9  E:12
 38. Nikephoros I                                  D: 9  E:12
 39. Staurakios                                    D:10  E: 5
 40. Michael I Rhangabe                            D:10  E: 6
 41. Leo V the Armenian                            D:11  E:13
 42. Michael II the Amorian                        D:10  E:11
 43. Theophilos                                    D:10  E:12
 44. Michael III the Drunkard                      D:11  E:14
 45. Basil I the Macedonian                        D: 8  E:16
 46. Leo VI the Wise                               D: 9  E:15
 47. Alexander                                     D: 9  E: 7
 48. Constantine VII Porphyrogennetos              D:12  E:13
 49. Romanos I Lekapenos                           D:10  E: 8
 50. Romanos II                                    D: 8  E:10
 51. Nikephoros II Phokas                          D:10  E:16
 52. John I Tzimiskes                              D:10  E:16
 53. Basil II the Bulgar-Slayer                    D:11  E:20
 54. Constantine VIII                              D: 6  E: 5
 55. Romanos III Argyros                           D: 8  E: 6
 56. Michael IV the Paphlagonian                   D: 8  E:10
 57. Michael V Kalaphates                          D: 8  E: 1
 58. Zoe (with Theodora)                           D: 7  E: 8
 59. Theodora                                      D: 7  E: 9
 60. Constantine IX Monomachos                     D: 8  E: 7
 61. Michael VI Bringas                            D: 9  E: 5
 62. Isaac I Komnenos                              D:10  E:12
 63. Constantine X Doukas                          D:11  E: 8
 64. Romanos IV Diogenes                           D:13  E: 5
 65. Michael VII Doukas                            D:13  E: 6
 66. Nikephoros III Botaneiates                    D:12  E: 7
 67. Alexios I Komnenos                            D:14  E:16
 68. John II Komnenos                              D:12  E:17
 69. Manuel I Komnenos                             D:10  E:14
 70. Alexios II Komnenos                           D:11  E: 6
 71. Andronikos I Komnenos                         D:11  E: 8
 72. Isaac II Angelos                              D:12  E:10
 73. Alexios III Angelos                           D:12  E: 5
 74. Isaac II Angelos (restored)                   D:14  E: 4
 75. Alexios IV Angelos                            D:14  E: 4
 76. Alexios V Mourtzouphlos                       D:15  E: 6
 77. Theodore I Laskaris                           D:14  E:14
 78. John III Doukas Vatatzes                      D:12  E:17
 79. Theodore II Laskaris                          D:11  E:12
 80. John IV Laskaris                              D:13  E: 5
 81. Michael VIII Palaiologos                      D:13  E:15
 82. Andronikos II Palaiologos                     D:15  E:10
 83. Michael IX Palaiologos                        D:14  E:10
 84. Andronikos III Palaiologos                    D:15  E:12
 85. John V Palaiologos                            D:17  E: 7
 86. John VI Kantakouzenos                         D:10  E: 4
 87. Andronikos IV Palaiologos                     D:16  E: 6
 88. John VII Palaiologos                          D:16  E: 5
 89. Manuel II Palaiologos                         D:16  E:14
 90. John VIII Palaiologos                         D:18  E:11
 91. Constantine XI Palaiologos Dragases           D:20  E:18

In [9]:
import pandas as pd

# ── Edit scores here ──────────────────────────────────────────────────────────
# Format: List_Number: (Difficulty, Effectiveness)
# Difficulty  1-20: how hard was the situation they inherited/faced
# Effectiveness 1-20: how well did they handle it relative to what was possible

RATINGS = {
    1:  (5,  18),  # Constantine I the Great
    2:  (8,  12),  # Constantius II
    3:  (7,  10),  # Julian the Apostate
    4:  (8,   6),  # Jovian
    5:  (10,  5),  # Valens
    6:  (10, 16),  # Theodosios I the Great
    7:  (8,   5),  # Arkadios
    8:  (9,  13),  # Theodosios II
    9:  (7,  12),  # Markianos
    10: (8,  11),  # Leo I the Thracian
    11: (6,   8),  # Leo II
    12: (10, 11),  # Zeno
    13: (8,   1),  # Basiliskos
    14: (7,  13),  # Anastasios I
    15: (6,  10),  # Justin I
    16: (5, 16),  # Justinian I the Great
    17: (11,  8),  # Justin II
    18: (10, 12),  # Tiberios II the Constantine
    19: (12, 15),  # Maurikios
    20: (8,   1),  # Phokas
    21: (14, 17),  # Herakleios
    22: (14,  8),  # Constantine III
    23: (20,  15),  # Heraklonas
    24: (13, 13),  # Constans II
    25: (13, 15),  # Constantine IV
    26: (12, 10),  # Justinian II Slit-Nose
    27: (8,   3),  # Leontios
    28: (8,   7),  # Tiberios III
    29: (10,  4),  # Philippikos
    30: (9,   8),  # Anastasios II
    31: (10,  5),  # Theodosios III
    32: (18, 19),  # Leo III the Isaurian
    33: (11, 15),  # Constantine V Kopronymos
    34: (8,   4),  # Artabasdos
    35: (9,  11),  # Leo IV the Khazar
    36: (10,  7),  # Constantine VI
    37: (9,  12),  # Eirene
    38: (9,  12),  # Nikephoros I
    39: (10,  5),  # Staurakios
    40: (10,  6),  # Michael I Rhangabe
    41: (11, 13),  # Leo V the Armenian
    42: (10, 11),  # Michael II the Amorian
    43: (10, 12),  # Theophilos
    44: (11, 14),  # Michael III the Drunkard
    45: (8,  16),  # Basil I the Macedonian
    46: (9,  15),  # Leo VI the Wise
    47: (9,   7),  # Alexander
    48: (12, 13),  # Constantine VII Porphyrogennetos
    49: (10,  8),  # Romanos I Lekapenos
    50: (8,  10),  # Romanos II
    51: (10, 16),  # Nikephoros II Phokas
    52: (10, 16),  # John I Tzimiskes
    53: (11, 20),  # Basil II the Bulgar-Slayer
    54: (6,   5),  # Constantine VIII
    55: (8,   6),  # Romanos III Argyros
    56: (8,  10),  # Michael IV the Paphlagonian
    57: (8,   5),  # Michael V Kalaphates
    58: (7,   10),  # Zoe
    59: (7,   10),  # Theodora
    60: (8,   7),  # Constantine IX Monomachos
    61: (9,   5),  # Michael VI Bringas
    62: (10, 12),  # Isaac I Komnenos
    63: (11,  8),  # Constantine X Doukas
    64: (13,  5),  # Romanos IV Diogenes
    65: (13,  6),  # Michael VII Doukas
    66: (12,  7),  # Nikephoros III Botaneiates
    67: (14, 16),  # Alexios I Komnenos
    68: (12, 17),  # John II Komnenos
    69: (10, 14),  # Manuel I Komnenos
    70: (11,  6),  # Alexios II Komnenos
    71: (11,  8),  # Andronikos I Komnenos
    72: (12, 10),  # Isaac II Angelos
    73: (12,  5),  # Alexios III Angelos
    74: (14,  2),  # Isaac II Angelos (restored)
    75: (14,  4),  # Alexios IV Angelos
    76: (15,  6),  # Alexios V Mourtzouphlos
    77: (14, 14),  # Theodore I Laskaris
    78: (12, 17),  # John III Doukas Vatatzes
    79: (11, 12),  # Theodore II Laskaris
    80: (13,  5),  # John IV Laskaris
    81: (13, 15),  # Michael VIII Palaiologos
    82: (15, 10),  # Andronikos II Palaiologos
    83: (14, 10),  # Michael IX Palaiologos
    84: (15, 12),  # Andronikos III Palaiologos
    85: (17,  7),  # John V Palaiologos
    86: (10,  4),  # John VI Kantakouzenos
    87: (16,  6),  # Andronikos IV Palaiologos
    88: (16,  5),  # John VII Palaiologos
    89: (16, 14),  # Manuel II Palaiologos
    90: (18, 11),  # John VIII Palaiologos
    91: (20, 12),  # Constantine XI Palaiologos Dragases
}

# ── Apply and save ────────────────────────────────────────────────────────────
df = pd.read_csv('ERE_List_20260226.csv')
df['Difficulty']    = df['List_Number'].map(lambda x: RATINGS.get(x, (1,1))[0])
df['Effectiveness'] = df['List_Number'].map(lambda x: RATINGS.get(x, (1,1))[1])
df.to_csv('ERE_List_20260226.csv', index=False)

print("Done! Updated scores:")
print(f"\n{'#':<4} {'Emperor':<45} {'D':>4} {'E':>4}")
print("-" * 60)
for _, row in df.iterrows():
    print(f"{int(row['List_Number']):<4} {row['Simple_Name_With_Epithets']:<45} {int(row['Difficulty']):>4} {int(row['Effectiveness']):>4}")

Done! Updated scores:

#    Emperor                                          D    E
------------------------------------------------------------
1    Constantine I the Great                          5   18
2    Constantius II                                   8   12
3    Julian the Apostate                              7   10
4    Jovian                                           8    6
5    Valens                                          10    5
6    Theodosios I the Great                          10   16
7    Arkadios                                         8    5
8    Theodosios II                                    9   13
9    Markianos                                        7   12
10   Leo I the Thracian                               8   11
11   Leo II                                           6    8
12   Zeno                                            10   11
13   Basiliskos (Usurper)                             8    1
14   Anastasios I                                     7   13
15   Justin I                                         6   10
16   Justinian I the Great                            5   16
17   Justin II                                       11    8
18   Tiberios II the Constantine                     10   12
19   Maurikios                                       12   15
20   Phokas                                           8    1
21   Herakleios                                      14   17
22   Constantine III                                 14    8
23   Heraklonas                                      20   15
24   Constans II                                     13   13
25   Constantine IV                                  13   15
26   Justinian II Slit-Nose                          12   10
27   Leontios (Usurper)                               8    3
28   Tiberios III (Usurper)                           8    7
29   Philippikos (Usurper)                           10    4
30   Anastasios II                                    9    8
31   Theodosios III                                  10    5
32   Leo III the Isaurian                            18   19
33   Constantine V Kopronymos                        11   15
34   Artabasdos (Usurper)                             8    4
35   Leo IV the Khazar                                9   11
36   Constantine VI                                  10    7
37   Eirene                                           9   12
38   Nikephoros I                                     9   12
39   Staurakios                                      10    5
40   Michael I Rhangabe                              10    6
41   Leo V the Armenian                              11   13
42   Michael II the Amorian                          10   11
43   Theophilos                                      10   12
44   Michael III the Drunkard                        11   14
45   Basil I the Macedonian                           8   16
46   Leo VI the Wise                                  9   15
47   Alexander                                        9    7
48   Constantine VII Porphyrogennetos                12   13
49   Romanos I Lekapenos                             10    8
50   Romanos II                                       8   10
51   Nikephoros II Phokas                            10   16
52   John I Tzimiskes                                10   16
53   Basil II the Bulgar-Slayer                      11   20
54   Constantine VIII                                 6    5
55   Romanos III Argyros                              8    6
56   Michael IV the Paphlagonian                      8   10
57   Michael V Kalaphates                             8    5
58   Zoe (with Theodora)                              7   10
59   Theodora                                         7   10
60   Constantine IX Monomachos                        8    7
61   Michael VI Bringas                               9    5
62   Isaac I Komnenos                                10   12
63   Constantine X Doukas                            11    8
64   Romanos IV Diogenes                             13    5
65   Michael VII Doukas                              13    6
66   Nikephoros III Botaneiates                      12    7
67   Alexios I Komnenos                              14   16
68   John II Komnenos                                12   17
69   Manuel I Komnenos                               10   14
70   Alexios II Komnenos                             11    6
71   Andronikos I Komnenos                           11    8
72   Isaac II Angelos                                12   10
73   Alexios III Angelos                             12    5
74   Isaac II Angelos (restored)                     14    2
75   Alexios IV Angelos                              14    4
76   Alexios V Mourtzouphlos                         15    6
77   Theodore I Laskaris                             14   14
78   John III Doukas Vatatzes                        12   17
79   Theodore II Laskaris                            11   12
80   John IV Laskaris                                13    5
81   Michael VIII Palaiologos                        13   15
82   Andronikos II Palaiologos                       15   10
83   Michael IX Palaiologos                          14   10
84   Andronikos III Palaiologos                      15   12
85   John V Palaiologos                              17    7
86   John VI Kantakouzenos                           10    4
87   Andronikos IV Palaiologos                       16    6
88   John VII Palaiologos                            16    5
89   Manuel II Palaiologos                           16   14
90   John VIII Palaiologos                           18   11
91   Constantine XI Palaiologos Dragases             20   12

In [10]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')

df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

df_ranked = df.sort_values('Composite', ascending=False).reset_index(drop=True)

print(f"{'Rank':<5} {'Emperor':<45} {'D':>4} {'E':>4} {'Score':>6}")
print("-" * 65)
for i, row in df_ranked.iterrows():
    print(f"{i+1:<5} {row['Simple_Name_With_Epithets']:<45} {int(row['Difficulty']):>4} {int(row['Effectiveness']):>4} {row['Composite']:>6}")

Rank  Emperor                                          D    E  Score
-----------------------------------------------------------------
1     Leo III the Isaurian                            18   19   93.0
2     Heraklonas                                      20   15   85.0
3     Basil II the Bulgar-Slayer                      11   20   82.0
4     Herakleios                                      14   17   79.0
5     Alexios I Komnenos                              14   16   76.0
6     Constantine XI Palaiologos Dragases             20   12   76.0
7     John III Doukas Vatatzes                        12   17   75.0
8     John II Komnenos                                12   17   75.0
9     Manuel II Palaiologos                           16   14   74.0
10    Michael VIII Palaiologos                        13   15   71.0
11    Constantine IV                                  13   15   71.0
12    Theodore I Laskaris                             14   14   70.0
13    Maurikios                                       12   15   69.0
14    John VIII Palaiologos                           18   11   69.0
15    Theodosios I the Great                          10   16   68.0
16    John I Tzimiskes                                10   16   68.0
17    Nikephoros II Phokas                            10   16   68.0
18    Constantine V Kopronymos                        11   15   67.0
19    Andronikos III Palaiologos                      15   12   66.0
20    Constans II                                     13   13   65.0
21    Basil I the Macedonian                           8   16   64.0
22    Michael III the Drunkard                        11   14   64.0
23    Constantine I the Great                          5   18   64.0
24    Leo VI the Wise                                  9   15   63.0
25    Constantine VII Porphyrogennetos                12   13   63.0
26    Manuel I Komnenos                               10   14   62.0
27    Leo V the Armenian                              11   13   61.0
28    Andronikos II Palaiologos                       15   10   60.0
29    Justinian I the Great                            5   16   58.0
30    Michael IX Palaiologos                          14   10   58.0
31    Theodore II Laskaris                            11   12   58.0
32    Theodosios II                                    9   13   57.0
33    Tiberios II the Constantine                     10   12   56.0
34    Theophilos                                      10   12   56.0
35    Isaac I Komnenos                                10   12   56.0
36    John V Palaiologos                              17    7   55.0
37    Eirene                                           9   12   54.0
38    Nikephoros I                                     9   12   54.0
39    Justinian II Slit-Nose                          12   10   54.0
40    Isaac II Angelos                                12   10   54.0
41    Anastasios I                                     7   13   53.0
42    Michael II the Amorian                          10   11   53.0
43    Zeno                                            10   11   53.0
44    Constantius II                                   8   12   52.0
45    Constantine III                                 14    8   52.0
46    Leo IV the Khazar                                9   11   51.0
47    Andronikos IV Palaiologos                       16    6   50.0
48    Markianos                                        7   12   50.0
49    Leo I the Thracian                               8   11   49.0
50    Alexios V Mourtzouphlos                         15    6   48.0
51    John VII Palaiologos                            16    5   47.0
52    Michael IV the Paphlagonian                      8   10   46.0
53    Andronikos I Komnenos                           11    8   46.0
54    Justin II                                       11    8   46.0
55    Constantine X Doukas                            11    8   46.0
56    Romanos II                                       8   10   46.0
57    Nikephoros III Botaneiates                      12    7   45.0
58    Michael VII Doukas                              13    6   44.0
59    Theodora                                         7   10   44.0
60    Romanos I Lekapenos                             10    8   44.0
61    Julian the Apostate                              7   10   44.0
62    Zoe (with Theodora)                              7   10   44.0
63    Anastasios II                                    9    8   42.0
64    Justin I                                         6   10   42.0
65    Romanos IV Diogenes                             13    5   41.0
66    Constantine VI                                  10    7   41.0
67    John IV Laskaris                                13    5   41.0
68    Alexios II Komnenos                             11    6   40.0
69    Alexios IV Angelos                              14    4   40.0
70    Alexander                                        9    7   39.0
71    Alexios III Angelos                             12    5   39.0
72    Michael I Rhangabe                              10    6   38.0
73    Constantine IX Monomachos                        8    7   37.0
74    Tiberios III (Usurper)                           8    7   37.0
75    Leo II                                           6    8   36.0
76    Staurakios                                      10    5   35.0
77    Valens                                          10    5   35.0
78    Theodosios III                                  10    5   35.0
79    Romanos III Argyros                              8    6   34.0
80    Isaac II Angelos (restored)                     14    2   34.0
81    Jovian                                           8    6   34.0
82    Michael VI Bringas                               9    5   33.0
83    Philippikos (Usurper)                           10    4   32.0
84    John VI Kantakouzenos                           10    4   32.0
85    Arkadios                                         8    5   31.0
86    Michael V Kalaphates                             8    5   31.0
87    Artabasdos (Usurper)                             8    4   28.0
88    Constantine VIII                                 6    5   27.0
89    Leontios (Usurper)                               8    3   25.0
90    Basiliskos (Usurper)                             8    1   19.0
91    Phokas                                           8    1   19.0

In [11]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')

# Find the restored Isaac II and drop him
restored = df[df['Simple_Name_With_Epithets'] == 'Isaac II Angelos (restored)'].index
df = df.drop(restored)

# Update the original Isaac II summary to mention restoration
mask = df['Simple_Name_With_Epithets'] == 'Isaac II Angelos'
df.loc[mask, 'Summary'] = df.loc[mask, 'Summary'].values[0] + ' Briefly restored in 1203 by the Fourth Crusade alongside his son Alexios IV, but blind and powerless; killed when Alexios V seized power in 1204.'
df.loc[mask, 'Simple_Name_With_Epithets'] = 'Isaac II Angelos'

# Renumber
df['List_Number'] = range(1, len(df) + 1)

df.to_csv('ERE_List_20260226.csv', index=False)
print(f"Done! {len(df)} emperors remaining.")

Done! 90 emperors remaining.

In [12]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')

# Remove (Usurper) from name fields
for col in ['Simple_Name', 'Simple_Name_With_Epithets']:
    df[col] = df[col].str.replace(' (Usurper)', '', regex=False)

df.to_csv('ERE_List_20260226.csv', index=False)
print("Done! Usurper labels removed.")

Done! Usurper labels removed.

In [14]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')
df['Lis'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Sort by List_number
df_sorted = df.sort_values('Composite', ascending=False).reset_index(drop=True)

print(f"{'Rank':<5} {'Emperor':<45} {'D':>4} {'E':>4} {'Score':>6}")
print("-" * 65)
for i, row in df_sorted.iterrows():
    print(f"{i+1:<5} {row['Simple_Name_With_Epithets']:<45} {int(row['Difficulty']):>4} {int(row['Effectiveness']):>4} {row['Composite']:>6}")

Rank  Emperor                                          D    E  Score
-----------------------------------------------------------------
1     Leo III the Isaurian                            18   19   93.0
2     Heraklonas                                      20   15   85.0
3     Basil II the Bulgar-Slayer                      11   20   82.0
4     Herakleios                                      14   17   79.0
5     Alexios I Komnenos                              14   16   76.0
6     Constantine XI Palaiologos Dragases             20   12   76.0
7     John III Doukas Vatatzes                        12   17   75.0
8     John II Komnenos                                12   17   75.0
9     Manuel II Palaiologos                           16   14   74.0
10    Michael VIII Palaiologos                        13   15   71.0
11    Constantine IV                                  13   15   71.0
12    Theodore I Laskaris                             14   14   70.0
13    Maurikios                                       12   15   69.0
14    John VIII Palaiologos                           18   11   69.0
15    Theodosios I the Great                          10   16   68.0
16    John I Tzimiskes                                10   16   68.0
17    Nikephoros II Phokas                            10   16   68.0
18    Constantine V Kopronymos                        11   15   67.0
19    Andronikos III Palaiologos                      15   12   66.0
20    Constans II                                     13   13   65.0
21    Basil I the Macedonian                           8   16   64.0
22    Michael III the Drunkard                        11   14   64.0
23    Constantine I the Great                          5   18   64.0
24    Leo VI the Wise                                  9   15   63.0
25    Constantine VII Porphyrogennetos                12   13   63.0
26    Manuel I Komnenos                               10   14   62.0
27    Leo V the Armenian                              11   13   61.0
28    Andronikos II Palaiologos                       15   10   60.0
29    Justinian I the Great                            5   16   58.0
30    Michael IX Palaiologos                          14   10   58.0
31    Theodore II Laskaris                            11   12   58.0
32    Theodosios II                                    9   13   57.0
33    Tiberios II the Constantine                     10   12   56.0
34    Theophilos                                      10   12   56.0
35    Isaac I Komnenos                                10   12   56.0
36    John V Palaiologos                              17    7   55.0
37    Eirene                                           9   12   54.0
38    Nikephoros I                                     9   12   54.0
39    Justinian II Slit-Nose                          12   10   54.0
40    Isaac II Angelos                                12   10   54.0
41    Anastasios I                                     7   13   53.0
42    Michael II the Amorian                          10   11   53.0
43    Zeno                                            10   11   53.0
44    Constantius II                                   8   12   52.0
45    Constantine III                                 14    8   52.0
46    Leo IV the Khazar                                9   11   51.0
47    Andronikos IV Palaiologos                       16    6   50.0
48    Markianos                                        7   12   50.0
49    Leo I the Thracian                               8   11   49.0
50    Alexios V Mourtzouphlos                         15    6   48.0
51    John VII Palaiologos                            16    5   47.0
52    Romanos II                                       8   10   46.0
53    Michael IV the Paphlagonian                      8   10   46.0
54    Justin II                                       11    8   46.0
55    Andronikos I Komnenos                           11    8   46.0
56    Constantine X Doukas                            11    8   46.0
57    Nikephoros III Botaneiates                      12    7   45.0
58    Romanos I Lekapenos                             10    8   44.0
59    Michael VII Doukas                              13    6   44.0
60    Zoe (with Theodora)                              7   10   44.0
61    Theodora                                         7   10   44.0
62    Julian the Apostate                              7   10   44.0
63    Anastasios II                                    9    8   42.0
64    Justin I                                         6   10   42.0
65    Romanos IV Diogenes                             13    5   41.0
66    John IV Laskaris                                13    5   41.0
67    Constantine VI                                  10    7   41.0
68    Alexios II Komnenos                             11    6   40.0
69    Alexios IV Angelos                              14    4   40.0
70    Alexander                                        9    7   39.0
71    Alexios III Angelos                             12    5   39.0
72    Michael I Rhangabe                              10    6   38.0
73    Tiberios III                                     8    7   37.0
74    Constantine IX Monomachos                        8    7   37.0
75    Leo II                                           6    8   36.0
76    Theodosios III                                  10    5   35.0
77    Valens                                          10    5   35.0
78    Staurakios                                      10    5   35.0
79    Romanos III Argyros                              8    6   34.0
80    Jovian                                           8    6   34.0
81    Michael VI Bringas                               9    5   33.0
82    Philippikos                                     10    4   32.0
83    John VI Kantakouzenos                           10    4   32.0
84    Arkadios                                         8    5   31.0
85    Michael V Kalaphates                             8    5   31.0
86    Artabasdos                                       8    4   28.0
87    Constantine VIII                                 6    5   27.0
88    Leontios                                         8    3   25.0
89    Basiliskos                                       8    1   19.0
90    Phokas                                           8    1   19.0

In [18]:
df_sorted = df.sort_values('Difficulty', ascending=False).reset_index(drop=True)

In [19]:
df

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL,Difficulty,Effectiveness,Local_Image,Composite
0,1,Constantine I,Constantine I the Great,Flavius Valerius Constantinus,Constantinian,Constantinus,306,337,31,Sole emperor from 324. Moved the imperial capi...,Co-ruled with Licinius 313-324; sons Constanti...,https://upload.wikimedia.org/wikipedia/commons...,5,18,images/001_.jpg,64.0
1,2,Constantius II,Constantius II,Flavius Julius Constantius,Constantinian,Constantinus,337,361,24,Son of Constantine I. Sole emperor from 350. F...,Co-emperor with brothers 337-350; appointed Ju...,https://upload.wikimedia.org/wikipedia/commons...,8,12,images/002_.jpg,52.0
2,3,Julian,Julian the Apostate,Flavius Claudius Julianus,Constantinian,Constantinus,361,363,2,Last non-Christian emperor. Attempted to resto...,Caesar under Constantius II from 355; proclaim...,https://upload.wikimedia.org/wikipedia/commons...,7,10,images/003_.jpg,44.0
3,4,Jovian,Jovian,Flavius Jovianus,NaN,Non-dynastic,363,364,1,Elected by the army after Julian's death. Made...,Sole emperor; no co-rulers,https://upload.wikimedia.org/wikipedia/commons...,8,6,images/004_.jpg,34.0
4,5,Valens,Valens,Flavius Valens,Valentinianic,Valentinianus,364,378,14,"Eastern emperor, brother of Valentinian I. All...",Co-emperor in the east under arrangement with ...,https://upload.wikimedia.org/wikipedia/commons...,10,5,images/005_.png,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,86,Andronikos IV,Andronikos IV Palaiologos,Andronicus Palaeologus,Palaiologan,Palaiologos,1376,1379,3,Son of John V who rebelled against his father ...,Usurper against his father John V; later recog...,https://upload.wikimedia.org/wikipedia/commons...,16,6,images/087_.png,50.0
86,87,John VII,John VII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1390,1390,1,Grandson of John V who briefly seized Constant...,Brief usurper; later legitimate co-emperor and...,https://upload.wikimedia.org/wikipedia/commons...,16,5,images/088_.jpg,47.0
87,88,Manuel II,Manuel II Palaiologos,Manuel Palaeologus,Palaiologan,Palaiologos,1391,1425,34,Cultivated and able emperor facing an impossib...,Co-emperor under John V from 1373; made his so...,https://upload.wikimedia.org/wikipedia/commons...,16,14,images/089_.jpg,74.0
88,89,John VIII,John VIII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1425,1448,23,Son of Manuel II. Attended the Council of Flor...,Co-emperor under Manuel II from 1421; made his...,https://upload.wikimedia.org/wikipedia/commons...,18,11,images/090_.jpg,69.0
89,90,Constantine XI,Constantine XI Palaiologos Dragases,Constantine Palaeologus Dragases,Palaiologan,Palaiologos,1449,1453,4,Last Byzantine emperor. Defended Constantinopl...,Sole emperor at the end; no co-emperor,https://upload.wikimedia.org/wikipedia/commons...,20,12,images/091_.jpg,76.0

In [1]:
df

NameError: name 'df' is not defined

In [2]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
print(f"Loaded {len(df)} emperors")

Loaded 90 emperors

In [3]:
df

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL,Difficulty,Effectiveness,Local_Image
0,1,Constantine I,Constantine I the Great,Flavius Valerius Constantinus,Constantinian,Constantinus,306,337,31,Sole emperor from 324. Moved the imperial capi...,Co-ruled with Licinius 313-324; sons Constanti...,https://upload.wikimedia.org/wikipedia/commons...,5,18,images/001_.jpg
1,2,Constantius II,Constantius II,Flavius Julius Constantius,Constantinian,Constantinus,337,361,24,Son of Constantine I. Sole emperor from 350. F...,Co-emperor with brothers 337-350; appointed Ju...,https://upload.wikimedia.org/wikipedia/commons...,8,12,images/002_.jpg
2,3,Julian,Julian the Apostate,Flavius Claudius Julianus,Constantinian,Constantinus,361,363,2,Last non-Christian emperor. Attempted to resto...,Caesar under Constantius II from 355; proclaim...,https://upload.wikimedia.org/wikipedia/commons...,7,10,images/003_.jpg
3,4,Jovian,Jovian,Flavius Jovianus,NaN,Non-dynastic,363,364,1,Elected by the army after Julian's death. Made...,Sole emperor; no co-rulers,https://upload.wikimedia.org/wikipedia/commons...,8,6,images/004_.jpg
4,5,Valens,Valens,Flavius Valens,Valentinianic,Valentinianus,364,378,14,"Eastern emperor, brother of Valentinian I. All...",Co-emperor in the east under arrangement with ...,https://upload.wikimedia.org/wikipedia/commons...,10,5,images/005_.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,86,Andronikos IV,Andronikos IV Palaiologos,Andronicus Palaeologus,Palaiologan,Palaiologos,1376,1379,3,Son of John V who rebelled against his father ...,Usurper against his father John V; later recog...,https://upload.wikimedia.org/wikipedia/commons...,16,6,images/087_.png
86,87,John VII,John VII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1390,1390,1,Grandson of John V who briefly seized Constant...,Brief usurper; later legitimate co-emperor and...,https://upload.wikimedia.org/wikipedia/commons...,16,5,images/088_.jpg
87,88,Manuel II,Manuel II Palaiologos,Manuel Palaeologus,Palaiologan,Palaiologos,1391,1425,34,Cultivated and able emperor facing an impossib...,Co-emperor under John V from 1373; made his so...,https://upload.wikimedia.org/wikipedia/commons...,16,14,images/089_.jpg
88,89,John VIII,John VIII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1425,1448,23,Son of Manuel II. Attended the Council of Flor...,Co-emperor under Manuel II from 1421; made his...,https://upload.wikimedia.org/wikipedia/commons...,18,11,images/090_.jpg
89,90,Constantine XI,Constantine XI Palaiologos Dragases,Constantine Palaeologus Dragases,Palaiologan,Palaiologos,1449,1453,4,Last Byzantine emperor. Defended Constantinopl...,Sole emperor at the end; no co-emperor,https://upload.wikimedia.org/wikipedia/commons...,20,12,images/091_.jpg

In [4]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

print(f"{'#':<4} {'Emperor':<45} {'D':>4} {'E':>4}")
print("-" * 60)
for _, row in df.iterrows():
    print(f"{int(row['List_Number']):<4} {row['Simple_Name_With_Epithets']:<45} {int(row['Difficulty']):>4} {int(row['Effectiveness']):>4}")

#    Emperor                                          D    E
------------------------------------------------------------
1    Constantine I the Great                          5   18
2    Constantius II                                   8   12
3    Julian the Apostate                              7   10
4    Jovian                                           8    6
5    Valens                                          10    5
6    Theodosios I the Great                          10   16
7    Arkadios                                         8    5
8    Theodosios II                                    9   13
9    Markianos                                        7   12
10   Leo I the Thracian                               8   11
11   Leo II                                           6    8
12   Zeno                                            10   11
13   Basiliskos                                       8    1
14   Anastasios I                                     7   13
15   Justin I                                         6   10
16   Justinian I the Great                            5   16
17   Justin II                                       11    8
18   Tiberios II the Constantine                     10   12
19   Maurikios                                       12   15
20   Phokas                                           8    1
21   Herakleios                                      14   17
22   Constantine III                                 14    8
23   Heraklonas                                      20   15
24   Constans II                                     13   13
25   Constantine IV                                  13   15
26   Justinian II Slit-Nose                          12   10
27   Leontios                                         8    3
28   Tiberios III                                     8    7
29   Philippikos                                     10    4
30   Anastasios II                                    9    8
31   Theodosios III                                  10    5
32   Leo III the Isaurian                            18   19
33   Constantine V Kopronymos                        11   15
34   Artabasdos                                       8    4
35   Leo IV the Khazar                                9   11
36   Constantine VI                                  10    7
37   Eirene                                           9   12
38   Nikephoros I                                     9   12
39   Staurakios                                      10    5
40   Michael I Rhangabe                              10    6
41   Leo V the Armenian                              11   13
42   Michael II the Amorian                          10   11
43   Theophilos                                      10   12
44   Michael III the Drunkard                        11   14
45   Basil I the Macedonian                           8   16
46   Leo VI the Wise                                  9   15
47   Alexander                                        9    7
48   Constantine VII Porphyrogennetos                12   13
49   Romanos I Lekapenos                             10    8
50   Romanos II                                       8   10
51   Nikephoros II Phokas                            10   16
52   John I Tzimiskes                                10   16
53   Basil II the Bulgar-Slayer                      11   20
54   Constantine VIII                                 6    5
55   Romanos III Argyros                              8    6
56   Michael IV the Paphlagonian                      8   10
57   Michael V Kalaphates                             8    5
58   Zoe (with Theodora)                              7   10
59   Theodora                                         7   10
60   Constantine IX Monomachos                        8    7
61   Michael VI Bringas                               9    5
62   Isaac I Komnenos                                10   12
63   Constantine X Doukas                            11    8
64   Romanos IV Diogenes                             13    5
65   Michael VII Doukas                              13    6
66   Nikephoros III Botaneiates                      12    7
67   Alexios I Komnenos                              14   16
68   John II Komnenos                                12   17
69   Manuel I Komnenos                               10   14
70   Alexios II Komnenos                             11    6
71   Andronikos I Komnenos                           11    8
72   Isaac II Angelos                                12   10
73   Alexios III Angelos                             12    5
74   Alexios IV Angelos                              14    4
75   Alexios V Mourtzouphlos                         15    6
76   Theodore I Laskaris                             14   14
77   John III Doukas Vatatzes                        12   17
78   Theodore II Laskaris                            11   12
79   John IV Laskaris                                13    5
80   Michael VIII Palaiologos                        13   15
81   Andronikos II Palaiologos                       15   10
82   Michael IX Palaiologos                          14   10
83   Andronikos III Palaiologos                      15   12
84   John V Palaiologos                              17    7
85   John VI Kantakouzenos                           10    4
86   Andronikos IV Palaiologos                       16    6
87   John VII Palaiologos                            16    5
88   Manuel II Palaiologos                           16   14
89   John VIII Palaiologos                           18   11
90   Constantine XI Palaiologos Dragases             20   12

In [5]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

# Export just the scoring columns
scores = df[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']]
scores.to_csv('emperor_scores.csv', index=False)
print("Exported to emperor_scores.csv")

Exported to emperor_scores.csv

In [6]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = pd.read_csv('emperor_scores.csv')

df['Difficulty'] = scores['Difficulty']
df['Effectiveness'] = scores['Effectiveness']

df.to_csv('ERE_List_20260226.csv', index=False)
print("Scores merged back in!")

Scores merged back in!

In [7]:
df

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL,Difficulty,Effectiveness,Local_Image
0,1,Constantine I,Constantine I the Great,Flavius Valerius Constantinus,Constantinian,Constantinus,306,337,31,Sole emperor from 324. Moved the imperial capi...,Co-ruled with Licinius 313-324; sons Constanti...,https://upload.wikimedia.org/wikipedia/commons...,20,10,images/001_.jpg
1,2,Constantius II,Constantius II,Flavius Julius Constantius,Constantinian,Constantinus,337,361,24,Son of Constantine I. Sole emperor from 350. F...,Co-emperor with brothers 337-350; appointed Ju...,https://upload.wikimedia.org/wikipedia/commons...,18,11,images/002_.jpg
2,3,Julian,Julian the Apostate,Flavius Claudius Julianus,Constantinian,Constantinus,361,363,2,Last non-Christian emperor. Attempted to resto...,Caesar under Constantius II from 355; proclaim...,https://upload.wikimedia.org/wikipedia/commons...,18,14,images/003_.jpg
3,4,Jovian,Jovian,Flavius Jovianus,NaN,Non-dynastic,363,364,1,Elected by the army after Julian's death. Made...,Sole emperor; no co-rulers,https://upload.wikimedia.org/wikipedia/commons...,17,5,images/004_.jpg
4,5,Valens,Valens,Flavius Valens,Valentinianic,Valentinianus,364,378,14,"Eastern emperor, brother of Valentinian I. All...",Co-emperor in the east under arrangement with ...,https://upload.wikimedia.org/wikipedia/commons...,16,6,images/005_.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,86,Andronikos IV,Andronikos IV Palaiologos,Andronicus Palaeologus,Palaiologan,Palaiologos,1376,1379,3,Son of John V who rebelled against his father ...,Usurper against his father John V; later recog...,https://upload.wikimedia.org/wikipedia/commons...,11,7,images/087_.png
86,87,John VII,John VII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1390,1390,1,Grandson of John V who briefly seized Constant...,Brief usurper; later legitimate co-emperor and...,https://upload.wikimedia.org/wikipedia/commons...,12,10,images/088_.jpg
87,88,Manuel II,Manuel II Palaiologos,Manuel Palaeologus,Palaiologan,Palaiologos,1391,1425,34,Cultivated and able emperor facing an impossib...,Co-emperor under John V from 1373; made his so...,https://upload.wikimedia.org/wikipedia/commons...,10,10,images/089_.jpg
88,89,John VIII,John VIII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1425,1448,23,Son of Manuel II. Attended the Council of Flor...,Co-emperor under Manuel II from 1421; made his...,https://upload.wikimedia.org/wikipedia/commons...,8,12,images/090_.jpg
89,90,Constantine XI,Constantine XI Palaiologos Dragases,Constantine Palaeologus Dragases,Palaiologan,Palaiologos,1449,1453,4,Last Byzantine emperor. Defended Constantinopl...,Sole emperor at the end; no co-emperor,https://upload.wikimedia.org/wikipedia/commons...,12,20,images/091_.jpg

In [8]:
import pandas as pd
scores = pd.read_csv('emperor_scores.csv')
print(scores[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']].to_string())

    List_Number            Simple_Name_With_Epithets  Difficulty  Effectiveness
0             1              Constantine I the Great          12             20
1             2                       Constantius II           8             12
2             3                  Julian the Apostate          10             10
3             4                               Jovian          12             10
4             5                               Valens          11              7
5             6               Theodosios I the Great          16             16
6             7                             Arkadios           8              5
7             8                        Theodosios II           9             13
8             9                            Markianos          12             12
9            10                   Leo I the Thracian           8             11
10           11                               Leo II           6              8
11           12                                 Zeno          15             16
12           13                           Basiliskos           8              6
13           14                         Anastasios I          10             17
14           15                             Justin I           5             15
15           16                Justinian I the Great           1             15
16           17                            Justin II          11              8
17           18          Tiberios II the Constantine          10             12
18           19                            Maurikios          10             14
19           20                               Phokas          12              1
20           21                           Herakleios          20             17
21           22                      Constantine III          14              8
22           23                           Heraklonas          18              7
23           24                          Constans II          13             13
24           25                       Constantine IV          13             15
25           26               Justinian II Slit-Nose          14              8
26           27                             Leontios           8              4
27           28                         Tiberios III           8              7
28           29                          Philippikos          10              4
29           30                        Anastasios II           9              8
30           31                       Theodosios III          10              5
31           32                 Leo III the Isaurian          20             18
32           33             Constantine V Kopronymos          17             17
33           34                           Artabasdos           8              4
34           35                    Leo IV the Khazar           9             11
35           36                       Constantine VI          10              7
36           37                               Eirene           9             12
37           38                         Nikephoros I           8             12
38           39                           Staurakios          15              4
39           40                   Michael I Rhangabe          10              6
40           41                   Leo V the Armenian          11             13
41           42               Michael II the Amorian          14             11
42           43                           Theophilos          10             12
43           44             Michael III the Drunkard          11             14
44           45               Basil I the Macedonian           7             16
45           46                      Leo VI the Wise           9             15
46           47                            Alexander           9              7
47           48     Constantine VII Porphyrogennetos          12             13
48           49                  Romanos I Lekapenos           4             15
49           50                           Romanos II           6             10
50           51                 Nikephoros II Phokas          10             16
51           52                     John I Tzimiskes           5             16
52           53           Basil II the Bulgar-Slayer           8             19
53           54                     Constantine VIII           6              5
54           55                  Romanos III Argyros           8              6
55           56          Michael IV the Paphlagonian           8             10
56           57                 Michael V Kalaphates           9              4
57           58                  Zoe (with Theodora)           7             10
58           59                             Theodora           7             10
59           60            Constantine IX Monomachos          10             12
60           61                   Michael VI Bringas           9              5
61           62                     Isaac I Komnenos          12             10
62           63                 Constantine X Doukas          11              8
63           64                  Romanos IV Diogenes          17              9
64           65                   Michael VII Doukas          13              6
65           66           Nikephoros III Botaneiates          12              7
66           67                   Alexios I Komnenos          20             18
67           68                     John II Komnenos          12             17
68           69                    Manuel I Komnenos          12             13
69           70                  Alexios II Komnenos          11              6
70           71                Andronikos I Komnenos          11              2
71           72                     Isaac II Angelos          15             10
72           73                  Alexios III Angelos          12              2
73           74                   Alexios IV Angelos          18              2
74           75              Alexios V Mourtzouphlos          20              3
75           76                  Theodore I Laskaris          18             14
76           77             John III Doukas Vatatzes          16             17
77           78                 Theodore II Laskaris          14             12
78           79                     John IV Laskaris          15              5
79           80             Michael VIII Palaiologos          16             16
80           81            Andronikos II Palaiologos          16              4
81           82               Michael IX Palaiologos          14             10
82           83           Andronikos III Palaiologos          15             12
83           84                   John V Palaiologos          17              7
84           85                John VI Kantakouzenos          15              1
85           86            Andronikos IV Palaiologos          16              6
86           87                 John VII Palaiologos          17              5
87           88                Manuel II Palaiologos          18             14
88           89                John VIII Palaiologos          18             11
89           90  Constantine XI Palaiologos Dragases          20             10

In [9]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = pd.read_csv('emperor_scores.csv')

df['Difficulty'] = scores['Difficulty']
df['Effectiveness'] = scores['Effectiveness']

df.to_csv('ERE_List_20260226.csv', index=False)
print("Scores merged back in!")

Scores merged back in!

In [10]:
df

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL,Difficulty,Effectiveness,Local_Image
0,1,Constantine I,Constantine I the Great,Flavius Valerius Constantinus,Constantinian,Constantinus,306,337,31,Sole emperor from 324. Moved the imperial capi...,Co-ruled with Licinius 313-324; sons Constanti...,https://upload.wikimedia.org/wikipedia/commons...,12,20,images/001_.jpg
1,2,Constantius II,Constantius II,Flavius Julius Constantius,Constantinian,Constantinus,337,361,24,Son of Constantine I. Sole emperor from 350. F...,Co-emperor with brothers 337-350; appointed Ju...,https://upload.wikimedia.org/wikipedia/commons...,8,12,images/002_.jpg
2,3,Julian,Julian the Apostate,Flavius Claudius Julianus,Constantinian,Constantinus,361,363,2,Last non-Christian emperor. Attempted to resto...,Caesar under Constantius II from 355; proclaim...,https://upload.wikimedia.org/wikipedia/commons...,10,10,images/003_.jpg
3,4,Jovian,Jovian,Flavius Jovianus,NaN,Non-dynastic,363,364,1,Elected by the army after Julian's death. Made...,Sole emperor; no co-rulers,https://upload.wikimedia.org/wikipedia/commons...,12,10,images/004_.jpg
4,5,Valens,Valens,Flavius Valens,Valentinianic,Valentinianus,364,378,14,"Eastern emperor, brother of Valentinian I. All...",Co-emperor in the east under arrangement with ...,https://upload.wikimedia.org/wikipedia/commons...,11,7,images/005_.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,86,Andronikos IV,Andronikos IV Palaiologos,Andronicus Palaeologus,Palaiologan,Palaiologos,1376,1379,3,Son of John V who rebelled against his father ...,Usurper against his father John V; later recog...,https://upload.wikimedia.org/wikipedia/commons...,16,6,images/087_.png
86,87,John VII,John VII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1390,1390,1,Grandson of John V who briefly seized Constant...,Brief usurper; later legitimate co-emperor and...,https://upload.wikimedia.org/wikipedia/commons...,17,5,images/088_.jpg
87,88,Manuel II,Manuel II Palaiologos,Manuel Palaeologus,Palaiologan,Palaiologos,1391,1425,34,Cultivated and able emperor facing an impossib...,Co-emperor under John V from 1373; made his so...,https://upload.wikimedia.org/wikipedia/commons...,18,14,images/089_.jpg
88,89,John VIII,John VIII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1425,1448,23,Son of Manuel II. Attended the Council of Flor...,Co-emperor under Manuel II from 1421; made his...,https://upload.wikimedia.org/wikipedia/commons...,18,11,images/090_.jpg
89,90,Constantine XI,Constantine XI Palaiologos Dragases,Constantine Palaeologus Dragases,Palaiologan,Palaiologos,1449,1453,4,Last Byzantine emperor. Defended Constantinopl...,Sole emperor at the end; no co-emperor,https://upload.wikimedia.org/wikipedia/commons...,20,10,images/091_.jpg

In [11]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

In [14]:
df.sort_values("Effectiveness")

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL,Difficulty,Effectiveness,Local_Image
84,85,John VI,John VI Kantakouzenos,John Cantacuzenus,Kantakouzenos,Kantakouzenos,1347,1354,7,Aristocrat and general who won the civil war a...,Ruled as senior co-emperor alongside the legit...,https://upload.wikimedia.org/wikipedia/commons...,15,1,images/086_.jpg
19,20,Phokas,Phokas,Flavius Phocas,NaN,Non-dynastic,602,610,8,Low-ranking soldier who led a mutiny against M...,Sole emperor,https://upload.wikimedia.org/wikipedia/commons...,12,1,images/020_.jpg
73,74,Alexios IV,Alexios IV Angelos,Alexius Angelos,Angelid,Angelos,1203,1204,1,Son of Isaac II who invited the Fourth Crusade...,Co-ruled with his father Isaac II,https://upload.wikimedia.org/wikipedia/commons...,18,2,images/075_.png
72,73,Alexios III,Alexios III Angelos,Alexius Angelos,Angelid,Angelos,1195,1203,8,Brother who overthrew Isaac II. Ineffective ru...,Sole emperor,https://upload.wikimedia.org/wikipedia/commons...,12,2,images/073_.png
70,71,Andronikos I,Andronikos I Komnenos,Andronicus Comnenus,Komnenian,Komnenos,1183,1185,2,Last of the Komnenian dynasty. Charismatic adv...,Initially co-emperor with Alexios II before ha...,https://upload.wikimedia.org/wikipedia/commons...,11,2,images/071_.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,77,John III,John III Doukas Vatatzes,John Doukas Vatatzes,Laskarid,Vatatzes,1222,1254,32,Greatest emperor of the Nikaia period. Expande...,Made his son Theodore II co-emperor,https://upload.wikimedia.org/wikipedia/commons...,16,17,images/078_.png
66,67,Alexios I,Alexios I Komnenos,Alexius Comnenus,Komnenian,Komnenos,1081,1118,37,Founded the Komnenian system of government bas...,Made his son John II co-emperor,https://upload.wikimedia.org/wikipedia/commons...,20,18,images/067_.jpg
31,32,Leo III,Leo III the Isaurian,Conon,Isaurian,Leo,717,741,24,Defended Constantinople against the second gre...,Made his son Constantine V co-emperor in 720,https://upload.wikimedia.org/wikipedia/commons...,20,18,images/032_.png
52,53,Basil II,Basil II the Bulgar-Slayer,Basil,Macedonian,Makedon,976,1025,49,Longest-reigning Byzantine emperor. Destroyed ...,Co-emperor from infancy under Nikephoros II an...,https://upload.wikimedia.org/wikipedia/commons...,8,19,images/053_.jpg
0,1,Constantine I,Constantine I the Great,Flavius Valerius Constantinus,Constantinian,Constantinus,306,337,31,Sole emperor from 324. Moved the imperial capi...,Co-ruled with Licinius 313-324; sons Constanti...,https://upload.wikimedia.org/wikipedia/commons...,12,20,images/001_.jpg

In [15]:
df.sort_values('Effectiveness').head(10)

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL,Difficulty,Effectiveness,Local_Image
84,85,John VI,John VI Kantakouzenos,John Cantacuzenus,Kantakouzenos,Kantakouzenos,1347,1354,7,Aristocrat and general who won the civil war a...,Ruled as senior co-emperor alongside the legit...,https://upload.wikimedia.org/wikipedia/commons...,15,1,images/086_.jpg
19,20,Phokas,Phokas,Flavius Phocas,NaN,Non-dynastic,602,610,8,Low-ranking soldier who led a mutiny against M...,Sole emperor,https://upload.wikimedia.org/wikipedia/commons...,12,1,images/020_.jpg
73,74,Alexios IV,Alexios IV Angelos,Alexius Angelos,Angelid,Angelos,1203,1204,1,Son of Isaac II who invited the Fourth Crusade...,Co-ruled with his father Isaac II,https://upload.wikimedia.org/wikipedia/commons...,18,2,images/075_.png
72,73,Alexios III,Alexios III Angelos,Alexius Angelos,Angelid,Angelos,1195,1203,8,Brother who overthrew Isaac II. Ineffective ru...,Sole emperor,https://upload.wikimedia.org/wikipedia/commons...,12,2,images/073_.png
70,71,Andronikos I,Andronikos I Komnenos,Andronicus Comnenus,Komnenian,Komnenos,1183,1185,2,Last of the Komnenian dynasty. Charismatic adv...,Initially co-emperor with Alexios II before ha...,https://upload.wikimedia.org/wikipedia/commons...,11,2,images/071_.jpg
74,75,Alexios V,Alexios V Mourtzouphlos,Alexius Doukas Mourtzouphlos,NaN,Doukas,1204,1204,1,Seized power promising to defend the city agai...,Sole emperor; usurper,https://upload.wikimedia.org/wikipedia/commons...,20,3,images/076_.png
26,27,Leontios,Leontios,Leontius,NaN,Non-dynastic,695,698,3,General who overthrew Justinian II. Himself de...,Sole ruler; usurper,https://upload.wikimedia.org/wikipedia/commons...,8,4,images/027_.png
80,81,Andronikos II,Andronikos II Palaiologos,Andronicus Palaeologus,Palaiologan,Palaiologos,1282,1328,46,"Long reign marked by financial difficulty, the...",Co-emperor under Michael VIII from 1261; made ...,https://upload.wikimedia.org/wikipedia/commons...,16,4,images/082_.png
56,57,Michael V,Michael V Kalaphates,Michael Kalaphates,Macedonian,Paphlagonians,1041,1042,1,"Nephew of Michael IV, adopted by Zoe. Attempte...",Initially co-emperor with empress Zoe; attempt...,https://upload.wikimedia.org/wikipedia/commons...,9,4,images/057_.jpg
38,39,Staurakios,Staurakios,Stauracius,NaN,Non-dynastic,811,811,1,"Son of Nikephoros I, wounded in the same battl...",Co-emperor under Nikephoros I,https://upload.wikimedia.org/wikipedia/commons...,15,4,images/039_.png

In [4]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
print(f"Loaded {len(df)} emperors")

Loaded 90 emperors

In [5]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

scores = df[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']]
scores.to_csv('emperor_scores.csv', index=False)
print("Exported to emperor_scores.csv")

Exported to emperor_scores.csv

In [6]:
import pandas as pd
scores = pd.read_csv('emperor_scores.csv')
print(scores.to_string(index=False))

 List_Number           Simple_Name_With_Epithets  Difficulty  Effectiveness
           1             Constantine I the Great          12             20
           2                      Constantius II           8             12
           3                 Julian the Apostate          10             10
           4                              Jovian          12             10
           5                              Valens          11              7
           6              Theodosios I the Great          16             16
           7                            Arkadios           8              5
           8                       Theodosios II           9             13
           9                           Markianos          12             12
          10                  Leo I the Thracian           8             11
          11                              Leo II           6              8
          12                                Zeno          15             16
          13                          Basiliskos           8              6
          14                        Anastasios I          10             18
          15                            Justin I           5             15
          16               Justinian I the Great           1             15
          17                           Justin II          11              8
          18         Tiberios II the Constantine          10             12
          19                           Maurikios          10             14
          20                              Phokas          14              1
          21                          Herakleios          20             18
          22                     Constantine III          14              8
          23                          Heraklonas          18              7
          24                         Constans II          13             12
          25                      Constantine IV          13             15
          26              Justinian II Slit-Nose          14              8
          27                            Leontios           8              7
          28                        Tiberios III           8              7
          29                         Philippikos          10              4
          30                       Anastasios II           9              8
          31                      Theodosios III          10              5
          32                Leo III the Isaurian          20             18
          33            Constantine V Kopronymos          17             17
          34                          Artabasdos           8              4
          35                   Leo IV the Khazar           9             11
          36                      Constantine VI          10              7
          37                              Eirene           9             12
          38                        Nikephoros I           8             12
          39                          Staurakios          15              4
          40                  Michael I Rhangabe          10              6
          41                  Leo V the Armenian          11             13
          42              Michael II the Amorian          14             11
          43                          Theophilos          10             12
          44            Michael III the Drunkard          11             14
          45              Basil I the Macedonian           7             16
          46                     Leo VI the Wise           6             15
          47                           Alexander           9              7
          48    Constantine VII Porphyrogennetos          12             13
          49                 Romanos I Lekapenos           4             15
          50                          Romanos II           6             10
          51                Nikephoros II Phokas          10             17
          52                    John I Tzimiskes           5             19
          53          Basil II the Bulgar-Slayer           8             20
          54                    Constantine VIII           6              5
          55                 Romanos III Argyros           8              6
          56         Michael IV the Paphlagonian           8             10
          57                Michael V Kalaphates           9              4
          58                 Zoe (with Theodora)           7             10
          59                            Theodora           7             10
          60           Constantine IX Monomachos          10             12
          61                  Michael VI Bringas           9              5
          62                    Isaac I Komnenos          12             10
          63                Constantine X Doukas          11              8
          64                 Romanos IV Diogenes          17              9
          65                  Michael VII Doukas          13              6
          66          Nikephoros III Botaneiates          12              7
          67                  Alexios I Komnenos          20             18
          68                    John II Komnenos          12             17
          69                   Manuel I Komnenos          12             13
          70                 Alexios II Komnenos          11              6
          71               Andronikos I Komnenos          11              2
          72                    Isaac II Angelos          15             10
          73                 Alexios III Angelos          12              2
          74                  Alexios IV Angelos          18              2
          75             Alexios V Mourtzouphlos          20              3
          76                 Theodore I Laskaris          19             14
          77            John III Doukas Vatatzes          16             17
          78                Theodore II Laskaris          14             12
          79                    John IV Laskaris          15              5
          80            Michael VIII Palaiologos          16             16
          81           Andronikos II Palaiologos          18              4
          82              Michael IX Palaiologos          17             10
          83          Andronikos III Palaiologos          18             12
          84                  John V Palaiologos          17              7
          85               John VI Kantakouzenos          19              1
          86           Andronikos IV Palaiologos          17              6
          87                John VII Palaiologos          17              5
          88               Manuel II Palaiologos          18             10
          89               John VIII Palaiologos          18              8
          90 Constantine XI Palaiologos Dragases          20             10

In [7]:
import pandas as pd
scores = pd.read_csv('emperor_scores.csv')
scores.to_clipboard(index=False)
print("Copied to clipboard!")

Copied to clipboard!

In [8]:
df

,List_Number,Simple_Name,Simple_Name_With_Epithets,Full_Name,Broad_Dynasty,Family_Name,Reign_Start,Reign_End,Reign_Length_Years,Summary,Co_Emperor_Notes,Image_URL,Difficulty,Effectiveness,Local_Image
0,1,Constantine I,Constantine I the Great,Flavius Valerius Constantinus,Constantinian,Constantinus,306,337,31,Sole emperor from 324. Moved the imperial capi...,Co-ruled with Licinius 313-324; sons Constanti...,https://upload.wikimedia.org/wikipedia/commons...,12,20,images/001_.jpg
1,2,Constantius II,Constantius II,Flavius Julius Constantius,Constantinian,Constantinus,337,361,24,Son of Constantine I. Sole emperor from 350. F...,Co-emperor with brothers 337-350; appointed Ju...,https://upload.wikimedia.org/wikipedia/commons...,8,12,images/002_.jpg
2,3,Julian,Julian the Apostate,Flavius Claudius Julianus,Constantinian,Constantinus,361,363,2,Last non-Christian emperor. Attempted to resto...,Caesar under Constantius II from 355; proclaim...,https://upload.wikimedia.org/wikipedia/commons...,10,10,images/003_.jpg
3,4,Jovian,Jovian,Flavius Jovianus,NaN,Non-dynastic,363,364,1,Elected by the army after Julian's death. Made...,Sole emperor; no co-rulers,https://upload.wikimedia.org/wikipedia/commons...,12,10,images/004_.jpg
4,5,Valens,Valens,Flavius Valens,Valentinianic,Valentinianus,364,378,14,"Eastern emperor, brother of Valentinian I. All...",Co-emperor in the east under arrangement with ...,https://upload.wikimedia.org/wikipedia/commons...,11,7,images/005_.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,86,Andronikos IV,Andronikos IV Palaiologos,Andronicus Palaeologus,Palaiologan,Palaiologos,1376,1379,3,Son of John V who rebelled against his father ...,Usurper against his father John V; later recog...,https://upload.wikimedia.org/wikipedia/commons...,16,6,images/087_.png
86,87,John VII,John VII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1390,1390,1,Grandson of John V who briefly seized Constant...,Brief usurper; later legitimate co-emperor and...,https://upload.wikimedia.org/wikipedia/commons...,17,5,images/088_.jpg
87,88,Manuel II,Manuel II Palaiologos,Manuel Palaeologus,Palaiologan,Palaiologos,1391,1425,34,Cultivated and able emperor facing an impossib...,Co-emperor under John V from 1373; made his so...,https://upload.wikimedia.org/wikipedia/commons...,18,14,images/089_.jpg
88,89,John VIII,John VIII Palaiologos,John Palaeologus,Palaiologan,Palaiologos,1425,1448,23,Son of Manuel II. Attended the Council of Flor...,Co-emperor under Manuel II from 1421; made his...,https://upload.wikimedia.org/wikipedia/commons...,18,11,images/090_.jpg
89,90,Constantine XI,Constantine XI Palaiologos Dragases,Constantine Palaeologus Dragases,Palaiologan,Palaiologos,1449,1453,4,Last Byzantine emperor. Defended Constantinopl...,Sole emperor at the end; no co-emperor,https://upload.wikimedia.org/wikipedia/commons...,20,10,images/091_.jpg

In [9]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = pd.read_csv('emperor_scores.csv')

df['Difficulty'] = scores['Difficulty']
df['Effectiveness'] = scores['Effectiveness']

df.to_csv('ERE_List_20260226.csv', index=False)
print("Done! Scores updated.")

Done! Scores updated.

In [10]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

df_ranked = df.sort_values('Composite', ascending=False).reset_index(drop=True)

print(f"{'Rank':<5} {'Emperor':<45} {'D':>4} {'E':>4} {'Score':>6}")
print("-" * 65)
for i, row in df_ranked.iterrows():
    print(f"{i+1:<5} {row['Simple_Name_With_Epithets']:<45} {int(row['Difficulty']):>4} {int(row['Effectiveness']):>4} {row['Composite']:>6}")

df.to_csv('ERE_List_20260226.csv', index=False)
print("\nComposite score saved to CSV.")

Rank  Emperor                                          D    E  Score
-----------------------------------------------------------------
1     Herakleios                                      20   18   94.0
2     Alexios I Komnenos                              20   18   94.0
3     Leo III the Isaurian                            20   18   94.0
4     Constantine V Kopronymos                        17   17   85.0
5     Constantine I the Great                         12   20   84.0
6     John III Doukas Vatatzes                        16   17   83.0
7     John II Komnenos                                15   17   81.0
8     Michael VIII Palaiologos                        16   16   80.0
9     Theodosios I the Great                          16   16   80.0
10    Theodore I Laskaris                             19   14   80.0
11    Zeno                                            15   16   78.0
12    Basil II the Bulgar-Slayer                       8   20   76.0
13    Anastasios I                                    10   18   74.0
14    Andronikos III Palaiologos                      18   12   72.0
15    Nikephoros II Phokas                            10   17   71.0
16    Constantine IV                                  13   15   71.0
17    Constantine XI Palaiologos Dragases             20   10   70.0
18    Manuel I Komnenos                               15   13   69.0
19    Manuel II Palaiologos                           18   10   66.0
20    Michael III the Drunkard                        11   14   64.0
21    Theodore II Laskaris                            14   12   64.0
22    John I Tzimiskes                                 5   18   64.0
23    Constantine VII Porphyrogennetos                12   13   63.0
24    Basil I the Macedonian                           7   16   62.0
25    Constans II                                     13   12   62.0
26    Michael II the Amorian                          14   11   61.0
27    Romanos IV Diogenes                             17    9   61.0
28    Leo V the Armenian                              11   13   61.0
29    Markianos                                       12   12   60.0
30    Isaac II Angelos                                15   10   60.0
31    Michael IX Palaiologos                          15   10   60.0
32    John VIII Palaiologos                           18    8   60.0
33    Romanos I Lekapenos                              7   15   59.0
34    Theodosios II                                    9   13   57.0
35    Leo VI the Wise                                  6   15   57.0
36    Constantine IX Monomachos                       10   12   56.0
37    Theophilos                                      10   12   56.0
38    Tiberios II the Constantine                     10   12   56.0
39    John V Palaiologos                              17    7   55.0
40    Eirene                                           9   12   54.0
41    Isaac I Komnenos                                12   10   54.0
42    Jovian                                          12   10   54.0
43    Justinian I the Great                            4   15   53.0
44    Maurikios                                        8   12   52.0
45    Nikephoros I                                     8   12   52.0
46    Constantius II                                   8   12   52.0
47    Andronikos IV Palaiologos                       17    6   52.0
48    Constantine III                                 14    8   52.0
49    Justinian II Slit-Nose                          14    8   52.0
50    Leo IV the Khazar                                9   11   51.0
51    Julian the Apostate                             10   10   50.0
52    Alexios V Mourtzouphlos                         20    3   49.0
53    Heraklonas                                      14    7   49.0
54    Leo I the Thracian                               8   11   49.0
55    Justin I                                         2   15   49.0
56    John VII Palaiologos                            17    5   49.0
57    Andronikos II Palaiologos                       18    4   48.0
58    Michael IV the Paphlagonian                      8   10   46.0
59    Constantine X Doukas                            11    8   46.0
60    Justin II                                       11    8   46.0
61    John IV Laskaris                                15    5   45.0
62    Nikephoros III Botaneiates                      12    7   45.0
63    Zoe (with Theodora)                              7   10   44.0
64    Theodora                                         7   10   44.0
65    Michael VII Doukas                              13    6   44.0
66    Valens                                          11    7   43.0
67    Alexios IV Angelos                              18    2   42.0
68    Staurakios                                      15    4   42.0
69    Romanos II                                       6   10   42.0
70    Anastasios II                                    9    8   42.0
71    Constantine VI                                  10    7   41.0
72    Alexios II Komnenos                             11    6   40.0
73    Alexander                                        9    7   39.0
74    Michael I Rhangabe                              10    6   38.0
75    Leontios                                         8    7   37.0
76    Tiberios III                                     8    7   37.0
77    John VI Kantakouzenos                           17    1   37.0
78    Leo II                                           6    8   36.0
79    Theodosios III                                  10    5   35.0
80    Basiliskos                                       8    6   34.0
81    Romanos III Argyros                              8    6   34.0
82    Michael VI Bringas                               9    5   33.0
83    Philippikos                                     10    4   32.0
84    Arkadios                                         8    5   31.0
85    Michael V Kalaphates                             9    4   30.0
86    Alexios III Angelos                             12    2   30.0
87    Andronikos I Komnenos                           12    2   30.0
88    Artabasdos                                       8    4   28.0
89    Phokas                                          12    1   27.0
90    Constantine VIII                                 1    5   17.0

Composite score saved to CSV.

In [11]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:30, top:45, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10.5), my = sy(10.5);
bg.fillStyle='rgba(44,123,182,0.06)';  bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(212,160,23,0.06)';  bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(192,57,43,0.06)';   bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(100,100,100,0.04)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#ddd'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=1;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=1;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of positions) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [12]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:30, top:45, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((20-d)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10.5), my = sy(10.5);
bg.fillStyle='rgba(44,123,182,0.06)';  bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(212,160,23,0.06)';  bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(192,57,43,0.06)';   bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(100,100,100,0.04)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#ddd'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=1;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=1;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('← Difficulty of Reign', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of positions) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [13]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:30, top:45, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((20-d)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10.5), my = sy(10.5);
bg.fillStyle='rgba(44,123,182,0.06)';  bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(212,160,23,0.06)';  bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(192,57,43,0.06)';   bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(100,100,100,0.04)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#ddd'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=1;i<=20;i+=2) bg.fillText(21-i, sx(21-i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=1;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('← Difficulty of Reign', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Hard + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Easy + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of positions) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [14]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:30, top:45, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10.5), my = sy(10.5);
bg.fillStyle='rgba(44,123,182,0.06)';  bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(212,160,23,0.06)';  bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(192,57,43,0.06)';   bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(100,100,100,0.04)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#ddd'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=1;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=1;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of positions) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [23]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:30, top:45, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(44,123,182,0.06)';  bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(212,160,23,0.06)';  bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(192,57,43,0.06)';   bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(100,100,100,0.04)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#ddd'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=1;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=1;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of positions) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [16]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
df.loc[df['Simple_Name_With_Epithets'] == 'Constantine VIII', 'Effectiveness'] = 10
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [18]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
row = df[df['Simple_Name_With_Epithets'] == 'Andronikos I Komnenos']
print(row[['Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']].to_string())

   Simple_Name_With_Epithets  Difficulty  Effectiveness
70     Andronikos I Komnenos          12              2

In [21]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = df[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']]
scores.to_csv('emperor_scores.csv', index=False)
print("Exported!")

Exported!

In [22]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = pd.read_csv('emperor_scores.csv')
df['Difficulty'] = scores['Difficulty']
df['Effectiveness'] = scores['Effectiveness']
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [46]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:30, top:45, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(44,123,182,0.06)';  bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(212,160,23,0.06)';  bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(192,57,43,0.06)';   bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(100,100,100,0.04)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#ddd'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=1;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=1;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [41]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

print(f"{'#':<4} {'Emperor':<45} {'D':>4} {'E':>4}")
print("-" * 60)
for _, row in df.iterrows():
    print(f"{int(row['List_Number']):<4} {row['Simple_Name_With_Epithets']:<45} {int(row['Difficulty']):>4} {int(row['Effectiveness']):>4}")

#    Emperor                                          D    E
------------------------------------------------------------
1    Constantine I the Great                         11   20
2    Constantius II                                   6   10
3    Julian the Apostate                             10   12
4    Jovian                                          12   10
5    Valens                                          11    7
6    Theodosios I the Great                          16   16
7    Arkadios                                         8    5
8    Theodosios II                                    9   13
9    Markianos                                       12   12
10   Leo I the Thracian                               8   11
11   Leo II                                           6    8
12   Zeno                                            15   16
13   Basiliskos                                       8    6
14   Anastasios I                                    10   18
15   Justin I                                         2   15
16   Justinian I the Great                            4   15
17   Justin II                                       11    8
18   Tiberios II the Constantine                     10   10
19   Maurikios                                        8   12
20   Phokas                                           4    1
21   Herakleios                                      20   18
22   Constantine III                                 14    8
23   Heraklonas                                      14    7
24   Constans II                                     13   12
25   Constantine IV                                  13   15
26   Justinian II Slit-Nose                          14    8
27   Leontios                                         8    7
28   Tiberios III                                     8    7
29   Philippikos                                     10    4
30   Anastasios II                                    9    8
31   Theodosios III                                  10    5
32   Leo III the Isaurian                            20   18
33   Constantine V Kopronymos                        17   17
34   Artabasdos                                       8    4
35   Leo IV the Khazar                                9   11
36   Constantine VI                                  10    7
37   Eirene                                           9   12
38   Nikephoros I                                     8   12
39   Staurakios                                      17    4
40   Michael I Rhangabe                              10    6
41   Leo V the Armenian                              11   13
42   Michael II the Amorian                          14   10
43   Theophilos                                      10   12
44   Michael III the Drunkard                        11    9
45   Basil I the Macedonian                           7   15
46   Leo VI the Wise                                  6   16
47   Alexander                                        9    7
48   Constantine VII Porphyrogennetos                 9   12
49   Romanos I Lekapenos                              7   15
50   Romanos II                                       6   10
51   Nikephoros II Phokas                            10   17
52   John I Tzimiskes                                 5   18
53   Basil II the Bulgar-Slayer                       8   20
54   Constantine VIII                                 1   11
55   Romanos III Argyros                              2    6
56   Michael IV the Paphlagonian                      3   10
57   Michael V Kalaphates                             3    4
58   Zoe (with Theodora)                              7   10
59   Theodora                                         7   10
60   Constantine IX Monomachos                       10   12
61   Michael VI Bringas                               9    5
62   Isaac I Komnenos                                12   10
63   Constantine X Doukas                            11    8
64   Romanos IV Diogenes                             17    9
65   Michael VII Doukas                              13    6
66   Nikephoros III Botaneiates                      12    7
67   Alexios I Komnenos                              20   18
68   John II Komnenos                                12   17
69   Manuel I Komnenos                               10   13
70   Alexios II Komnenos                              8    6
71   Andronikos I Komnenos                            5    2
72   Isaac II Angelos                                15   10
73   Alexios III Angelos                             12    2
74   Alexios IV Angelos                              18    2
75   Alexios V Mourtzouphlos                         20    3
76   Theodore I Laskaris                             19   14
77   John III Doukas Vatatzes                        16   17
78   Theodore II Laskaris                            14   12
79   John IV Laskaris                                15    5
80   Michael VIII Palaiologos                        16   16
81   Andronikos II Palaiologos                       18    4
82   Michael IX Palaiologos                          15   10
83   Andronikos III Palaiologos                      18   12
84   John V Palaiologos                              17    7
85   John VI Kantakouzenos                           17    1
86   Andronikos IV Palaiologos                       17    6
87   John VII Palaiologos                            17    5
88   Manuel II Palaiologos                           18   10
89   John VIII Palaiologos                           18    8
90   Constantine XI Palaiologos Dragases             20   10

In [33]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

df.loc[df['Simple_Name_With_Epithets'] == 'Phokas', 'Difficulty'] = 3
df.loc[df['Simple_Name_With_Epithets'] == 'Andronikos I Komnenos', 'Difficulty'] = 7

df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [34]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = pd.read_csv('emperor_scores.csv')
df['Difficulty'] = scores['Difficulty']
df['Effectiveness'] = scores['Effectiveness']
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [36]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = pd.read_csv('emperor_scores.csv')
df['Difficulty'] = scores['Difficulty']
df['Effectiveness'] = scores['Effectiveness']
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [38]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = pd.read_csv('emperor_scores.csv')
df['Difficulty'] = scores['Difficulty']
df['Effectiveness'] = scores['Effectiveness']
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [40]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
df.loc[df['Simple_Name_With_Epithets'] == 'Phokas', 'Difficulty'] = 4
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [43]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = df[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']]
scores.to_csv('emperor_scores.csv', index=False)
print("Exported!")

PermissionError: [Errno 13] Permission denied: 'emperor_scores.csv'

In [44]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = pd.read_csv('emperor_scores.csv')
df['Difficulty'] = scores['Difficulty']
df['Effectiveness'] = scores['Effectiveness']
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [45]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
df.loc[df['Simple_Name_With_Epithets'] == 'Constantine XI Palaiologos Dragases', 'Effectiveness'] = 12
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [47]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:30, top:45, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

// Add jitter to separate overlapping emperors
function jitter(val, amount=0.4) {{
  return val + (Math.random() - 0.5) * amount * 2;
}}

function sx(d) {{ return PAD.left + ((jitter(d)-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((jitter(e)-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(44,123,182,0.06)';  bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(212,160,23,0.06)';  bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(192,57,43,0.06)';   bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(100,100,100,0.04)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#ddd'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=1;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=1;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Zoom and pan
let scale = 1, panX = 0, panY = 0, isPanning = false, startX, startY;

const fgEl = document.getElementById('fg');
const bgEl = document.getElementById('bg');

function applyTransform() {{
  const t = `translate(${{panX}}px, ${{panY}}px) scale(${{scale}})`;
  fgEl.style.transform = t;
  bgEl.style.transform = t;
  fgEl.style.transformOrigin = '0 0';
  bgEl.style.transformOrigin = '0 0';
}}

fgEl.addEventListener('wheel', function(e) {{
  e.preventDefault();
  const delta = e.deltaY > 0 ? 0.9 : 1.1;
  const rect = fgEl.getBoundingClientRect();
  const mx = e.clientX - rect.left;
  const my = e.clientY - rect.top;
  panX -= mx * (delta - 1);
  panY -= my * (delta - 1);
  scale *= delta;
  scale = Math.max(0.5, Math.min(5, scale));
  applyTransform();
}}, {{ passive: false }});

fgEl.addEventListener('mousedown', function(e) {{
  isPanning = true;
  startX = e.clientX - panX;
  startY = e.clientY - panY;
  fgEl.style.cursor = 'grabbing';
}});

window.addEventListener('mousemove', function(e) {{
  if (!isPanning) return;
  panX = e.clientX - startX;
  panY = e.clientY - startY;
  applyTransform();
}});

window.addEventListener('mouseup', function() {{
  isPanning = false;
  fgEl.style.cursor = 'default';
}});

// Reset zoom on double click
fgEl.addEventListener('dblclick', function() {{
  scale = 1; panX = 0; panY = 0;
  applyTransform();
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [55]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Byzantine Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Byzantine Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:30, top:45, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(44,123,182,0.06)';  bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(212,160,23,0.06)';  bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(192,57,43,0.06)';   bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(100,100,100,0.04)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#ddd'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=1;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=1;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [49]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = df[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']]
scores.to_csv('emperor_scores.csv', index=False)
print("Exported!")

Exported!

In [50]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = pd.read_csv('emperor_scores.csv')
df['Difficulty'] = scores['Difficulty']
df['Effectiveness'] = scores['Effectiveness']
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [53]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = df[['List_Number', 'Simple_Name_With_Epithets', 'Difficulty', 'Effectiveness']]
scores.to_csv('emperor_scores.csv', index=False)
print("Exported!")

Exported!

In [54]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
scores = pd.read_csv('emperor_scores.csv')
df['Difficulty'] = scores['Difficulty']
df['Effectiveness'] = scores['Effectiveness']
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [56]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(44,123,182,0.06)';  bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(212,160,23,0.06)';  bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(192,57,43,0.06)';   bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(100,100,100,0.04)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#ddd'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=1;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=1;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [57]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,200,0,0.12)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,180,0,0.12)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(200,0,0,0.12)';     bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - red
bg.fillStyle='rgba(150,150,150,0.10)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#ddd'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [58]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#bbb'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [59]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v2.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v2.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v2.html in your browser.

In [60]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [61]:
import requests
import time

session = requests.Session()
session.headers.update({
    'User-Agent': 'ByzantineEmperorsTool/1.0 (educational project; ecocinar@gmail.com)'
})

# Test with 5 well known emperors and their Wikipedia page titles
TEST_EMPERORS = [
    ("Basil II the Bulgar-Slayer",    "Basil II"),
    ("Justinian I the Great",         "Justinian I"),
    ("Constantine I the Great",       "Constantine the Great"),
    ("Alexios I Komnenos",            "Alexios I Komnenos"),
    ("Herakleios",                    "Heraclius"),
]

def get_page_length(title):
    """Get Wikipedia article length in bytes."""
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "titles": title,
        "prop": "revisions",
        "rvprop": "size",
        "format": "json"
    }
    try:
        r = session.get(url, params=params, timeout=10)
        pages = r.json()['query']['pages']
        for page in pages.values():
            return page['revisions'][0]['size']
    except:
        return 0

def get_page_views(title):
    """Get average daily Wikipedia page views for last 30 days."""
    url = f"https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/all-agents/{title.replace(' ','_')}/daily/20250101/20250131"
    try:
        r = session.get(url, timeout=10)
        items = r.json().get('items', [])
        if items:
            return int(sum(i['views'] for i in items) / len(items))
        return 0
    except:
        return 0

print(f"{'Emperor':<40} {'Page Length':>12} {'Avg Daily Views':>15}")
print("-" * 70)

for name, wiki_title in TEST_EMPERORS:
    length = get_page_length(wiki_title)
    views  = get_page_views(wiki_title)
    print(f"{name:<40} {length:>12,} {views:>15,}")
    time.sleep(1)

Emperor                                   Page Length Avg Daily Views
----------------------------------------------------------------------
Basil II the Bulgar-Slayer                     80,680             925
Justinian I the Great                         102,537           2,377
Constantine I the Great                       180,856           4,576
Alexios I Komnenos                             42,197             643
Herakleios                                     62,599             992

In [62]:
import pandas as pd
import requests
import time

df = pd.read_csv('ERE_List_20260226.csv')

session = requests.Session()
session.headers.update({
    'User-Agent': 'ByzantineEmperorsTool/1.0 (educational project; ecocinar@gmail.com)'
})

# Manual Wikipedia title overrides where the name won't match automatically
WIKI_TITLES = {
    'Constantine I the Great':          'Constantine the Great',
    'Justinian I the Great':            'Justinian I',
    'Theodosios I the Great':           'Theodosius I',
    'Theodosios II':                    'Theodosius II',
    'Markianos':                        'Marcian',
    'Anastasios I':                     'Anastasius I Dicorus',
    'Herakleios':                       'Heraclius',
    'Constantine III':                  'Constantine III (emperor)',
    'Heraklonas':                       'Heraclonas',
    'Constans II':                      'Constans II',
    'Constantine IV':                   'Constantine IV',
    'Justinian II Slit-Nose':           'Justinian II',
    'Leontios':                         'Leontius (emperor)',
    'Tiberios II the Constantine':      'Tiberius II Constantine',
    'Tiberios III':                     'Tiberius III',
    'Leo III the Isaurian':             'Leo III the Isaurian',
    'Constantine V Kopronymos':         'Constantine V',
    'Leo IV the Khazar':                'Leo IV the Khazar',
    'Nikephoros I':                     'Nikephoros I',
    'Michael I Rhangabe':               'Michael I Rhangabe',
    'Leo V the Armenian':               'Leo V the Armenian',
    'Michael II the Amorian':           'Michael II',
    'Michael III the Drunkard':         'Michael III',
    'Basil I the Macedonian':           'Basil I',
    'Leo VI the Wise':                  'Leo VI the Wise',
    'Constantine VII Porphyrogennetos': 'Constantine VII',
    'Romanos I Lekapenos':              'Romanos I Lekapenos',
    'Nikephoros II Phokas':             'Nikephoros II Phokas',
    'John I Tzimiskes':                 'John I Tzimiskes',
    'Basil II the Bulgar-Slayer':       'Basil II',
    'Romanos III Argyros':              'Romanos III',
    'Michael IV the Paphlagonian':      'Michael IV',
    'Michael V Kalaphates':             'Michael V',
    'Zoe (with Theodora)':              'Zoe (empress)',
    'Constantine IX Monomachos':        'Constantine IX',
    'Isaac I Komnenos':                 'Isaac I Komnenos',
    'Constantine X Doukas':             'Constantine X',
    'Romanos IV Diogenes':              'Romanos IV Diogenes',
    'Michael VII Doukas':               'Michael VII Doukas',
    'Nikephoros III Botaneiates':       'Nikephoros III',
    'Alexios I Komnenos':               'Alexios I Komnenos',
    'John II Komnenos':                 'John II Komnenos',
    'Manuel I Komnenos':                'Manuel I Komnenos',
    'Alexios II Komnenos':              'Alexios II Komnenos',
    'Andronikos I Komnenos':            'Andronikos I Komnenos',
    'Isaac II Angelos':                 'Isaac II Angelos',
    'Alexios III Angelos':              'Alexios III Angelos',
    'Alexios IV Angelos':               'Alexios IV Angelos',
    'Alexios V Mourtzouphlos':          'Alexios V Doukas',
    'Theodore I Laskaris':              'Theodore I Laskaris',
    'John III Doukas Vatatzes':         'John III Doukas Vatatzes',
    'Theodore II Laskaris':             'Theodore II Laskaris',
    'John IV Laskaris':                 'John IV Laskaris',
    'Michael VIII Palaiologos':         'Michael VIII Palaiologos',
    'Andronikos II Palaiologos':        'Andronikos II Palaiologos',
    'Michael IX Palaiologos':           'Michael IX Palaiologos',
    'Andronikos III Palaiologos':       'Andronikos III Palaiologos',
    'John V Palaiologos':               'John V Palaiologos',
    'John VI Kantakouzenos':            'John VI Kantakouzenos',
    'Andronikos IV Palaiologos':        'Andronikos IV Palaiologos',
    'John VII Palaiologos':             'John VII Palaiologos',
    'Manuel II Palaiologos':            'Manuel II Palaiologos',
    'John VIII Palaiologos':            'John VIII Palaiologos',
    'Constantine XI Palaiologos Dragases': 'Constantine XI',
}

def get_page_length(title):
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "titles": title,
        "prop": "revisions",
        "rvprop": "size",
        "format": "json"
    }
    try:
        r = session.get(url, params=params, timeout=10)
        pages = r.json()['query']['pages']
        for page in pages.values():
            return page['revisions'][0]['size']
    except:
        return 0

def get_page_views(title):
    url = f"https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/all-agents/{title.replace(' ','_')}/daily/20250101/20250131"
    try:
        r = session.get(url, timeout=10)
        items = r.json().get('items', [])
        if items:
            return int(sum(i['views'] for i in items) / len(items))
        return 0
    except:
        return 0

print("Fetching Wikipedia metrics...\n")
print(f"{'#':<4} {'Emperor':<45} {'Length':>8} {'Views':>8}")
print("-" * 70)

lengths = []
views = []

for _, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    wiki_title = WIKI_TITLES.get(name, name)
    
    length = get_page_length(wiki_title)
    view   = get_page_views(wiki_title)
    
    lengths.append(length)
    views.append(view)
    
    print(f"{int(row['List_Number']):<4} {name:<45} {length:>8,} {view:>8,}")
    time.sleep(0.8)

df['Wiki_Length'] = lengths
df['Wiki_Views']  = views
df.to_csv('ERE_List_20260226.csv', index=False)

print("\nDone! Wiki metrics saved to CSV.")
print("\nTop 15 by combined rank:")

df['Length_Rank'] = df['Wiki_Length'].rank(ascending=False)
df['Views_Rank']  = df['Wiki_Views'].rank(ascending=False)
df['Wiki_Score']  = (df['Length_Rank'] + df['Views_Rank']) / 2
top15 = df.nsmallest(15, 'Wiki_Score')[['Simple_Name_With_Epithets', 'Wiki_Length', 'Wiki_Views', 'Wiki_Score']]
print(top15.to_string(index=False))
df.to_csv('ERE_List_20260226.csv', index=False)

Fetching Wikipedia metrics...

#    Emperor                                         Length    Views
----------------------------------------------------------------------
1    Constantine I the Great                        180,856    4,576
2    Constantius II                                  68,764      716
3    Julian the Apostate                                 58      128
4    Jovian                                             909       35
5    Valens                                          47,541      477
6    Theodosios I the Great                         106,066    1,489
7    Arkadios                                             0        0
8    Theodosios II                                   31,727      490
9    Markianos                                       61,167      322
10   Leo I the Thracian                                  76       32
11   Leo II                                             776        3
12   Zeno                                             2,519       54
13   Basiliskos                                          24        1
14   Anastasios I                                    32,657      334
15   Justin I                                        33,397      362
16   Justinian I the Great                          102,537    2,377
17   Justin II                                       24,994      323
18   Tiberios II the Constantine                     29,573      226
19   Maurikios                                           28        1
20   Phokas                                              20        1
21   Herakleios                                      62,599      992
22   Constantine III                                     29        1
23   Heraklonas                                      22,587      156
24   Constans II                                     31,588      257
25   Constantine IV                                  26,763      231
26   Justinian II Slit-Nose                          29,783      473
27   Leontios                                            22        1
28   Tiberios III                                    22,784      119
29   Philippikos                                         25        4
30   Anastasios II                                      116       11
31   Theodosios III                                      93        3
32   Leo III the Isaurian                            38,065      387
33   Constantine V Kopronymos                        41,816      267
34   Artabasdos                                       7,880       44
35   Leo IV the Khazar                                8,271      181
36   Constantine VI                                  15,888      210
37   Eirene                                             642        7
38   Nikephoros I                                    18,726      255
39   Staurakios                                      37,736      129
40   Michael I Rhangabe                                  94       12
41   Leo V the Armenian                              30,553      175
42   Michael II the Amorian                          22,740      178
43   Theophilos                                          23        1
44   Michael III the Drunkard                        33,900      262
45   Basil I the Macedonian                          34,684      403
46   Leo VI the Wise                                 24,765      285
47   Alexander                                       34,728      775
48   Constantine VII Porphyrogennetos                27,033      544
49   Romanos I Lekapenos                             34,319      189
50   Romanos II                                      13,126      240
51   Nikephoros II Phokas                            38,975      300
52   John I Tzimiskes                                18,449      264
53   Basil II the Bulgar-Slayer                      80,680      925
54   Constantine VIII                                16,719      223
55   Romanos III Argyros                                 52       17
56   Michael IV the Paphlagonian                        249        2
57   Michael V Kalaphates                               356        6
58   Zoe (with Theodora)                                 32       12
59   Theodora                                         3,404       27
60   Constantine IX Monomachos                           39       77
61   Michael VI Bringas                               6,898      111
62   Isaac I Komnenos                                31,977      172
63   Constantine X Doukas                                34        9
64   Romanos IV Diogenes                             38,779      293
65   Michael VII Doukas                              19,317      170
66   Nikephoros III Botaneiates                          40        7
67   Alexios I Komnenos                              42,197      643
68   John II Komnenos                                55,659      314
69   Manuel I Komnenos                               83,212      436
70   Alexios II Komnenos                             10,924      160
71   Andronikos I Komnenos                           52,079      375
72   Isaac II Angelos                                23,251      257
73   Alexios III Angelos                             14,993      171
74   Alexios IV Angelos                              11,003      121
75   Alexios V Mourtzouphlos                         18,936      165
76   Theodore I Laskaris                             43,970      149
77   John III Doukas Vatatzes                        27,944      112
78   Theodore II Laskaris                            55,467      104
79   John IV Laskaris                                    84      126
80   Michael VIII Palaiologos                        44,635      314
81   Andronikos II Palaiologos                       31,721      250
82   Michael IX Palaiologos                          46,370       71
83   Andronikos III Palaiologos                      18,528      187
84   John V Palaiologos                              17,194      248
85   John VI Kantakouzenos                           18,927      153
86   Andronikos IV Palaiologos                        9,994       93
87   John VII Palaiologos                            49,889       75
88   Manuel II Palaiologos                           31,002      285
89   John VIII Palaiologos                           12,033      275
90   Constantine XI Palaiologos Dragases                 40       44

Done! Wiki metrics saved to CSV.

Top 15 by combined rank:
 Simple_Name_With_Epithets  Wiki_Length  Wiki_Views  Wiki_Score
   Constantine I the Great       180856        4576        1.00
    Theodosios I the Great       106066        1489        2.50
     Justinian I the Great       102537        2377        2.50
Basil II the Bulgar-Slayer        80680         925        5.00
                Herakleios        62599         992        5.50
            Constantius II        68764         716        6.50
         Manuel I Komnenos        83212         436        8.50
                    Valens        47541         477       12.00
        Alexios I Komnenos        42197         643       12.50
     Andronikos I Komnenos        52079         375       13.50
                 Markianos        61167         322       14.00
                 Alexander        34728         775       14.50
          John II Komnenos        55659         314       15.25
      Leo III the Isaurian        38065         387       18.00
  Michael VIII Palaiologos        44635         314       18.25

In [63]:
import pandas as pd
import requests
import time

df = pd.read_csv('ERE_List_20260226.csv')

session = requests.Session()
session.headers.update({
    'User-Agent': 'ByzantineEmperorsTool/1.0 (educational project; ecocinar@gmail.com)'
})

# Fixed title mappings for problem entries
FIXES = {
    'Julian the Apostate':            'Julian (emperor)',
    'Arkadios':                       'Arcadius',
    'Leo I the Thracian':             'Leo I (emperor)',
    'Maurikios':                      'Maurice (emperor)',
    'Phokas':                         'Phocas',
    'Leontios':                       'Leontius (emperor)',
    'Theophilos':                     'Theophilos (emperor)',
    'Eirene':                         'Irene of Athens',
    'Constantine XI Palaiologos Dragases': 'Constantine XI',
    'Romanos III Argyros':            'Romanos III',
    'Zoe (with Theodora)':            'Zoe (empress)',
    'Constantine IX Monomachos':      'Constantine IX',
    'Michael I Rhangabe':             'Michael I of Bulgaria',
    'Anastasios II':                  'Anastasius II',
    'Theodosios III':                 'Theodosius III',
    'Basiliskos':                     'Basiliscus',
    'Philippikos':                    'Philippicus',
    'Constantine X Doukas':           'Constantine X Doukas',
    'Nikephoros III Botaneiates':     'Nikephoros III Botaneiates',
    'Michael IV the Paphlagonian':    'Michael IV the Paphlagonian',
    'Michael V Kalaphates':           'Michael V',
    'Michael VI Bringas':             'Michael VI Bringas',
    'Constantine III':                'Constantine III (Byzantine emperor)',
    'John IV Laskaris':               'John IV Laskaris',
}

def get_page_length(title):
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "titles": title,
        "prop": "revisions",
        "rvprop": "size",
        "format": "json"
    }
    try:
        r = session.get(url, params=params, timeout=10)
        pages = r.json()['query']['pages']
        for page in pages.values():
            return page['revisions'][0]['size']
    except:
        return 0

def get_page_views(title):
    url = f"https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/all-agents/{title.replace(' ','_')}/daily/20250101/20250131"
    try:
        r = session.get(url, timeout=10)
        items = r.json().get('items', [])
        if items:
            return int(sum(i['views'] for i in items) / len(items))
        return 0
    except:
        return 0

print("Fixing problem entries...\n")
print(f"{'Emperor':<45} {'Length':>8} {'Views':>8}")
print("-" * 65)

for _, row in df.iterrows():
    name = row['Simple_Name_With_Epithets']
    if name not in FIXES:
        continue
    
    wiki_title = FIXES[name]
    length = get_page_length(wiki_title)
    views  = get_page_views(wiki_title)
    
    df.loc[df['Simple_Name_With_Epithets'] == name, 'Wiki_Length'] = length
    df.loc[df['Simple_Name_With_Epithets'] == name, 'Wiki_Views']  = views
    
    print(f"{name:<45} {length:>8,} {views:>8,}")
    time.sleep(0.8)

df.to_csv('ERE_List_20260226.csv', index=False)

# Recalculate top 15
df['Length_Rank'] = df['Wiki_Length'].rank(ascending=False)
df['Views_Rank']  = df['Wiki_Views'].rank(ascending=False)
df['Wiki_Score']  = (df['Length_Rank'] + df['Views_Rank']) / 2
top15 = df.nsmallest(15, 'Wiki_Score')[['Simple_Name_With_Epithets', 'Wiki_Length', 'Wiki_Views', 'Wiki_Score']]

print("\nDone! Updated top 15:")
print(top15.to_string(index=False))
df.to_csv('ERE_List_20260226.csv', index=False)

Fixing problem entries...

Emperor                                         Length    Views
-----------------------------------------------------------------
Julian the Apostate                            110,060    1,170
Arkadios                                        33,009      398
Leo I the Thracian                              21,048      332
Basiliskos                                      55,466      227
Maurikios                                       46,871      384
Phokas                                          23,627      356
Constantine III                                    110       55
Leontios                                            22        1
Philippikos                                      9,990      114
Anastasios II                                      345        4
Theodosios III                                  21,522      135
Eirene                                          49,127      442
Michael I Rhangabe                                   0        0
Theophilos                                      33,533      184
Romanos III Argyros                                 52       17
Michael IV the Paphlagonian                     17,534      197
Michael V Kalaphates                               356        6
Zoe (with Theodora)                                 32       12
Constantine IX Monomachos                           39       77
Michael VI Bringas                               6,898      111
Constantine X Doukas                            10,580      163
Nikephoros III Botaneiates                      51,900      147
John IV Laskaris                                    84      126
Constantine XI Palaiologos Dragases                 40       44

Done! Updated top 15:
 Simple_Name_With_Epithets  Wiki_Length  Wiki_Views  Wiki_Score
   Constantine I the Great       180856        4576         1.0
       Julian the Apostate       110060        1170         3.0
    Theodosios I the Great       106066        1489         3.0
     Justinian I the Great       102537        2377         3.0
Basil II the Bulgar-Slayer        80680         925         6.0
                Herakleios        62599         992         6.5
            Constantius II        68764         716         7.5
         Manuel I Komnenos        83212         436        10.0
                    Valens        47541         477        14.5
                    Eirene        49127         442        15.0
        Alexios I Komnenos        42197         643        15.5
     Andronikos I Komnenos        52079         375        16.5
                 Markianos        61167         322        17.5
                 Alexander        34728         775        17.5
                 Maurikios        46871         384        18.5

In [64]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

df['Length_Rank'] = df['Wiki_Length'].rank(ascending=False)
df['Views_Rank']  = df['Wiki_Views'].rank(ascending=False)
df['Wiki_Score']  = (df['Length_Rank'] + df['Views_Rank']) / 2

top20 = df.nsmallest(20, 'Wiki_Score')[['List_Number', 'Simple_Name_With_Epithets', 'Wiki_Length', 'Wiki_Views', 'Wiki_Score']]
print(top20.to_string(index=False))

 List_Number  Simple_Name_With_Epithets  Wiki_Length  Wiki_Views  Wiki_Score
           1    Constantine I the Great       180856        4576        1.00
           3        Julian the Apostate       110060        1170        3.00
           6     Theodosios I the Great       106066        1489        3.00
          16      Justinian I the Great       102537        2377        3.00
          53 Basil II the Bulgar-Slayer        80680         925        6.00
          21                 Herakleios        62599         992        6.50
           2             Constantius II        68764         716        7.50
          69          Manuel I Komnenos        83212         436       10.00
           5                     Valens        47541         477       14.50
          37                     Eirene        49127         442       15.00
          67         Alexios I Komnenos        42197         643       15.50
          71      Andronikos I Komnenos        52079         375       16.50
           9                  Markianos        61167         322       17.50
          47                  Alexander        34728         775       17.50
          19                  Maurikios        46871         384       18.50
          68           John II Komnenos        55659         314       18.75
          32       Leo III the Isaurian        38065         387       22.00
          45     Basil I the Macedonian        34684         403       22.50
          80   Michael VIII Palaiologos        44635         314       23.75
           8              Theodosios II        31727         490       24.00

In [65]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

print("Top 10 by Page Length:")
print("-" * 60)
top_length = df.nlargest(10, 'Wiki_Length')[['Simple_Name_With_Epithets', 'Wiki_Length']]
print(top_length.to_string(index=False))

print("\nTop 10 by Page Views:")
print("-" * 60)
top_views = df.nlargest(10, 'Wiki_Views')[['Simple_Name_With_Epithets', 'Wiki_Views']]
print(top_views.to_string(index=False))

Top 10 by Page Length:
------------------------------------------------------------
 Simple_Name_With_Epithets  Wiki_Length
   Constantine I the Great       180856
       Julian the Apostate       110060
    Theodosios I the Great       106066
     Justinian I the Great       102537
         Manuel I Komnenos        83212
Basil II the Bulgar-Slayer        80680
            Constantius II        68764
                Herakleios        62599
                 Markianos        61167
          John II Komnenos        55659

Top 10 by Page Views:
------------------------------------------------------------
       Simple_Name_With_Epithets  Wiki_Views
         Constantine I the Great        4576
           Justinian I the Great        2377
          Theodosios I the Great        1489
             Julian the Apostate        1170
                      Herakleios         992
      Basil II the Bulgar-Slayer         925
                       Alexander         775
                  Constantius II         716
              Alexios I Komnenos         643
Constantine VII Porphyrogennetos         544

In [66]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label === 'notable') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [68]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for top and bottom 5</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        // Semi-transparent overlay
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // Name text
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        fg.fillStyle='#fff';
        fg.font = `bold ${{Math.max(8, Math.min(11, r*0.35))}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [69]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for most notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.beginPath(); bg.moveTo(PAD.left,PAD.top); bg.lineTo(PAD.left,PAD.top+plotH); bg.lineTo(PAD.left+plotW,PAD.top+plotH); bg.stroke();

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign = 'center';
        const tw = fg.measureText(shortName).width;
        // Dark overlay behind text
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // White text
        fg.fillStyle='#fff';
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [70]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes and border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('← Effectiveness', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign = 'center';
        const tw = fg.measureText(shortName).width;
        // Dark overlay behind text
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // White text
        fg.fillStyle='#fff';
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [71]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes and border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia';
bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Watermark
bg.fillStyle='rgba(0,0,0,0.15)';
bg.font='italic 12px Georgia';
bg.textAlign='right';
bg.fillText('Created by Eric Cook', PAD.left+plotW-8, PAD.top+plotH-8);
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign = 'center';
        const tw = fg.measureText(shortName).width;
        // Dark overlay behind text
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // White text
        fg.fillStyle='#fff';
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [73]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Identify top 5 and bottom 5 by composite score
top5 = set(df.nlargest(5, 'Composite')['List_Number'].tolist())
bot5 = set(df.nsmallest(5, 'Composite')['List_Number'].tolist())

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 24px;
    padding: 14px;
    flex-wrap: wrap;
    font-size: 0.78em;
    color: #555;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes and border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia';
bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Watermark
bg.fillStyle='rgba(0,0,0,0.15)';
bg.font='italic 12px Georgia';
bg.textAlign='right';
bg.fillText('Created by Eric Cook', PAD.left+plotW-8, PAD.top+plotH-8);
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign = 'center';
        const tw = fg.measureText(shortName).width;
        // Dark overlay behind text
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // White text
        fg.fillStyle='#fff';
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [74]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors defined by name

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 12px;
    padding: 10px 40px;
    flex-wrap: wrap;
    font-size: 0.75em;
    color: #555;
    max-width: 700px;
    margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes and border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia';
bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia';
bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign = 'center';
        const tw = fg.measureText(shortName).width;
        // Dark overlay behind text
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // White text
        fg.fillStyle='#fff';
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [77]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors defined by name

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
max_years = df['Reign_Length_Years'].max()

for _, row in df.iterrows():
    num = int(row['List_Number'])
    label_type = 'top' if num in top5 else ('bot' if num in bot5 else 'none')
    emperors.append({
        "num":        num,
        "name":       str(row['Simple_Name_With_Epithets']),
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      label_type,
    })
    print(f"  Embedding #{num}: {row['Simple_Name_With_Epithets']}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #f8f5ef;
    color: #222;
    font-family: 'Georgia', serif;
  }}
  h1 {{
    text-align: center;
    color: #8b1a1a;
    font-size: 1.9em;
    padding: 24px 20px 4px;
    letter-spacing: 1px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    font-size: 0.85em;
    padding-bottom: 16px;
  }}
  #chart-wrap {{
    position: relative;
    width: 960px;
    height: 720px;
    margin: 0 auto;
  }}
  canvas {{
    position: absolute;
    top: 0; left: 0;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(255,252,245,0.98);
    border: 1px solid #8b1a1a;
    border-radius: 6px;
    padding: 12px;
    pointer-events: none;
    display: none;
    max-width: 290px;
    z-index: 100;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{
    width: 75px;
    height: 95px;
    object-fit: cover;
    border-radius: 4px;
    float: left;
    margin-right: 10px;
  }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex;
    justify-content: center;
    gap: 12px;
    padding: 10px 40px;
    flex-wrap: wrap;
    font-size: 0.75em;
    color: #555;
    max-width: 700px;
    margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{
    text-align: center;
    font-size: 0.75em;
    color: #888;
    padding-bottom: 20px;
  }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:65}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}
const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

// Background canvas
const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);        // top left - yellow
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);         // top right - green
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);        // bottom left - soft red
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);        // bottom right - grey

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Axes and border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia';
bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia';
bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Foreground canvas — draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  // Ring
  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      // Overlay name for top/bottom 5
      if(emp.label !== 'none') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign = 'center';
        const tw = fg.measureText(shortName).width;
        // Dark overlay behind text
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        // White text
        fg.fillStyle='#fff';
        fg.font = `bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    // Fallback circle
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    fg.fillStyle='#8b1a1a'; fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
    fg.textAlign='center'; fg.fillText(emp.name.charAt(0), cx, cy+4);
    if(emp.label !== 'none') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.fillText(shortName, cx, cy+3);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r - b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [78]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Constantius II',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Michael VIII Palaiologos',
    'Constantine XI Palaiologos Dragases',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

emperors = []
for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative; width: 960px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [14]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Constantius II',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Michael VIII Palaiologos',
    'Constantine XI Palaiologos Dragases',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

# Load decorative images
def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column.jpg')

emperors = []


for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative; width: 960px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Decorative images
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 180, 100);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-90, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [12]:
import os
print(os.getcwd())
print(os.path.exists('constantinearch.png'))
print(os.path.exists('Gurlitt_Justinian_column.jpg'))
print(os.path.exists('ERE_List_20260226.csv'))

C:\Users\eric.cook\OneDrive - Mitratech Holdings, Inc\Documents\ERE Project
True
True
True

In [15]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Constantius II',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Michael VIII Palaiologos',
    'Constantine XI Palaiologos Dragases',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column.jpg')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative; width: 960px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Decorative images
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-90, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [16]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Constantius II',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Michael VIII Palaiologos',
    'Constantine XI Palaiologos Dragases',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column.jpg')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative; width: 960px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-90, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [17]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Constantius II',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Michael VIII Palaiologos',
    'Constantine XI Palaiologos Dragases',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column.jpg')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative; width: 960px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="960" height="720"></canvas>
  <canvas id="fg" width="960" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 960, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-90, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [18]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Constantius II',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Michael VIII Palaiologos',
    'Constantine XI Palaiologos Dragases',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column.jpg')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [19]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Constantius II',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Michael VIII Palaiologos',
    'Constantine XI Palaiologos Dragases',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column.jpg')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [20]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Constantius II',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Michael VIII Palaiologos',
    'Constantine XI Palaiologos Dragases',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [ ]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Constantius II',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Michael VIII Palaiologos',
    'Constantine XI Palaiologos Dragases',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Kantakouzenos':  '#4d5656',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

In [21]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
df.loc[df['Simple_Name_With_Epithets'] == 'Michael IV the Paphlagonian', 'Broad_Dynasty'] = 'Paphlagonian'
df.loc[df['Simple_Name_With_Epithets'] == 'Michael V Kalaphates', 'Broad_Dynasty'] = 'Paphlagonian'
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [22]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Constantine XI Palaiologos Dragases',
    'Eirene',
    'Valens',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Paphlagonian':   '#5d6d7e',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [26]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
print(df[['List_Number', 'Simple_Name_With_Epithets', 'Broad_Dynasty']].to_string())

    List_Number            Simple_Name_With_Epithets  Broad_Dynasty
0             1              Constantine I the Great  Constantinian
1             2                       Constantius II  Constantinian
2             3                  Julian the Apostate  Constantinian
3             4                               Jovian            NaN
4             5                               Valens  Valentinianic
5             6               Theodosios I the Great     Theodosian
6             7                             Arkadios     Theodosian
7             8                        Theodosios II     Theodosian
8             9                            Markianos     Theodosian
9            10                   Leo I the Thracian         Leonid
10           11                               Leo II         Leonid
11           12                                 Zeno         Leonid
12           13                           Basiliskos            NaN
13           14                         Anastasios I            NaN
14           15                             Justin I    Justinianic
15           16                Justinian I the Great    Justinianic
16           17                            Justin II    Justinianic
17           18          Tiberios II the Constantine            NaN
18           19                            Maurikios            NaN
19           20                               Phokas            NaN
20           21                           Herakleios      Heraklean
21           22                      Constantine III      Heraklean
22           23                           Heraklonas      Heraklean
23           24                          Constans II      Heraklean
24           25                       Constantine IV      Heraklean
25           26               Justinian II Slit-Nose      Heraklean
26           27                             Leontios            NaN
27           28                         Tiberios III            NaN
28           29                          Philippikos            NaN
29           30                        Anastasios II            NaN
30           31                       Theodosios III            NaN
31           32                 Leo III the Isaurian       Isaurian
32           33             Constantine V Kopronymos       Isaurian
33           34                           Artabasdos            NaN
34           35                    Leo IV the Khazar       Isaurian
35           36                       Constantine VI       Isaurian
36           37                               Eirene       Isaurian
37           38                         Nikephoros I            NaN
38           39                           Staurakios            NaN
39           40                   Michael I Rhangabe            NaN
40           41                   Leo V the Armenian            NaN
41           42               Michael II the Amorian        Amorian
42           43                           Theophilos        Amorian
43           44             Michael III the Drunkard        Amorian
44           45               Basil I the Macedonian     Macedonian
45           46                      Leo VI the Wise     Macedonian
46           47                            Alexander     Macedonian
47           48     Constantine VII Porphyrogennetos     Macedonian
48           49                  Romanos I Lekapenos     Macedonian
49           50                           Romanos II     Macedonian
50           51                 Nikephoros II Phokas     Macedonian
51           52                     John I Tzimiskes     Macedonian
52           53           Basil II the Bulgar-Slayer     Macedonian
53           54                     Constantine VIII     Macedonian
54           55                  Romanos III Argyros     Macedonian
55           56          Michael IV the Paphlagonian   Paphlagonian
56           57                 Michael V Kalaphates   Paphlagonian
57           58                  Zoe (with Theodora)     Macedonian
58           59                             Theodora     Macedonian
59           60            Constantine IX Monomachos     Macedonian
60           61                   Michael VI Bringas            NaN
61           62                     Isaac I Komnenos      Komnenian
62           63                 Constantine X Doukas         Doukas
63           64                  Romanos IV Diogenes         Doukas
64           65                   Michael VII Doukas         Doukas
65           66           Nikephoros III Botaneiates            NaN
66           67                   Alexios I Komnenos      Komnenian
67           68                     John II Komnenos      Komnenian
68           69                    Manuel I Komnenos      Komnenian
69           70                  Alexios II Komnenos      Komnenian
70           71                Andronikos I Komnenos      Komnenian
71           72                     Isaac II Angelos        Angelid
72           73                  Alexios III Angelos        Angelid
73           74                   Alexios IV Angelos        Angelid
74           75              Alexios V Mourtzouphlos            NaN
75           76                  Theodore I Laskaris       Laskarid
76           77             John III Doukas Vatatzes       Laskarid
77           78                 Theodore II Laskaris       Laskarid
78           79                     John IV Laskaris       Laskarid
79           80             Michael VIII Palaiologos    Palaiologan
80           81            Andronikos II Palaiologos    Palaiologan
81           82               Michael IX Palaiologos    Palaiologan
82           83           Andronikos III Palaiologos    Palaiologan
83           84                   John V Palaiologos    Palaiologan
84           85                John VI Kantakouzenos  Kantakouzenos
85           86            Andronikos IV Palaiologos    Palaiologan
86           87                 John VII Palaiologos    Palaiologan
87           88                Manuel II Palaiologos    Palaiologan
88           89                John VIII Palaiologos    Palaiologan
89           90  Constantine XI Palaiologos Dragases    Palaiologan

In [24]:
import pandas as pd

df = pd.read_csv('ERE_List_20260226.csv')

DYNASTY_FIXES = {
    'Jovian':                       '',
    'Basiliskos':                   '',
    'Anastasios I':                 '',
    'Tiberios II the Constantine':  '',
    'Maurikios':                    '',
    'Phokas':                       '',
    'Leontios':                     '',
    'Tiberios III':                 '',
    'Philippikos':                  '',
    'Anastasios II':                '',
    'Theodosios III':               '',
    'Artabasdos':                   '',
    'Nikephoros I':                 '',
    'Staurakios':                   '',
    'Michael I Rhangabe':           '',
    'Leo V the Armenian':           '',
    'Michael VI Bringas':           '',
    'Nikephoros III Botaneiates':   '',
    'Alexios V Mourtzouphlos':      '',
}

for name, dynasty in DYNASTY_FIXES.items():
    df.loc[df['Simple_Name_With_Epithets'] == name, 'Broad_Dynasty'] = dynasty

df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [28]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Constantine XI Palaiologos Dragases',
    'Eirene',
    'Valens',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Paphlagonian':   '#5d6d7e',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
  '':               '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [29]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
df['Broad_Dynasty'] = df['Broad_Dynasty'].fillna('')
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")
print(df[df['Broad_Dynasty'] == ''][['Simple_Name_With_Epithets', 'Broad_Dynasty']].to_string())

Done!
      Simple_Name_With_Epithets Broad_Dynasty
3                        Jovian
12                   Basiliskos
13                 Anastasios I
17  Tiberios II the Constantine
18                    Maurikios
19                       Phokas
26                     Leontios
27                 Tiberios III
28                  Philippikos
29                Anastasios II
30               Theodosios III
33                   Artabasdos
37                 Nikephoros I
38                   Staurakios
39           Michael I Rhangabe
40           Leo V the Armenian
60           Michael VI Bringas
65   Nikephoros III Botaneiates
74      Alexios V Mourtzouphlos

In [32]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Constantine XI Palaiologos Dragases',
    'Eirene',
    'Valens',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Paphlagonian':   '#5d6d7e',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
  '':               '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II the Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [31]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv', keep_default_na=False)
df['Broad_Dynasty'] = df['Broad_Dynasty'].replace('', 'Non-dynastic')
df['Broad_Dynasty'] = df['Broad_Dynasty'].fillna('Non-dynastic')
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")
print(df['Broad_Dynasty'].unique())

Done!
['Constantinian' 'Non-dynastic' 'Valentinianic' 'Theodosian' 'Leonid'
 'Justinianic' 'Heraklean' 'Isaurian' 'Amorian' 'Macedonian'
 'Paphlagonian' 'Komnenian' 'Doukas' 'Angelid' 'Laskarid' 'Palaiologan'
 'Kantakouzenos']

In [33]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
print(df['Broad_Dynasty'].unique())

['Constantinian' 'Non-dynastic' 'Valentinianic' 'Theodosian' 'Leonid'
 'Justinianic' 'Heraklean' 'Isaurian' 'Amorian' 'Macedonian'
 'Paphlagonian' 'Komnenian' 'Doukas' 'Angelid' 'Laskarid' 'Palaiologan'
 'Kantakouzenos']

In [18]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Constantine XI Palaiologos Dragases',
    'Eirene',
    'Valens',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#9b3dab"></div>Valentinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#2e6da4"></div>Leonid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#b7950b"></div>Doukas</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4d5656"></div>Kantakouzenos</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Paphlagonian':   '#5d6d7e',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
  '':               '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [13]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

In [14]:
df.loc[df['Simple_Name_With_Epithets'] == 'Tiberios II the Constantine', 'Simple_Name_With_Epithets'] = 'Tiberios II Constantine'

In [15]:
df.to_csv('ERE_List_20260226.csv', index=False)

In [17]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')

justinianic = [
    'Justin I',
    'Justinian I the Great',
    'Justin II',
    'Tiberios II Constantine',
    'Maurikios',
]

for name in justinianic:
    df.loc[df['Simple_Name_With_Epithets'] == name, 'Broad_Dynasty'] = 'Justinianic'

df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [19]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
df.loc[df['Broad_Dynasty'] == 'Kantakouzenos', 'Broad_Dynasty'] = 'Non-dynastic'
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [20]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Constantine XI Palaiologos Dragases',
    'Eirene',
    'Valens',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#9b3dab"></div>Valentinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#2e6da4"></div>Leonid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#b7950b"></div>Doukas</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Paphlagonian':   '#5d6d7e',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
  '':               '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [22]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
df.loc[df['Simple_Name_With_Epithets'] == 'Theodosios I the Great', 'Difficulty'] = 14
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [27]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Constantine XI Palaiologos Dragases',
    'Eirene',
    'Valens',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#9b3dab"></div>Valentinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#2e6da4"></div>Leonid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#b7950b"></div>Doukas</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Paphlagonian':   '#5d6d7e',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
  '':               '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy+3);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [25]:
import pandas as pd
df = pd.read_csv('ERE_List_20260226.csv')
df.loc[df['Simple_Name_With_Epithets'] == 'Zeno', 'Effectiveness'] = 14
df.to_csv('ERE_List_20260226.csv', index=False)
print("Done!")

Done!

In [28]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Constantine XI Palaiologos Dragases',
    'Eirene',
    'Valens',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#9b3dab"></div>Valentinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#2e6da4"></div>Leonid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#b7950b"></div>Doukas</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Paphlagonian':   '#5d6d7e',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
  '':               '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy + r*0.5);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [30]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Constantine XI Palaiologos Dragases',
    'Eirene',
    'Valens',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1100px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1100" height="720"></canvas>
  <canvas id="fg" width="1100" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#9b3dab"></div>Valentinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#2e6da4"></div>Leonid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#b7950b"></div>Doukas</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1100, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Paphlagonian':   '#5d6d7e',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
  '':               '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  bg.drawImage(colImg, W-95, PAD.top, 85, plotH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy + r*0.5);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [37]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Constantine XI Palaiologos Dragases',
    'Eirene',
    'Valens',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1280px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1280" height="720"></canvas>
  <canvas id="fg" width="1280" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#9b3dab"></div>Valentinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#2e6da4"></div>Leonid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#b7950b"></div>Doukas</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1280, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Paphlagonian':   '#5d6d7e',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
  '':               '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  const colH = H * 0.4;
  const colW = colH / 4;
  bg.drawImage(colImg, PAD.left + plotW + 5, PAD.top, colW, colH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy + r*0.5);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.

In [38]:
import pandas as pd
import json
import base64
import os

df = pd.read_csv('ERE_List_20260226.csv')

# Calculate composite score
df['Composite'] = ((df['Effectiveness'] * 0.6 + df['Difficulty'] * 0.4) * 5).round(1)

# Notable emperors to always label
NOTABLE = {
    'Constantine I the Great',
    'Julian the Apostate',
    'Theodosios I the Great',
    'Justinian I the Great',
    'Herakleios',
    'Basil II the Bulgar-Slayer',
    'Alexios I Komnenos',
    'Constantine VII Porphyrogennetos',
    'John II Komnenos',
    'Manuel I Komnenos',
    'Leo III the Isaurian',
    'Andronikos I Komnenos',
    'Constantine XI Palaiologos Dragases',
    'Eirene',
    'Valens',
}

def img_to_base64(path):
    if not path or str(path) in ('PLACEHOLDER', 'NOT_FOUND', 'NO_IMAGE', 'ERROR', 'nan'):
        return ''
    if not os.path.exists(str(path)):
        return ''
    ext = os.path.splitext(str(path))[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(str(path), 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

def load_deco(path):
    if not os.path.exists(path):
        return ''
    ext = os.path.splitext(path)[-1].lower().replace('.', '')
    if ext == 'jpg': ext = 'jpeg'
    try:
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode('utf-8')
        return f"data:image/{ext};base64,{data}"
    except:
        return ''

arch_b64   = load_deco('constantinearch.png')
column_b64 = load_deco('Gurlitt_Justinian_column-removebg-preview.png')

emperors = []

for _, row in df.iterrows():
    name = str(row['Simple_Name_With_Epithets'])
    emperors.append({
        "num":        int(row['List_Number']),
        "name":       name,
        "dynasty":    str(row['Broad_Dynasty']),
        "start":      int(row['Reign_Start']),
        "end":        int(row['Reign_End']),
        "years":      int(row['Reign_Length_Years']),
        "difficulty": int(row['Difficulty']),
        "effective":  int(row['Effectiveness']),
        "composite":  float(row['Composite']),
        "summary":    str(row['Summary']),
        "image":      img_to_base64(str(row.get('Local_Image', ''))),
        "label":      'notable' if name in NOTABLE else 'none',
    })
    print(f"  Embedding #{int(row['List_Number'])}: {name}")

data_json = json.dumps(emperors)

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eastern Roman Emperors – Difficulty vs Effectiveness</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #f8f5ef; color: #222; font-family: 'Georgia', serif; }}
  h1 {{ text-align: center; color: #8b1a1a; font-size: 1.9em; padding: 24px 20px 4px; letter-spacing: 1px; }}
  .subtitle {{ text-align: center; color: #666; font-size: 0.85em; padding-bottom: 16px; }}
  #chart-wrap {{ position: relative;   width: 1280px; height: 720px; margin: 0 auto; }}
  canvas {{ position: absolute; top: 0; left: 0; }}
  #tooltip {{
    position: fixed; background: rgba(255,252,245,0.98); border: 1px solid #8b1a1a;
    border-radius: 6px; padding: 12px; pointer-events: none; display: none;
    max-width: 290px; z-index: 100; box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  }}
  #tooltip img {{ width: 75px; height: 95px; object-fit: cover; border-radius: 4px; float: left; margin-right: 10px; }}
  #tooltip .tip-name    {{ color: #8b1a1a; font-size: 0.95em; font-weight: bold; margin-bottom: 3px; }}
  #tooltip .tip-dynasty {{ color: #888; font-size: 0.78em; margin-bottom: 3px; }}
  #tooltip .tip-reign   {{ color: #666; font-size: 0.76em; margin-bottom: 5px; }}
  #tooltip .tip-scores  {{ color: #222; font-size: 0.8em; margin-bottom: 5px; }}
  #tooltip .tip-summary {{ color: #555; font-size: 0.73em; line-height: 1.4; clear: both; margin-top: 8px; border-top: 1px solid #ddd; padding-top: 6px; }}
  #legend {{
    display: flex; justify-content: center; gap: 12px; padding: 10px 40px;
    flex-wrap: wrap; font-size: 0.75em; color: #555; max-width: 700px; margin: 0 auto;
  }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot  {{ width: 12px; height: 12px; border-radius: 50%; }}
  #key {{ text-align: center; font-size: 0.75em; color: #888; padding-bottom: 20px; }}
</style>
</head>
<body>

<h1>Eastern Roman Emperors</h1>
<p class="subtitle">Difficulty of Reign vs Effectiveness &nbsp;·&nbsp; Circle size = length of reign &nbsp;·&nbsp; Hover for details</p>

<div id="chart-wrap">
  <canvas id="bg" width="1280" height="720"></canvas>
  <canvas id="fg" width="1280" height="720"></canvas>
</div>

<div id="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#7b2d8b"></div>Constantinian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#9b3dab"></div>Valentinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#4a90d9"></div>Theodosian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#2e6da4"></div>Leonid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#c0392b"></div>Justinianic</div>
  <div class="legend-item"><div class="legend-dot" style="background:#e67e22"></div>Heraklean</div>
  <div class="legend-item"><div class="legend-dot" style="background:#27ae60"></div>Isaurian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#16a085"></div>Amorian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d4a017"></div>Macedonian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#8b1a1a"></div>Komnenian</div>
  <div class="legend-item"><div class="legend-dot" style="background:#b7950b"></div>Doukas</div>
  <div class="legend-item"><div class="legend-dot" style="background:#717d7e"></div>Angelid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#1a5276"></div>Laskarid</div>
  <div class="legend-item"><div class="legend-dot" style="background:#784212"></div>Palaiologan</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bbb"></div>Non-dynastic</div>
</div>
<p id="key">Circle size reflects length of reign · Name shown for notable emperors</p>

<div id="tooltip"></div>

<script>
const DATA = {data_json};
const W = 1280, H = 720;
const PAD = {{left:75, right:60, top:75, bottom:80}};
const plotW = W - PAD.left - PAD.right;
const plotH = H - PAD.top - PAD.bottom;
const MIN_R = 14, MAX_R = 52;
const maxYears = Math.max(...DATA.map(e => e.years));

function sx(d) {{ return PAD.left + ((d-1)/19)*plotW; }}
function sy(e) {{ return PAD.top + plotH - ((e-1)/19)*plotH; }}
function radius(y) {{ return MIN_R + (y/maxYears)*(MAX_R-MIN_R); }}

const DYNASTY_COLORS = {{
  'Constantinian':  '#7b2d8b',
  'Valentinianic':  '#9b3dab',
  'Theodosian':     '#4a90d9',
  'Leonid':         '#2e6da4',
  'Justinianic':    '#c0392b',
  'Heraklean':      '#e67e22',
  'Isaurian':       '#27ae60',
  'Amorian':        '#16a085',
  'Macedonian':     '#d4a017',
  'Komnenian':      '#8b1a1a',
  'Doukas':         '#b7950b',
  'Angelid':        '#717d7e',
  'Laskarid':       '#1a5276',
  'Palaiologan':    '#784212',
  'Paphlagonian':   '#5d6d7e',
  'N/A':            '#999',
  'Non-dynastic':   '#bbb',
  '':               '#bbb',
}};

function ringColor(dynasty) {{
  return DYNASTY_COLORS[dynasty] || '#2c7bb6';
}}

const bg = document.getElementById('bg').getContext('2d');

// Column drawn first so chart renders on top
const colImg = new Image();
colImg.onload = function() {{
  bg.globalAlpha = 0.4;
  const colH = H * 0.4;
  const colW = colH / 4;
  const colY = PAD.top + (plotH / 2) - (colH / 2);
  bg.drawImage(colImg, PAD.left + plotW + 5, colY, colW, colH);
  bg.globalAlpha = 1.0;
}};
if('{column_b64}') colImg.src = `{column_b64}`;

// Quadrant shading
const mx = sx(10), my = sy(10);
bg.fillStyle='rgba(255,210,0,0.08)';   bg.fillRect(PAD.left,PAD.top,mx-PAD.left,my-PAD.top);
bg.fillStyle='rgba(0,160,0,0.08)';     bg.fillRect(mx,PAD.top,PAD.left+plotW-mx,my-PAD.top);
bg.fillStyle='rgba(220,100,100,0.08)'; bg.fillRect(PAD.left,my,mx-PAD.left,PAD.top+plotH-my);
bg.fillStyle='rgba(150,150,150,0.07)'; bg.fillRect(mx,my,PAD.left+plotW-mx,PAD.top+plotH-my);

// Grid
bg.strokeStyle='#e0e0e0'; bg.lineWidth=1;
for(let i=1;i<=20;i++){{
  bg.beginPath(); bg.moveTo(sx(i),PAD.top); bg.lineTo(sx(i),PAD.top+plotH); bg.stroke();
  bg.beginPath(); bg.moveTo(PAD.left,sy(i)); bg.lineTo(PAD.left+plotW,sy(i)); bg.stroke();
}}

// Quadrant dividers
bg.strokeStyle='#aaa'; bg.lineWidth=1.5; bg.setLineDash([5,4]);
bg.beginPath(); bg.moveTo(mx,PAD.top); bg.lineTo(mx,PAD.top+plotH); bg.stroke();
bg.beginPath(); bg.moveTo(PAD.left,my); bg.lineTo(PAD.left+plotW,my); bg.stroke();
bg.setLineDash([]);

// Border
bg.strokeStyle='#999'; bg.lineWidth=2;
bg.strokeRect(PAD.left, PAD.top, plotW, plotH);

// Tick labels
bg.fillStyle='#999'; bg.font='11px Georgia'; bg.textAlign='center';
for(let i=2;i<=20;i+=2) bg.fillText(i, sx(i), PAD.top+plotH+18);
bg.textAlign='right';
for(let i=2;i<=20;i+=2) bg.fillText(i, PAD.left-8, sy(i)+4);

// Axis titles
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Difficulty of Reign →', PAD.left+plotW/2, H-28);
bg.font='11px Georgia'; bg.fillStyle='#999';
bg.fillText('Defined by how challenging was the state of the empire at ascension to the throne', PAD.left+plotW/2, H-12);
bg.save(); bg.translate(16,PAD.top+plotH/2); bg.rotate(-Math.PI/2);
bg.fillStyle='#666'; bg.font='13px Georgia'; bg.textAlign='center';
bg.fillText('Effectiveness →', 0, 0); bg.restore();

// Quadrant labels
bg.font='italic 10px Georgia'; bg.fillStyle='rgba(0,0,0,0.18)'; bg.textAlign='center';
bg.fillText('Easy + Effective', PAD.left+plotW*0.25, PAD.top+16);
bg.fillText('Hard + Effective', PAD.left+plotW*0.75, PAD.top+16);
bg.fillText('Easy + Ineffective', PAD.left+plotW*0.25, PAD.top+plotH-8);
bg.fillText('Hard + Ineffective', PAD.left+plotW*0.75, PAD.top+plotH-8);

// Watermark
bg.fillStyle='rgba(0,0,0,0.25)';
bg.font='italic 12px Georgia'; bg.textAlign='right';
bg.fillText('Created by Eric Cook', W-20, H-2);

// Arch drawn after chart so it sits on top
const archImg = new Image();
archImg.onload = function() {{
  bg.globalAlpha = 0.5;
  bg.drawImage(archImg, 5, 5, 220, 60);
  bg.globalAlpha = 1.0;
}};
if('{arch_b64}') archImg.src = `{arch_b64}`;

// Draw emperors
const fg = document.getElementById('fg').getContext('2d');
const positions = [];

DATA.forEach(emp => {{
  const cx = sx(emp.difficulty);
  const cy = sy(emp.effective);
  const r  = radius(emp.years);
  positions.push({{cx, cy, r, emp}});

  fg.beginPath(); fg.arc(cx,cy,r+3,0,Math.PI*2);
  fg.fillStyle = ringColor(emp.dynasty); fg.fill();

  if(emp.image) {{
    const img = new Image();
    img.onload = function() {{
      fg.save();
      fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
      fg.drawImage(img, cx-r, cy-r, r*2, r*2);
      fg.restore();
      if(emp.label === 'notable') {{
        const words = emp.name.split(' ');
        const shortName = words.slice(0,2).join(' ');
        const fontSize = Math.max(8, Math.min(11, r*0.35));
        fg.save();
        fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2); fg.clip();
        fg.fillStyle='rgba(0,0,0,0.45)'; fg.fillRect(cx-r,cy-r,r*2,r*2);
        fg.restore();
        fg.fillStyle='#fff';
        fg.font=`bold ${{fontSize}}px Georgia`;
        fg.textAlign='center';
        fg.fillText(shortName, cx, cy + r*0.5);
      }}
    }};
    img.src = emp.image;
  }} else {{
    fg.beginPath(); fg.arc(cx,cy,r,0,Math.PI*2);
    fg.fillStyle='#e8e0d0'; fg.fill();
    if(emp.label === 'notable') {{
      const words = emp.name.split(' ');
      const shortName = words.slice(0,2).join(' ');
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(8,Math.min(11,r*0.35))}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(shortName, cx, cy+3);
    }} else {{
      fg.fillStyle='#8b1a1a';
      fg.font=`bold ${{Math.max(9,r*0.4)}}px Georgia`;
      fg.textAlign='center';
      fg.fillText(emp.name.charAt(0), cx, cy+4);
    }}
  }}
}});

// Tooltip
const tip = document.getElementById('tooltip');
document.getElementById('fg').addEventListener('mousemove', function(e) {{
  const rect = this.getBoundingClientRect();
  const mx = e.clientX-rect.left, my = e.clientY-rect.top;
  let found = null;
  for(const p of [...positions].sort((a,b) => a.r-b.r)) {{
    const dx=mx-p.cx, dy=my-p.cy;
    if(Math.sqrt(dx*dx+dy*dy) < p.r+4) {{ found=p; break; }}
  }}
  if(found) {{
    const e2 = found.emp;
    const imgTag = e2.image ? `<img src="${{e2.image}}" onerror="this.style.display='none'">` : '';
    tip.innerHTML = `
      ${{imgTag}}
      <div class="tip-name">${{e2.name}}</div>
      <div class="tip-dynasty">${{e2.dynasty}}</div>
      <div class="tip-reign">${{e2.start}} – ${{e2.end}} (${{e2.years}} years)</div>
      <div class="tip-scores">Difficulty: ${{e2.difficulty}} &nbsp;|&nbsp; Effectiveness: ${{e2.effective}} &nbsp;|&nbsp; Score: ${{e2.composite}}</div>
      <div class="tip-summary">${{e2.summary}}</div>
    `;
    tip.style.display='block';
    let tx=e.clientX+15, ty=e.clientY-10;
    if(tx+300>window.innerWidth) tx=e.clientX-305;
    if(ty+320>window.innerHeight) ty=e.clientY-320;
    tip.style.left=tx+'px'; tip.style.top=ty+'px';
    this.style.cursor='pointer';
  }} else {{
    tip.style.display='none';
    this.style.cursor='default';
  }}
}});
document.getElementById('fg').addEventListener('mouseleave', ()=>tip.style.display='none');
</script>
</body>
</html>"""

with open('byzantine_scatter_v3.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("\nDone! Open byzantine_scatter_v3.html in your browser.")

  Embedding #1: Constantine I the Great
  Embedding #2: Constantius II
  Embedding #3: Julian the Apostate
  Embedding #4: Jovian
  Embedding #5: Valens
  Embedding #6: Theodosios I the Great
  Embedding #7: Arkadios
  Embedding #8: Theodosios II
  Embedding #9: Markianos
  Embedding #10: Leo I the Thracian
  Embedding #11: Leo II
  Embedding #12: Zeno
  Embedding #13: Basiliskos
  Embedding #14: Anastasios I
  Embedding #15: Justin I
  Embedding #16: Justinian I the Great
  Embedding #17: Justin II
  Embedding #18: Tiberios II Constantine
  Embedding #19: Maurikios
  Embedding #20: Phokas
  Embedding #21: Herakleios
  Embedding #22: Constantine III
  Embedding #23: Heraklonas
  Embedding #24: Constans II
  Embedding #25: Constantine IV
  Embedding #26: Justinian II Slit-Nose
  Embedding #27: Leontios
  Embedding #28: Tiberios III
  Embedding #29: Philippikos
  Embedding #30: Anastasios II
  Embedding #31: Theodosios III
  Embedding #32: Leo III the Isaurian
  Embedding #33: Constantine V Kopronymos
  Embedding #34: Artabasdos
  Embedding #35: Leo IV the Khazar
  Embedding #36: Constantine VI
  Embedding #37: Eirene
  Embedding #38: Nikephoros I
  Embedding #39: Staurakios
  Embedding #40: Michael I Rhangabe
  Embedding #41: Leo V the Armenian
  Embedding #42: Michael II the Amorian
  Embedding #43: Theophilos
  Embedding #44: Michael III the Drunkard
  Embedding #45: Basil I the Macedonian
  Embedding #46: Leo VI the Wise
  Embedding #47: Alexander
  Embedding #48: Constantine VII Porphyrogennetos
  Embedding #49: Romanos I Lekapenos
  Embedding #50: Romanos II
  Embedding #51: Nikephoros II Phokas
  Embedding #52: John I Tzimiskes
  Embedding #53: Basil II the Bulgar-Slayer
  Embedding #54: Constantine VIII
  Embedding #55: Romanos III Argyros
  Embedding #56: Michael IV the Paphlagonian
  Embedding #57: Michael V Kalaphates
  Embedding #58: Zoe (with Theodora)
  Embedding #59: Theodora
  Embedding #60: Constantine IX Monomachos
  Embedding #61: Michael VI Bringas
  Embedding #62: Isaac I Komnenos
  Embedding #63: Constantine X Doukas
  Embedding #64: Romanos IV Diogenes
  Embedding #65: Michael VII Doukas
  Embedding #66: Nikephoros III Botaneiates
  Embedding #67: Alexios I Komnenos
  Embedding #68: John II Komnenos
  Embedding #69: Manuel I Komnenos
  Embedding #70: Alexios II Komnenos
  Embedding #71: Andronikos I Komnenos
  Embedding #72: Isaac II Angelos
  Embedding #73: Alexios III Angelos
  Embedding #74: Alexios IV Angelos
  Embedding #75: Alexios V Mourtzouphlos
  Embedding #76: Theodore I Laskaris
  Embedding #77: John III Doukas Vatatzes
  Embedding #78: Theodore II Laskaris
  Embedding #79: John IV Laskaris
  Embedding #80: Michael VIII Palaiologos
  Embedding #81: Andronikos II Palaiologos
  Embedding #82: Michael IX Palaiologos
  Embedding #83: Andronikos III Palaiologos
  Embedding #84: John V Palaiologos
  Embedding #85: John VI Kantakouzenos
  Embedding #86: Andronikos IV Palaiologos
  Embedding #87: John VII Palaiologos
  Embedding #88: Manuel II Palaiologos
  Embedding #89: John VIII Palaiologos
  Embedding #90: Constantine XI Palaiologos Dragases

Done! Open byzantine_scatter_v3.html in your browser.